In [1]:
import sys
import os

sys.path.append(os.path.abspath(".."))

In [2]:
from src.data.alpaca_data import get_stock_bars
tickers = [
    "AAPL", "ADBE", "AMAT", "AMD", "AMZN",
    "AVGO", "CRM", "CSCO", "GOOGL", "IBM",
    "INTC", "META", "MSFT", "MU", "NFLX",
    "NOW", "NVDA", "ORCL", "QCOM", "TXN"
]
bars = get_stock_bars(tickers,"2021-01-01","2025-02-01")

In [3]:
from src.data.preprocessing import prepare_price_data,split_data
prices = prepare_price_data(bars)
formation_data,trading_data=split_data(prices,"2023-12-29")
formation_data

symbol,AAPL,ADBE,AMAT,AMD,AMZN,AVGO,CRM,CSCO,GOOGL,IBM,INTC,META,MSFT,MU,NFLX,NOW,NVDA,ORCL,QCOM,TXN
timestamp,,,,,,,,,,,,,,,,,,,,
2021-01-04 05:00:00+00:00,129.41,485.34,86.87,92.30,3186.63,425.22,220.31,43.96,1726.13,123.94,49.67,268.94,217.69,74.05,522.86,526.83,524.54,63.75,148.50,162.22
2021-01-05 05:00:00+00:00,131.01,485.69,89.60,92.77,3218.51,428.10,221.52,43.98,1740.05,126.14,50.61,270.97,217.90,77.26,520.80,531.97,536.19,62.96,152.43,163.41
2021-01-06 05:00:00+00:00,126.66,466.31,90.83,90.33,3138.38,425.46,216.15,44.40,1722.88,129.29,51.10,263.34,212.25,77.11,500.49,507.25,504.58,62.57,151.19,164.22
2021-01-07 05:00:00+00:00,130.92,477.74,94.56,95.16,3162.16,443.39,217.98,44.96,1774.34,128.99,52.19,268.74,218.29,79.11,508.89,511.41,533.76,63.07,155.70,167.94
2021-01-08 05:00:00+00:00,132.05,485.10,95.56,94.58,3182.70,445.64,222.04,45.06,1797.83,128.53,51.65,267.57,219.62,77.42,510.40,529.64,531.07,63.38,156.64,171.16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-12-22 05:00:00+00:00,193.60,598.75,162.05,139.60,153.42,1121.98,266.34,50.09,141.49,162.14,48.00,353.39,374.58,86.49,486.76,697.55,488.30,106.20,143.49,168.24
2023-12-26 05:00:00+00:00,193.05,598.26,164.28,143.41,153.41,1131.89,266.22,50.28,141.52,163.21,50.50,354.83,374.66,87.06,491.19,701.23,492.79,106.19,145.46,170.81
2023-12-27 05:00:00+00:00,193.15,596.08,164.21,146.07,153.34,1126.17,266.72,50.44,140.37,163.46,50.76,357.83,374.07,86.66,491.79,703.76,494.17,105.94,145.72,171.23
2023-12-28 05:00:00+00:00,193.58,595.52,163.12,148.76,153.38,1122.41,265.58,50.48,140.23,163.75,50.39,358.32,375.28,86.00,490.51,702.46,495.22,106.25,145.86,171.72
2023-12-29 05:00:00+00:00,192.53,596.60,162.07,147.41,151.94,1116.25,263.14,50.52,139.69,163.55,50.25,353.96,376.04,85.34,486.88,706.49,495.22,105.43,144.63,170.46

In [4]:
trading_data

symbol,AAPL,ADBE,AMAT,AMD,AMZN,AVGO,CRM,CSCO,GOOGL,IBM,INTC,META,MSFT,MU,NFLX,NOW,NVDA,ORCL,QCOM,TXN
timestamp,,,,,,,,,,,,,,,,,,,,
2024-01-02 05:00:00+00:00,185.64,580.07,154.37,138.58,149.93,1085.38,256.13,50.51,138.17,161.50,47.80,346.29,370.87,82.34,468.50,687.52,481.68,104.06,140.23,169.260
2024-01-03 05:00:00+00:00,184.25,571.79,151.45,135.32,148.47,1058.58,251.84,50.51,138.92,160.10,47.05,344.47,370.60,82.26,470.26,675.30,475.69,102.46,137.60,166.740
2024-01-04 05:00:00+00:00,181.91,567.05,149.31,136.01,144.57,1049.01,251.24,50.08,136.39,160.86,46.87,347.12,367.94,82.71,474.67,671.87,479.98,102.59,136.17,164.465
2024-01-05 05:00:00+00:00,181.18,564.60,149.00,138.58,145.24,1049.28,251.12,50.09,135.73,159.16,46.89,351.95,367.75,83.45,474.06,676.16,490.97,102.73,136.73,165.100
2024-01-08 05:00:00+00:00,185.56,580.55,151.56,146.18,149.10,1074.85,260.87,50.46,138.84,161.14,48.45,358.66,374.69,84.95,485.03,696.26,522.53,104.66,139.03,168.540
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-01-27 05:00:00+00:00,229.86,438.60,174.57,115.01,235.42,202.13,347.10,59.08,191.81,224.13,20.29,659.88,434.56,91.11,971.89,1140.62,118.42,158.28,171.18,187.030
2025-01-28 05:00:00+00:00,238.26,442.84,172.85,114.17,238.15,207.36,359.95,59.43,195.30,225.66,19.80,674.33,447.20,88.25,971.83,1170.39,128.99,164.00,171.55,180.570
2025-01-29 05:00:00+00:00,239.36,441.68,175.28,117.35,237.07,206.35,354.00,59.55,195.41,228.63,19.75,676.49,442.33,89.01,978.15,1143.63,123.70,162.02,171.71,180.270
2025-01-30 05:00:00+00:00,237.59,446.00,181.72,118.86,234.64,215.66,343.57,60.47,200.87,258.27,20.01,687.00,414.99,92.50,973.24,1012.75,124.65,170.38,171.93,185.270
2025-01-31 05:00:00+00:00,236.00,437.45,180.35,115.95,237.68,221.27,341.70,60.60,204.02,255.70,19.43,689.18,415.06,91.24,976.76,1018.38,120.07,170.06,172.93,184.610

In [5]:
from src.pairs.selection import select_pairs
formation_returns=formation_data.pct_change().dropna()
corr_matrix=formation_returns.corr()
candidate_pairs=[]
correlation_threshold=0.6
for i in range(len(corr_matrix.columns)):
    for j in range(i+1,len(corr_matrix.columns)):
        stock1=corr_matrix.columns[i]
        stock2=corr_matrix.columns[j]
        correlation=corr_matrix.iloc[i,j]
        if correlation>=correlation_threshold:
            candidate_pairs.append(
                (stock1,stock2,correlation)
            )
print(len(candidate_pairs))
selected_pairs=select_pairs(formation_data,candidate_pairs)
selected_pairs

33

[('AMD',
  'MSFT',
  np.float64(0.04959216212157262),
  np.float64(0.011520421568257217),
  np.float64(133.3845452264579),
  np.float64(1.553961517257702))]

In [6]:
from src.pairs.spread import calculate_spread

formation_spreads = []

for pair in selected_pairs:

    spread = calculate_spread(
        formation_data,
        pair,
        pair[4],   # alpha
        pair[5]    # beta
    )

    formation_spreads.append(
        (pair[0], pair[1], pair[2], pair[3], pair[4], pair[5], spread)
    )
formation_spreads

[('AMD',
  'MSFT',
  np.float64(0.04959216212157262),
  np.float64(0.011520421568257217),
  np.float64(133.3845452264579),
  np.float64(1.553961517257702),
  timestamp
  2021-01-04 05:00:00+00:00   -59.125193
  2021-01-05 05:00:00+00:00   -59.645555
  2021-01-06 05:00:00+00:00   -61.503889
  2021-01-07 05:00:00+00:00   -62.969523
  2021-01-08 05:00:00+00:00   -60.738226
                                 ...
  2023-12-22 05:00:00+00:00    24.262427
  2023-12-26 05:00:00+00:00    18.421834
  2023-12-27 05:00:00+00:00    13.698296
  2023-12-28 05:00:00+00:00    10.728139
  2023-12-29 05:00:00+00:00    13.585988
  Length: 753, dtype: float64)]

In [7]:
#calculation z scor for formation period
from src.strategy.zscore import calculate_zscore
from src.strategy.signals import calculate_thresholds

formation_zscores = []

for pair in formation_spreads:

    zscore = calculate_zscore(pair[6])

    lower_threshold, upper_threshold = calculate_thresholds(zscore)

    formation_zscores.append(
        (
            pair[0],
            pair[1],
            pair[2],
            pair[3],
            pair[4],
            pair[5],
            pair[6],
            zscore,
            lower_threshold,
            upper_threshold
        )
    )
formation_zscores

[('AMD',
  'MSFT',
  np.float64(0.04959216212157262),
  np.float64(0.011520421568257217),
  np.float64(133.3845452264579),
  np.float64(1.553961517257702),
  timestamp
  2021-01-04 05:00:00+00:00   -59.125193
  2021-01-05 05:00:00+00:00   -59.645555
  2021-01-06 05:00:00+00:00   -61.503889
  2021-01-07 05:00:00+00:00   -62.969523
  2021-01-08 05:00:00+00:00   -60.738226
                                 ...
  2023-12-22 05:00:00+00:00    24.262427
  2023-12-26 05:00:00+00:00    18.421834
  2023-12-27 05:00:00+00:00    13.698296
  2023-12-28 05:00:00+00:00    10.728139
  2023-12-29 05:00:00+00:00    13.585988
  Length: 753, dtype: float64,
  timestamp
  2021-01-04 05:00:00+00:00         NaN
  2021-01-05 05:00:00+00:00         NaN
  2021-01-06 05:00:00+00:00   -5.757594
  2021-01-07 05:00:00+00:00   -2.301477
  2021-01-08 05:00:00+00:00    0.041268
                                 ...
  2023-12-22 05:00:00+00:00    1.090897
  2023-12-26 05:00:00+00:00    0.827891
  2023-12-27 05:00:00+00:00    0.615503
  2023-12-28 05:00:00+00:00    0.481917
  2023-12-29 05:00:00+00:00    0.609579
  Length: 753, dtype: float64,
  np.float64(-0.7962765530142031),
  np.float64(2.4840177332105604))]

In [8]:
#to calculate trading period spread using formation period alpha beta
from src.pairs.spread import calculate_spread

trading_spreads = []

for pair in formation_zscores:

    spread = calculate_spread(
        trading_data,
        pair,
        pair[4],   # alpha from formation
        pair[5]    # beta from formation
    )

    trading_spreads.append(
        (
            pair[0],
            pair[1],
            pair[2],
            pair[3],
            pair[4],
            pair[5],
            pair[6],
            pair[7],
            pair[8],
            pair[9],
            spread
        )
    )
trading_spreads

[('AMD',
  'MSFT',
  np.float64(0.04959216212157262),
  np.float64(0.011520421568257217),
  np.float64(133.3845452264579),
  np.float64(1.553961517257702),
  timestamp
  2021-01-04 05:00:00+00:00   -59.125193
  2021-01-05 05:00:00+00:00   -59.645555
  2021-01-06 05:00:00+00:00   -61.503889
  2021-01-07 05:00:00+00:00   -62.969523
  2021-01-08 05:00:00+00:00   -60.738226
                                 ...
  2023-12-22 05:00:00+00:00    24.262427
  2023-12-26 05:00:00+00:00    18.421834
  2023-12-27 05:00:00+00:00    13.698296
  2023-12-28 05:00:00+00:00    10.728139
  2023-12-29 05:00:00+00:00    13.585988
  Length: 753, dtype: float64,
  timestamp
  2021-01-04 05:00:00+00:00         NaN
  2021-01-05 05:00:00+00:00         NaN
  2021-01-06 05:00:00+00:00   -5.757594
  2021-01-07 05:00:00+00:00   -2.301477
  2021-01-08 05:00:00+00:00    0.041268
                                 ...
  2023-12-22 05:00:00+00:00    1.090897
  2023-12-26 05:00:00+00:00    0.827891
  2023-12-27 05:00:00+00:00    0.615503
  2023-12-28 05:00:00+00:00    0.481917
  2023-12-29 05:00:00+00:00    0.609579
  Length: 753, dtype: float64,
  np.float64(-0.7962765530142031),
  np.float64(2.4840177332105604),
  timestamp
  2024-01-02 05:00:00+00:00     22.137468
  2024-01-03 05:00:00+00:00     26.933382
  2024-01-04 05:00:00+00:00     23.201149
  2024-01-05 05:00:00+00:00     19.017468
  2024-01-08 05:00:00+00:00     14.147360
                                  ...
  2025-01-27 05:00:00+00:00    122.454341
  2025-01-28 05:00:00+00:00    136.399668
  2025-01-29 05:00:00+00:00    126.588071
  2025-01-30 05:00:00+00:00     96.901589
  2025-01-31 05:00:00+00:00    101.493617
  Length: 272, dtype: float64)]

In [9]:
#to calculate z score for trading period(including past available formation data)
from src.strategy.zscore import calculate_zscore

formation_spread = formation_spreads[0][6]
trading_spread = trading_spreads[0][10]

trading_zscore = calculate_zscore(
    trading_spread,
    formation_spread
)

trading_zscore

timestamp
2024-01-02 05:00:00+00:00    0.992365
2024-01-03 05:00:00+00:00    1.206050
2024-01-04 05:00:00+00:00    1.036833
2024-01-05 05:00:00+00:00    0.847931
2024-01-08 05:00:00+00:00    0.628688
                               ...
2025-01-27 05:00:00+00:00    3.333809
2025-01-28 05:00:00+00:00    3.732639
2025-01-29 05:00:00+00:00    3.413037
2025-01-30 05:00:00+00:00    2.511423
2025-01-31 05:00:00+00:00    2.638369
Length: 272, dtype: float64

In [10]:
#WE GENERATE ENTRY EXIT SIGNALS NOW
#ENTER ON THRESHOLD
#EXIT FOR 1)MEAN REVERSION
#         2)MAX HOLDING PERIOD
#         3)STOP-LOSS

In [11]:
from src.strategy.half_life import calculate_half_life
half_life=calculate_half_life(formation_spread)
max_holding_period=2*half_life

In [12]:
#will need a for loop in future rn just working with one pair
import pandas as pd
entry=pd.Series("NO_EVENT",index=trading_zscore.index)
entry[trading_zscore<formation_zscores[0][8]]="LONG_ENTRY"
entry[trading_zscore>formation_zscores[0][9]]="SHORT_ENTRY"
entry
"""
NEED TO FIX REPEATED EVENTS DAY AFTER DAY COZ OF JUST THRESHOLD CONDITION.NEED TO IMPLEMENT CONDITION TO CHECK IF ALREADY ENTERED AND EXITED
"""

'\nNEED TO FIX REPEATED EVENTS DAY AFTER DAY COZ OF JUST THRESHOLD CONDITION.NEED TO IMPLEMENT CONDITION TO CHECK IF ALREADY ENTERED AND EXITED\n'

In [13]:
#EXIT-CONDITIONS1)MEAN REVERSION
#               2)MAX HOLDING PERIOD
#               3)STOP LOSS

In [14]:
#CANT MAKE ENTRY AND EXIT SEPARATELY

In [15]:
#position=0(currently flat)
#position=1(currently long spread)
#position=-1(currently short spread)

In [16]:
position=0
position_df=pd.DataFrame(trading_zscore.copy())
position_df=position_df.rename(columns={0:"zscore"})
position_df["position"]=0
position_df["event"]="NO_EVENT"
entry_day=None
for i in range(len(position_df)):
        if position==0:
            if position_df.iloc[i,0]<formation_zscores[0][8]:#long entry check
                position=1
                entry_day=i
                position_df.loc[position_df.index[i],"event"]="LONG_ENTRY"
            elif position_df.iloc[i,0]>formation_zscores[0][9]:#short entry check
                position=-1
                entry_day=i
                position_df.loc[position_df.index[i],"event"]="SHORT_ENTRY"
                
        
        elif position==1:
            #check mean reversion on long position
            if position_df.iloc[i,0]>=formation_zscores[0][7].quantile(0.5):
                position=0#exit
                entry_day=None
                position_df.loc[position_df.index[i],"event"]="LONG_MEAN_EXIT"
            #check stop loss
            elif position_df.iloc[i,0]<=formation_zscores[0][8]-1:
                position=2#exit-long stop loss
                entry_day=None
                position_df.loc[position_df.index[i],"event"]="LONG_STOPLOSS"
                
            #check max holding days
            elif i-entry_day>=max_holding_period:
                position=0
                entry_day=None
                position_df.loc[position_df.index[i],"event"]="LONG_MAX_HOLDING"
                
        
        elif position==-1:
            #check mean reversion on short position
            if position_df.iloc[i,0]<=formation_zscores[0][7].quantile(0.5):
                position=0#exit
                entry_day=None
                position_df.loc[position_df.index[i],"event"]="SHORT_MEAN_EXIT"
            #check stop loss
            elif position_df.iloc[i,0]>=formation_zscores[0][9]+1:
                position=-2#exit-short stop loss
                entry_day=None
                position_df.loc[position_df.index[i],"event"]="SHORT_STOPLOSS"
            elif i-entry_day>=max_holding_period:
                position=0
                entry_day=None
                position_df.loc[position_df.index[i],"event"]="SHORT_MAX_HOLDING"
print(f"upper threshold:{formation_zscores[0][9]}\nlower threshold:{formation_zscores[0][8]}")
position_df

upper threshold:2.4840177332105604
lower threshold:-0.7962765530142031

                             zscore  position     event
timestamp
2024-01-02 05:00:00+00:00  0.992365         0  NO_EVENT
2024-01-03 05:00:00+00:00  1.206050         0  NO_EVENT
2024-01-04 05:00:00+00:00  1.036833         0  NO_EVENT
2024-01-05 05:00:00+00:00  0.847931         0  NO_EVENT
2024-01-08 05:00:00+00:00  0.628688         0  NO_EVENT
...                             ...       ...       ...
2025-01-27 05:00:00+00:00  3.333809         0  NO_EVENT
2025-01-28 05:00:00+00:00  3.732639         0  NO_EVENT
2025-01-29 05:00:00+00:00  3.413037         0  NO_EVENT
2025-01-30 05:00:00+00:00  2.511423         0  NO_EVENT
2025-01-31 05:00:00+00:00  2.638369         0  NO_EVENT

[272 rows x 3 columns]

In [17]:
position = 0

position_df = pd.DataFrame(trading_zscore.copy())
position_df = position_df.rename(columns={0: "zscore"})

position_df["position"] = 0
position_df["event"] = "NO_EVENT"

entry_day = None

# Formation-period thresholds
lower_threshold = formation_zscores[0][8]
upper_threshold = formation_zscores[0][9]
formation_median = formation_zscores[0][7].quantile(0.5)

for i in range(len(position_df)):

    current_zscore = position_df.iloc[i, 0]

    # -------------------------
    # FLAT: look for new entry
    # -------------------------
    if position == 0:

        if current_zscore < lower_threshold:
            position = 1
            entry_day = i

            position_df.loc[position_df.index[i], "event"] = "LONG_ENTRY"

        elif current_zscore > upper_threshold:
            position = -1
            entry_day = i

            position_df.loc[position_df.index[i], "event"] = "SHORT_ENTRY"


    # -------------------------
    # LONG POSITION
    # -------------------------
    elif position == 1:

        # Mean reversion
        if current_zscore >= formation_median:
            position = 0
            entry_day = None

            position_df.loc[
                position_df.index[i], "event"
            ] = "LONG_MEAN_EXIT"

        # Stop loss
        elif current_zscore <= lower_threshold - 1:
            position = 2
            entry_day = None

            position_df.loc[
                position_df.index[i], "event"
            ] = "LONG_STOPLOSS"

        # Maximum holding period
        elif i - entry_day >= max_holding_period:
            position = 0
            entry_day = None

            position_df.loc[
                position_df.index[i], "event"
            ] = "LONG_MAX_HOLDING"


    # -------------------------
    # SHORT POSITION
    # -------------------------
    elif position == -1:

        # Mean reversion
        if current_zscore <= formation_median:
            position = 0
            entry_day = None

            position_df.loc[
                position_df.index[i], "event"
            ] = "SHORT_MEAN_EXIT"

        # Stop loss
        elif current_zscore >= upper_threshold + 1:
            position = -2
            entry_day = None

            position_df.loc[
                position_df.index[i], "event"
            ] = "SHORT_STOPLOSS"

        # Maximum holding period
        elif i - entry_day >= max_holding_period:
            position = 0
            entry_day = None

            position_df.loc[
                position_df.index[i], "event"
            ] = "SHORT_MAX_HOLDING"


    # -------------------------
    # COOLDOWN AFTER LONG STOP
    # -------------------------
    elif position == 2:

        # Wait until z-score comes back
        # inside the long-entry region
        if current_zscore > lower_threshold:
            position = 0

            position_df.loc[
                position_df.index[i], "event"
            ] = "LONG_REENTRY_UNLOCK"


    # -------------------------
    # COOLDOWN AFTER SHORT STOP
    # -------------------------
    elif position == -2:

        # Wait until z-score comes back
        # inside the short-entry region
        if current_zscore < upper_threshold:
            position = 0

            position_df.loc[
                position_df.index[i], "event"
            ] = "SHORT_REENTRY_UNLOCK"


    # Store current state
    position_df.loc[
        position_df.index[i], "position"
    ] = position


print(
    f"Upper threshold: {upper_threshold}\n"
    f"Lower threshold: {lower_threshold}\n"
    f"Formation median: {formation_median}"
)

pd.set_option("display.max_rows", None)

position_df

Upper threshold: 2.4840177332105604
Lower threshold: -0.7962765530142031
Formation median: 0.8957413403422575

                             zscore  position                event
timestamp
2024-01-02 05:00:00+00:00  0.992365         0             NO_EVENT
2024-01-03 05:00:00+00:00  1.206050         0             NO_EVENT
2024-01-04 05:00:00+00:00  1.036833         0             NO_EVENT
2024-01-05 05:00:00+00:00  0.847931         0             NO_EVENT
2024-01-08 05:00:00+00:00  0.628688         0             NO_EVENT
2024-01-09 05:00:00+00:00  0.462826         0             NO_EVENT
2024-01-10 05:00:00+00:00  0.825785         0             NO_EVENT
2024-01-11 05:00:00+00:00  0.944591         0             NO_EVENT
2024-01-12 05:00:00+00:00  1.217545         0             NO_EVENT
2024-01-16 05:00:00+00:00  0.447231         0             NO_EVENT
2024-01-17 05:00:00+00:00  0.311233         0             NO_EVENT
2024-01-18 05:00:00+00:00  0.334143         0             NO_EVENT
2024-01-19 05:00:00+00:00 -0.257636         0             NO_EVENT
2024-01-22 05:00:00+00:00  0.068149         0             NO_EVENT
2024-01-23 05:00:00+00:00  0.158858         0             NO_EVENT
2024-01-24 05:00:00+00:00 -0.366995         0             NO_EVENT
2024-01-25 05:00:00+00:00 -0.405469         0             NO_EVENT
2024-01-26 05:00:00+00:00 -0.231808         0             NO_EVENT
2024-01-29 05:00:00+00:00 -0.011171         0             NO_EVENT
2024-01-30 05:00:00+00:00  0.342481         0             NO_EVENT
2024-01-31 05:00:00+00:00  0.151718         0             NO_EVENT
2024-02-01 05:00:00+00:00  0.235859         0             NO_EVENT
2024-02-02 05:00:00+00:00  0.067631         0             NO_EVENT
2024-02-05 05:00:00+00:00  0.056733         0             NO_EVENT
2024-02-06 05:00:00+00:00  0.496152         0             NO_EVENT
2024-02-07 05:00:00+00:00  0.668081         0             NO_EVENT
2024-02-08 05:00:00+00:00  0.782124         0             NO_EVENT
2024-02-09 05:00:00+00:00  0.852743         0             NO_EVENT
2024-02-12 05:00:00+00:00  0.652172         0             NO_EVENT
2024-02-13 05:00:00+00:00  0.272282         0             NO_EVENT
2024-02-14 05:00:00+00:00 -0.088883         0             NO_EVENT
2024-02-15 05:00:00+00:00 -0.084982         0             NO_EVENT
2024-02-16 05:00:00+00:00  0.005516         0             NO_EVENT
2024-02-20 05:00:00+00:00  0.525598         0             NO_EVENT
2024-02-21 05:00:00+00:00  0.596369         0             NO_EVENT
2024-02-22 05:00:00+00:00 -0.215478         0             NO_EVENT
2024-02-23 05:00:00+00:00  0.102790         0             NO_EVENT
2024-02-26 05:00:00+00:00  0.011279         0             NO_EVENT
2024-02-27 05:00:00+00:00 -0.132416         0             NO_EVENT
2024-02-28 05:00:00+00:00 -0.017908         0             NO_EVENT
2024-02-29 05:00:00+00:00 -0.881727         1           LONG_ENTRY
2024-03-01 05:00:00+00:00 -1.512943         1             NO_EVENT
2024-03-04 05:00:00+00:00 -1.729043         1             NO_EVENT
2024-03-05 05:00:00+00:00 -2.267345         2        LONG_STOPLOSS
2024-03-06 05:00:00+00:00 -2.672390         2             NO_EVENT
2024-03-07 05:00:00+00:00 -2.392503         2             NO_EVENT
2024-03-08 05:00:00+00:00 -2.234451         2             NO_EVENT
2024-03-11 04:00:00+00:00 -1.673087         2             NO_EVENT
2024-03-12 04:00:00+00:00 -1.490658         2             NO_EVENT
2024-03-13 04:00:00+00:00 -0.939304         2             NO_EVENT
2024-03-14 04:00:00+00:00  0.056248         0  LONG_REENTRY_UNLOCK
2024-03-15 04:00:00+00:00 -0.618906         0             NO_EVENT
2024-03-18 04:00:00+00:00 -0.549238         0             NO_EVENT
2024-03-19 04:00:00+00:00  0.280642         0             NO_EVENT
2024-03-20 04:00:00+00:00  0.570681         0             NO_EVENT
2024-03-21 04:00:00+00:00  0.830179         0             NO_EVENT
2024-03-22 04:00:00+00:00  0.733025         0             NO_EVENT
2024-03-25 04:00:00+00:00  0.538784         0             NO_EVENT
2024-03-26 04:00:00+00:00  0.537049         0             NO_EVENT
2024-03-27 04:00:00+00:00  0.406149         0             NO_EVENT
2024-03-28 04:00:00+00:00  0.310706         0             NO_EVENT
2024-04-01 04:00:00+00:00  0.284364         0             NO_EVENT
2024-04-02 04:00:00+00:00  0.468514         0             NO_EVENT
2024-04-03 04:00:00+00:00  0.278028         0             NO_EVENT
2024-04-04 04:00:00+00:00  1.211548         0             NO_EVENT
2024-04-05 04:00:00+00:00  1.232659         0             NO_EVENT
2024-04-08 04:00:00+00:00  1.225253         0             NO_EVENT
2024-04-09 04:00:00+00:00  1.237958         0             NO_EVENT
2024-04-10 04:00:00+00:00  1.355133         0             NO_EVENT
2024-04-11 04:00:00+00:00  1.327908         0             NO_EVENT
2024-04-12 04:00:00+00:00  1.559860         0             NO_EVENT
2024-04-15 04:00:00+00:00  1.391590         0             NO_EVENT
2024-04-16 04:00:00+00:00  1.211605         0             NO_EVENT
2024-04-17 04:00:00+00:00  1.747182         0             NO_EVENT
2024-04-18 04:00:00+00:00  1.328214         0             NO_EVENT
2024-04-19 04:00:00+00:00  1.684211         0             NO_EVENT
2024-04-22 04:00:00+00:00  1.623364         0             NO_EVENT
2024-04-23 04:00:00+00:00  1.663305         0             NO_EVENT
2024-04-24 04:00:00+00:00  1.763259         0             NO_EVENT
2024-04-25 04:00:00+00:00  1.169750         0             NO_EVENT
2024-04-26 04:00:00+00:00  1.240764         0             NO_EVENT
2024-04-29 04:00:00+00:00  0.862047         0             NO_EVENT
2024-04-30 04:00:00+00:00  0.409488         0             NO_EVENT
2024-05-01 04:00:00+00:00  1.642214         0             NO_EVENT
2024-05-02 04:00:00+00:00  1.636939         0             NO_EVENT
2024-05-03 04:00:00+00:00  1.719169         0             NO_EVENT
2024-05-06 04:00:00+00:00  1.662921         0             NO_EVENT
2024-05-07 04:00:00+00:00  1.565468         0             NO_EVENT
2024-05-08 04:00:00+00:00  1.671797         0             NO_EVENT
2024-05-09 04:00:00+00:00  1.832313         0             NO_EVENT
2024-05-10 04:00:00+00:00  1.967592         0             NO_EVENT
2024-05-13 04:00:00+00:00  2.010437         0             NO_EVENT
2024-05-14 04:00:00+00:00  1.951298         0             NO_EVENT
2024-05-15 04:00:00+00:00  1.786765         0             NO_EVENT
2024-05-16 04:00:00+00:00  1.487648         0             NO_EVENT
2024-05-17 04:00:00+00:00  1.323567         0             NO_EVENT
2024-05-20 04:00:00+00:00  1.420202         0             NO_EVENT
2024-05-21 04:00:00+00:00  1.695163         0             NO_EVENT
2024-05-22 04:00:00+00:00  1.697633         0             NO_EVENT
2024-05-23 04:00:00+00:00  1.886836         0             NO_EVENT
2024-05-24 04:00:00+00:00  1.615895         0             NO_EVENT
2024-05-28 04:00:00+00:00  1.261565         0             NO_EVENT
2024-05-29 04:00:00+00:00  1.650181         0             NO_EVENT
2024-05-30 04:00:00+00:00  0.901661         0             NO_EVENT
2024-05-31 04:00:00+00:00  0.910651         0             NO_EVENT
2024-06-03 04:00:00+00:00  1.067262         0             NO_EVENT
2024-06-04 04:00:00+00:00  1.420098         0             NO_EVENT
2024-06-05 04:00:00+00:00  1.344758         0             NO_EVENT
2024-06-06 04:00:00+00:00  1.323397         0             NO_EVENT
2024-06-07 04:00:00+00:00  1.217857         0             NO_EVENT
2024-06-10 04:00:00+00:00  1.903806         0             NO_EVENT
2024-06-11 04:00:00+00:00  2.202471         0             NO_EVENT
2024-06-12 04:00:00+00:00  2.473562         0             NO_EVENT
2024-06-13 04:00:00+00:00  2.508991        -1          SHORT_ENTRY
2024-06-14 04:00:00+00:00  2.559543        -1             NO_EVENT
2024-06-17 04:00:00+00:00  2.881451        -1             NO_EVENT
2024-06-18 04:00:00+00:00  3.030748        -1             NO_EVENT
2024-06-20 04:00:00+00:00  2.510181        -1             NO_EVENT
2024-06-21 04:00:00+00:00  2.710273        -1             NO_EVENT
2024-06-24 04:00:00+00:00  2.672408        -1             NO_EVENT
2024-06-25 04:00:00+00:00  2.798975        -1             NO_EVENT
2024-06-26 04:00:00+00:00  3.013702        -1             NO_EVENT
2024-06-27 04:00:00+00:00  2.899445        -1             NO_EVENT
2024-06-28 04:00:00+00:00  2.459034        -1             NO_EVENT
2024-07-01 04:00:00+00:00  3.150144        -1             NO_EVENT
2024-07-02 04:00:00+00:00  2.809570        -1             NO_EVENT
2024-07-03 04:00:00+00:00  2.883373        -1             NO_EVENT
2024-07-05 04:00:00+00:00  2.635932        -1             NO_EVENT
2024-07-08 04:00:00+00:00  2.136986        -1             NO_EVENT
2024-07-09 04:00:00+00:00  1.957077        -1             NO_EVENT
2024-07-10 04:00:00+00:00  1.790237        -1             NO_EVENT
2024-07-11 04:00:00+00:00  1.442537        -1             NO_EVENT
2024-07-12 04:00:00+00:00  1.414026        -1             NO_EVENT
2024-07-15 04:00:00+00:00  1.541172        -1             NO_EVENT
2024-07-16 04:00:00+00:00  1.501688        -1             NO_EVENT
2024-07-17 04:00:00+00:00  2.401320        -1             NO_EVENT
2024-07-18 04:00:00+00:00  2.495281        -1             NO_EVENT
2024-07-19 04:00:00+00:00  2.616855        -1             NO_EVENT
2024-07-22 04:00:00+00:00  2.571618        -1             NO_EVENT
2024-07-23 04:00:00+00:00  2.754481        -1             NO_EVENT
2024-07-24 04:00:00+00:00  2.685603        -1             NO_EVENT
2024-07-25 04:00:00+00:00  2.645581        -1             NO_EVENT
2024-07-26 04:00:00+00:00  2.804040        -1             NO_EVENT
2024-07-29 04:00:00+00:00  2.862957        -1             NO_EVENT
2024-07-30 04:00:00+00:00  2.778260        -1             NO_EVENT
2024-07-31 04:00:00+00:00  2.215495        -1             NO_EVENT
2024-08-01 04:00:00+00:00  2.888306        -1             NO_EVENT
2024-08-02 04:00:00+00:00  2.538630        -1             NO_EVENT
2024-08-05 04:00:00+00:00  1.867306        -1             NO_EVENT
2024-08-06 04:00:00+00:00  2.317203        -1             NO_EVENT
2024-08-07 04:00:00+00:00  2.354380        -1             NO_EVENT
2024-08-08 04:00:00+00:00  2.050264        -1             NO_EVENT
2024-08-09 04:00:00+00:00  2.296461        -1             NO_EVENT
2024-08-12 04:00:00+00:00  2.169082        -1             NO_EVENT
2024-08-13 04:00:00+00:00  2.178640        -1             NO_EVENT
2024-08-14 04:00:00+00:00  2.304017        -1             NO_EVENT
2024-08-15 04:00:00+00:00  2.062058        -1             NO_EVENT
2024-08-16 04:00:00+00:00  1.886742        -1             NO_EVENT
2024-08-19 04:00:00+00:00  1.599817        -1             NO_EVENT
2024-08-20 04:00:00+00:00  1.655120        -1             NO_EVENT
2024-08-21 04:00:00+00:00  1.542944        -1             NO_EVENT
2024-08-22 04:00:00+00:00  1.574590        -1             NO_EVENT
2024-08-23 04:00:00+00:00  1.424656        -1             NO_EVENT
2024-08-26 04:00:00+00:00  1.591906        -1             NO_EVENT
2024-08-27 04:00:00+00:00  1.572007        -1             NO_EVENT
2024-08-28 04:00:00+00:00  1.690434        -1             NO_EVENT
2024-08-29 04:00:00+00:00  1.833934        -1             NO_EVENT
2024-08-30 04:00:00+00:00  1.801122        -1             NO_EVENT
2024-09-03 04:00:00+00:00  2.189319        -1             NO_EVENT
2024-09-04 04:00:00+00:00  1.931177        -1             NO_EVENT
2024-09-05 04:00:00+00:00  1.990870         0    SHORT_MAX_HOLDING
2024-09-06 04:00:00+00:00  2.031502         0             NO_EVENT
2024-09-09 04:00:00+00:00  1.954962         0             NO_EVENT
2024-09-10 04:00:00+00:00  1.994660         0             NO_EVENT
2024-09-11 04:00:00+00:00  1.911721         0             NO_EVENT
2024-09-12 04:00:00+00:00  2.002289         0             NO_EVENT
2024-09-13 04:00:00+00:00  2.041658         0             NO_EVENT
2024-09-16 04:00:00+00:00  2.077338         0             NO_EVENT
2024-09-17 04:00:00+00:00  2.286355         0             NO_EVENT
2024-09-18 04:00:00+00:00  2.263555         0             NO_EVENT
2024-09-19 04:00:00+00:00  2.061355         0             NO_EVENT
2024-09-20 04:00:00+00:00  1.974387         0             NO_EVENT
2024-09-23 04:00:00+00:00  1.858184         0             NO_EVENT
2024-09-24 04:00:00+00:00  1.603418         0             NO_EVENT
2024-09-25 04:00:00+00:00  1.496701         0             NO_EVENT
2024-09-26 04:00:00+00:00  1.151205         0             NO_EVENT
2024-09-27 04:00:00+00:00  1.208376         0             NO_EVENT
2024-09-30 04:00:00+00:00  1.306292         0             NO_EVENT
2024-10-01 04:00:00+00:00  1.198259         0             NO_EVENT
2024-10-02 04:00:00+00:00  1.063864         0             NO_EVENT
2024-10-03 04:00:00+00:00  0.865221         0             NO_EVENT
2024-10-04 04:00:00+00:00  0.385937         0             NO_EVENT
2024-10-07 04:00:00+00:00  0.141411         0             NO_EVENT
2024-10-08 04:00:00+00:00  0.227109         0             NO_EVENT
2024-10-09 04:00:00+00:00  0.430474         0             NO_EVENT
2024-10-10 04:00:00+00:00  0.762700         0             NO_EVENT
2024-10-11 04:00:00+00:00  0.566963         0             NO_EVENT
2024-10-14 04:00:00+00:00  0.821054         0             NO_EVENT
2024-10-15 04:00:00+00:00  1.300872         0             NO_EVENT
2024-10-16 04:00:00+00:00  1.231562         0             NO_EVENT
2024-10-17 04:00:00+00:00  1.245201         0             NO_EVENT
2024-10-18 04:00:00+00:00  1.312729         0             NO_EVENT
2024-10-21 04:00:00+00:00  1.223101         0             NO_EVENT
2024-10-22 04:00:00+00:00  1.761773         0             NO_EVENT
2024-10-23 04:00:00+00:00  1.718354         0             NO_EVENT
2024-10-24 04:00:00+00:00  1.689290         0             NO_EVENT
2024-10-25 04:00:00+00:00  1.652242         0             NO_EVENT
2024-10-28 04:00:00+00:00  1.381122         0             NO_EVENT
2024-10-29 04:00:00+00:00  1.214685         0             NO_EVENT
2024-10-30 04:00:00+00:00  2.241108         0             NO_EVENT
2024-10-31 04:00:00+00:00  1.533048         0             NO_EVENT
2024-11-01 04:00:00+00:00  1.803228         0             NO_EVENT
2024-11-04 05:00:00+00:00  1.794767         0             NO_EVENT
2024-11-05 05:00:00+00:00  1.846496         0             NO_EVENT
2024-11-06 05:00:00+00:00  1.965363         0             NO_EVENT
2024-11-07 05:00:00+00:00  1.884516         0             NO_EVENT
2024-11-08 05:00:00+00:00  1.880678         0             NO_EVENT
2024-11-11 05:00:00+00:00  1.745611         0             NO_EVENT
2024-11-12 05:00:00+00:00  2.133881         0             NO_EVENT
2024-11-13 05:00:00+00:00  2.450098         0             NO_EVENT
2024-11-14 05:00:00+00:00  2.528190        -1          SHORT_ENTRY
2024-11-15 05:00:00+00:00  2.310856        -1             NO_EVENT
2024-11-18 05:00:00+00:00  2.105572        -1             NO_EVENT
2024-11-19 05:00:00+00:00  2.146919        -1             NO_EVENT
2024-11-20 05:00:00+00:00  2.158021        -1             NO_EVENT
2024-11-21 05:00:00+00:00  2.064241        -1             NO_EVENT
2024-11-22 05:00:00+00:00  2.158414        -1             NO_EVENT
2024-11-25 05:00:00+00:00  2.062068        -1             NO_EVENT
2024-11-26 05:00:00+00:00  2.572231        -1             NO_EVENT
2024-11-27 05:00:00+00:00  2.466537        -1             NO_EVENT
2024-11-29 05:00:00+00:00  2.422911        -1             NO_EVENT
2024-12-02 05:00:00+00:00  2.411973        -1             NO_EVENT
2024-12-03 05:00:00+00:00  2.415775        -1             NO_EVENT
2024-12-04 05:00:00+00:00  2.516162        -1             NO_EVENT
2024-12-05 05:00:00+00:00  2.832078        -1             NO_EVENT
2024-12-06 05:00:00+00:00  3.002574        -1             NO_EVENT
2024-12-09 05:00:00+00:00  3.489555        -2       SHORT_STOPLOSS
2024-12-10 05:00:00+00:00  3.541650        -2             NO_EVENT
2024-12-11 05:00:00+00:00  3.583451        -2             NO_EVENT
2024-12-12 05:00:00+00:00  3.554248        -2             NO_EVENT
2024-12-13 05:00:00+00:00  3.647016        -2             NO_EVENT
2024-12-16 05:00:00+00:00  3.778358        -2             NO_EVENT
2024-12-17 05:00:00+00:00  3.932869        -2             NO_EVENT
2024-12-18 05:00:00+00:00  3.519209        -2             NO_EVENT
2024-12-19 05:00:00+00:00  3.613994        -2             NO_EVENT
2024-12-20 05:00:00+00:00  3.557735        -2             NO_EVENT
2024-12-23 05:00:00+00:00  3.215476        -2             NO_EVENT
2024-12-24 05:00:00+00:00  3.244701        -2             NO_EVENT
2024-12-26 05:00:00+00:00  3.248548        -2             NO_EVENT
2024-12-27 05:00:00+00:00  2.978961        -2             NO_EVENT
2024-12-30 05:00:00+00:00  2.918547        -2             NO_EVENT
2024-12-31 05:00:00+00:00  2.880271        -2             NO_EVENT
2025-01-02 05:00:00+00:00  2.781826        -2             NO_EVENT
2025-01-03 05:00:00+00:00  2.687294        -2             NO_EVENT
2025-01-06 05:00:00+00:00  2.613139        -2             NO_EVENT
2025-01-07 05:00:00+00:00  2.538887        -2             NO_EVENT
2025-01-08 05:00:00+00:00  2.867391        -2             NO_EVENT
2025-01-10 05:00:00+00:00  2.961217        -2             NO_EVENT
2025-01-13 05:00:00+00:00  2.829721        -2             NO_EVENT
2025-01-14 05:00:00+00:00  2.829389        -2             NO_EVENT
2025-01-15 05:00:00+00:00  2.960582        -2             NO_EVENT
2025-01-16 05:00:00+00:00  2.965962        -2             NO_EVENT
2025-01-17 05:00:00+00:00  2.944236        -2             NO_EVENT
2025-01-21 05:00:00+00:00  2.874889        -2             NO_EVENT
2025-01-22 05:00:00+00:00  3.333625        -2             NO_EVENT
2025-01-23 05:00:00+00:00  3.363060        -2             NO_EVENT
2025-01-24 05:00:00+00:00  3.272016        -2             NO_EVENT
2025-01-27 05:00:00+00:00  3.333809        -2             NO_EVENT
2025-01-28 05:00:00+00:00  3.732639        -2             NO_EVENT
2025-01-29 05:00:00+00:00  3.413037        -2             NO_EVENT
2025-01-30 05:00:00+00:00  2.511423        -2             NO_EVENT
2025-01-31 05:00:00+00:00  2.638369        -2             NO_EVENT

In [18]:
#work for construct_trades()-pair each entry with the next corresponding exit
import numpy as np
trades=[]
entry_day = None
entry_zscore = None
direction = None
for date,row in position_df.iterrows():
    event=row["event"]
    #ENTRY
    if event=="LONG_ENTRY":
        entry_day=date
        entry_zscore=row["zscore"]
        direction="LONG"
    elif event=="SHORT_ENTRY":
        entry_day=date
        entry_zscore=row["zscore"]
        direction="SHORT"
    #EXIT
    elif event in [
    "LONG_MEAN_EXIT",
    "LONG_STOPLOSS",
    "LONG_MAX_HOLDING",
    "SHORT_MEAN_EXIT",
    "SHORT_STOPLOSS",
    "SHORT_MAX_HOLDING"
]:

        if direction == "LONG" and event.startswith("LONG_"):
            pass

        elif direction == "SHORT" and event.startswith("SHORT_"):
            pass

        else:
            continue

        trade = {
            "trade_id": len(trades) + 1,
            "direction": direction,
            "entry_date": entry_day,
            "exit_date": date,
            "entry_zscore": entry_zscore,
            "exit_zscore": row["zscore"],
            "exit_reason": event,
            "holding_period": (date - entry_day).days
        }

        trades.append(trade)

        entry_day = None
        entry_zscore = None
        direction = None
            
trade_df=pd.DataFrame(trades)
trade_df

,trade_id,direction,entry_date,exit_date,entry_zscore,exit_zscore,exit_reason,holding_period
0,1,LONG,2024-02-29 05:00:00+00:00,2024-03-05 05:00:00+00:00,-0.881727,-2.267345,LONG_STOPLOSS,5
1,2,SHORT,2024-06-13 04:00:00+00:00,2024-09-05 04:00:00+00:00,2.508991,1.990870,SHORT_MAX_HOLDING,84
2,3,SHORT,2024-11-14 05:00:00+00:00,2024-12-09 05:00:00+00:00,2.528190,3.489555,SHORT_STOPLOSS,25

In [19]:
import pandas as pd


def construct_trades(position_df):
    """
    Pair each entry signal with the next corresponding exit signal
    and construct a trade-level DataFrame.

    Holding period is measured in trading days.
    """

    trades = []

    entry_day = None
    entry_zscore = None
    direction = None

    for date, row in position_df.iterrows():

        event = row["event"]

        # ENTRY
        if event == "LONG_ENTRY":

            entry_day = date
            entry_zscore = row["zscore"]
            direction = "LONG"

        elif event == "SHORT_ENTRY":

            entry_day = date
            entry_zscore = row["zscore"]
            direction = "SHORT"

        # EXIT
        elif event in [
            "LONG_MEAN_EXIT",
            "LONG_STOPLOSS",
            "LONG_MAX_HOLDING",
            "SHORT_MEAN_EXIT",
            "SHORT_STOPLOSS",
            "SHORT_MAX_HOLDING"
        ]:

            # Make sure the exit matches the open position
            if direction == "LONG" and event.startswith("LONG_"):
                pass

            elif direction == "SHORT" and event.startswith("SHORT_"):
                pass

            else:
                continue

            # Calculate holding period in trading days
            holding_period = position_df.loc[entry_day:date].shape[0] - 1

            trade = {
                "trade_id": len(trades) + 1,
                "direction": direction,
                "entry_date": entry_day,
                "exit_date": date,
                "entry_zscore": entry_zscore,
                "exit_zscore": row["zscore"],
                "exit_reason": event,
                "holding_period": holding_period
            }

            trades.append(trade)

            # Reset after completing the trade
            entry_day = None
            entry_zscore = None
            direction = None

    trade_df = pd.DataFrame(trades)

    return trade_df
trade_df=construct_trades(position_df)
trade_df

,trade_id,direction,entry_date,exit_date,entry_zscore,exit_zscore,exit_reason,holding_period
0,1,LONG,2024-02-29 05:00:00+00:00,2024-03-05 05:00:00+00:00,-0.881727,-2.267345,LONG_STOPLOSS,3
1,2,SHORT,2024-06-13 04:00:00+00:00,2024-09-05 04:00:00+00:00,2.508991,1.990870,SHORT_MAX_HOLDING,57
2,3,SHORT,2024-11-14 05:00:00+00:00,2024-12-09 05:00:00+00:00,2.528190,3.489555,SHORT_STOPLOSS,16

PL DF 
| Column | Meaning |
|---|---|
| `trade_id` | Trade number |
| `direction` | LONG/SHORT spread |
| `entry_date` | Entry date |
| `exit_date` | Exit date |
| `entry_zscore` | Entry z-score |
| `exit_zscore` | Exit z-score |
| `exit_reason` | Mean exit / stop loss / max holding |
| `holding_period` | Trading days |
concat
| `entry_price_A` | A price at entry |
| `exit_price_A` | A price at exit |
| `entry_price_B` | B price at entry |
| `exit_price_B` | B price at exit |
| `shares_A` | Number of A shares |
| `shares_B` | Number of B shares |
| `pnl_A` | P&L from A leg |
| `pnl_B` | P&L from B leg |
| `total_pnl` | Combined pair P&L |
| `trade_return` | Return from the trade |

In [20]:
from math import floor
initial_capital=100000
pandl_all=[]
for _,row in trade_df.iterrows():
    entry_date=row["entry_date"]
    exit_date=row["exit_date"]
    direction=row["direction"]
    entry_price_A=trading_data.loc[entry_date,"AMD"]
    entry_price_B=trading_data.loc[entry_date,"MSFT"]
    exit_price_A=trading_data.loc[exit_date,"AMD"]
    exit_price_B=trading_data.loc[exit_date,"MSFT"]
    shares_A=floor(initial_capital/(2*entry_price_A))
    shares_B=floor(initial_capital/(2*entry_price_B))
    if direction=="LONG":
        pnl_A=shares_A*(exit_price_A-entry_price_A)
        pnl_B=shares_B*(entry_price_B-exit_price_B)
    elif direction=="SHORT":
        pnl_A=shares_A*(entry_price_A-exit_price_A)
        pnl_B=shares_B*(exit_price_B-entry_price_B)
    total_pnl=pnl_A+pnl_B
    trade_return=total_pnl/initial_capital
    pandl_all.append(
        {
        "entry_price_A":entry_price_A,
        "exit_price_A":exit_price_A,
        "entry_price_B":entry_price_B,
        "exit_price_B":exit_price_B,
        "shares_A":shares_A,
        "shares_B":shares_B,
        "pnl_A":pnl_A,
        "pnl_B":pnl_B,
        "total_pnl":total_pnl,
        "trade_return%":trade_return*100
        }
                     )
pnl_df=pd.DataFrame(pandl_all)
pnl_df=pd.concat([
    trade_df,
    pnl_df
],axis=1)
pnl_df

,trade_id,direction,entry_date,exit_date,entry_zscore,exit_zscore,exit_reason,holding_period,entry_price_A,exit_price_A,entry_price_B,exit_price_B,shares_A,shares_B,pnl_A,pnl_B,total_pnl,trade_return%
0,1,LONG,2024-02-29 05:00:00+00:00,2024-03-05 05:00:00+00:00,-0.881727,-2.267345,LONG_STOPLOSS,3,192.53,205.13,413.64,402.65,259,120,3263.40,1318.80,4582.20,4.58220
1,2,SHORT,2024-06-13 04:00:00+00:00,2024-09-05 04:00:00+00:00,2.508991,1.990870,SHORT_MAX_HOLDING,57,159.90,139.44,441.58,408.39,312,113,6383.52,-3750.47,2633.05,2.63305
2,3,SHORT,2024-11-14 05:00:00+00:00,2024-12-09 05:00:00+00:00,2.528190,3.489555,SHORT_STOPLOSS,16,138.84,130.87,426.89,446.02,360,117,2869.20,2238.21,5107.41,5.10741

In [21]:
stock1="AMD"
stock2="MSFT"

In [22]:
from src.backtest.portfolio import build_equity_curve
portfolio_df = build_equity_curve(
    pnl_df,
    initial_capital=100000
)

portfolio_df

                       date  trade_id  trade_pnl  cumulative_pnl     equity
0 2024-03-05 05:00:00+00:00         1    4582.20         4582.20  104582.20
1 2024-09-05 04:00:00+00:00         2    2633.05         7215.25  107215.25
2 2024-12-09 05:00:00+00:00         3    5107.41        12322.66  112322.66

In [23]:
position_df

                             zscore  position                event
timestamp
2024-01-02 05:00:00+00:00  0.992365         0             NO_EVENT
2024-01-03 05:00:00+00:00  1.206050         0             NO_EVENT
2024-01-04 05:00:00+00:00  1.036833         0             NO_EVENT
2024-01-05 05:00:00+00:00  0.847931         0             NO_EVENT
2024-01-08 05:00:00+00:00  0.628688         0             NO_EVENT
2024-01-09 05:00:00+00:00  0.462826         0             NO_EVENT
2024-01-10 05:00:00+00:00  0.825785         0             NO_EVENT
2024-01-11 05:00:00+00:00  0.944591         0             NO_EVENT
2024-01-12 05:00:00+00:00  1.217545         0             NO_EVENT
2024-01-16 05:00:00+00:00  0.447231         0             NO_EVENT
2024-01-17 05:00:00+00:00  0.311233         0             NO_EVENT
2024-01-18 05:00:00+00:00  0.334143         0             NO_EVENT
2024-01-19 05:00:00+00:00 -0.257636         0             NO_EVENT
2024-01-22 05:00:00+00:00  0.068149         0             NO_EVENT
2024-01-23 05:00:00+00:00  0.158858         0             NO_EVENT
2024-01-24 05:00:00+00:00 -0.366995         0             NO_EVENT
2024-01-25 05:00:00+00:00 -0.405469         0             NO_EVENT
2024-01-26 05:00:00+00:00 -0.231808         0             NO_EVENT
2024-01-29 05:00:00+00:00 -0.011171         0             NO_EVENT
2024-01-30 05:00:00+00:00  0.342481         0             NO_EVENT
2024-01-31 05:00:00+00:00  0.151718         0             NO_EVENT
2024-02-01 05:00:00+00:00  0.235859         0             NO_EVENT
2024-02-02 05:00:00+00:00  0.067631         0             NO_EVENT
2024-02-05 05:00:00+00:00  0.056733         0             NO_EVENT
2024-02-06 05:00:00+00:00  0.496152         0             NO_EVENT
2024-02-07 05:00:00+00:00  0.668081         0             NO_EVENT
2024-02-08 05:00:00+00:00  0.782124         0             NO_EVENT
2024-02-09 05:00:00+00:00  0.852743         0             NO_EVENT
2024-02-12 05:00:00+00:00  0.652172         0             NO_EVENT
2024-02-13 05:00:00+00:00  0.272282         0             NO_EVENT
2024-02-14 05:00:00+00:00 -0.088883         0             NO_EVENT
2024-02-15 05:00:00+00:00 -0.084982         0             NO_EVENT
2024-02-16 05:00:00+00:00  0.005516         0             NO_EVENT
2024-02-20 05:00:00+00:00  0.525598         0             NO_EVENT
2024-02-21 05:00:00+00:00  0.596369         0             NO_EVENT
2024-02-22 05:00:00+00:00 -0.215478         0             NO_EVENT
2024-02-23 05:00:00+00:00  0.102790         0             NO_EVENT
2024-02-26 05:00:00+00:00  0.011279         0             NO_EVENT
2024-02-27 05:00:00+00:00 -0.132416         0             NO_EVENT
2024-02-28 05:00:00+00:00 -0.017908         0             NO_EVENT
2024-02-29 05:00:00+00:00 -0.881727         1           LONG_ENTRY
2024-03-01 05:00:00+00:00 -1.512943         1             NO_EVENT
2024-03-04 05:00:00+00:00 -1.729043         1             NO_EVENT
2024-03-05 05:00:00+00:00 -2.267345         2        LONG_STOPLOSS
2024-03-06 05:00:00+00:00 -2.672390         2             NO_EVENT
2024-03-07 05:00:00+00:00 -2.392503         2             NO_EVENT
2024-03-08 05:00:00+00:00 -2.234451         2             NO_EVENT
2024-03-11 04:00:00+00:00 -1.673087         2             NO_EVENT
2024-03-12 04:00:00+00:00 -1.490658         2             NO_EVENT
2024-03-13 04:00:00+00:00 -0.939304         2             NO_EVENT
2024-03-14 04:00:00+00:00  0.056248         0  LONG_REENTRY_UNLOCK
2024-03-15 04:00:00+00:00 -0.618906         0             NO_EVENT
2024-03-18 04:00:00+00:00 -0.549238         0             NO_EVENT
2024-03-19 04:00:00+00:00  0.280642         0             NO_EVENT
2024-03-20 04:00:00+00:00  0.570681         0             NO_EVENT
2024-03-21 04:00:00+00:00  0.830179         0             NO_EVENT
2024-03-22 04:00:00+00:00  0.733025         0             NO_EVENT
2024-03-25 04:00:00+00:00  0.538784         0             NO_EVENT
2024-03-26 04:00:00+00:00  0.537049         0             NO_EVENT
2024-03-27 04:00:00+00:00  0.406149         0             NO_EVENT
2024-03-28 04:00:00+00:00  0.310706         0             NO_EVENT
2024-04-01 04:00:00+00:00  0.284364         0             NO_EVENT
2024-04-02 04:00:00+00:00  0.468514         0             NO_EVENT
2024-04-03 04:00:00+00:00  0.278028         0             NO_EVENT
2024-04-04 04:00:00+00:00  1.211548         0             NO_EVENT
2024-04-05 04:00:00+00:00  1.232659         0             NO_EVENT
2024-04-08 04:00:00+00:00  1.225253         0             NO_EVENT
2024-04-09 04:00:00+00:00  1.237958         0             NO_EVENT
2024-04-10 04:00:00+00:00  1.355133         0             NO_EVENT
2024-04-11 04:00:00+00:00  1.327908         0             NO_EVENT
2024-04-12 04:00:00+00:00  1.559860         0             NO_EVENT
2024-04-15 04:00:00+00:00  1.391590         0             NO_EVENT
2024-04-16 04:00:00+00:00  1.211605         0             NO_EVENT
2024-04-17 04:00:00+00:00  1.747182         0             NO_EVENT
2024-04-18 04:00:00+00:00  1.328214         0             NO_EVENT
2024-04-19 04:00:00+00:00  1.684211         0             NO_EVENT
2024-04-22 04:00:00+00:00  1.623364         0             NO_EVENT
2024-04-23 04:00:00+00:00  1.663305         0             NO_EVENT
2024-04-24 04:00:00+00:00  1.763259         0             NO_EVENT
2024-04-25 04:00:00+00:00  1.169750         0             NO_EVENT
2024-04-26 04:00:00+00:00  1.240764         0             NO_EVENT
2024-04-29 04:00:00+00:00  0.862047         0             NO_EVENT
2024-04-30 04:00:00+00:00  0.409488         0             NO_EVENT
2024-05-01 04:00:00+00:00  1.642214         0             NO_EVENT
2024-05-02 04:00:00+00:00  1.636939         0             NO_EVENT
2024-05-03 04:00:00+00:00  1.719169         0             NO_EVENT
2024-05-06 04:00:00+00:00  1.662921         0             NO_EVENT
2024-05-07 04:00:00+00:00  1.565468         0             NO_EVENT
2024-05-08 04:00:00+00:00  1.671797         0             NO_EVENT
2024-05-09 04:00:00+00:00  1.832313         0             NO_EVENT
2024-05-10 04:00:00+00:00  1.967592         0             NO_EVENT
2024-05-13 04:00:00+00:00  2.010437         0             NO_EVENT
2024-05-14 04:00:00+00:00  1.951298         0             NO_EVENT
2024-05-15 04:00:00+00:00  1.786765         0             NO_EVENT
2024-05-16 04:00:00+00:00  1.487648         0             NO_EVENT
2024-05-17 04:00:00+00:00  1.323567         0             NO_EVENT
2024-05-20 04:00:00+00:00  1.420202         0             NO_EVENT
2024-05-21 04:00:00+00:00  1.695163         0             NO_EVENT
2024-05-22 04:00:00+00:00  1.697633         0             NO_EVENT
2024-05-23 04:00:00+00:00  1.886836         0             NO_EVENT
2024-05-24 04:00:00+00:00  1.615895         0             NO_EVENT
2024-05-28 04:00:00+00:00  1.261565         0             NO_EVENT
2024-05-29 04:00:00+00:00  1.650181         0             NO_EVENT
2024-05-30 04:00:00+00:00  0.901661         0             NO_EVENT
2024-05-31 04:00:00+00:00  0.910651         0             NO_EVENT
2024-06-03 04:00:00+00:00  1.067262         0             NO_EVENT
2024-06-04 04:00:00+00:00  1.420098         0             NO_EVENT
2024-06-05 04:00:00+00:00  1.344758         0             NO_EVENT
2024-06-06 04:00:00+00:00  1.323397         0             NO_EVENT
2024-06-07 04:00:00+00:00  1.217857         0             NO_EVENT
2024-06-10 04:00:00+00:00  1.903806         0             NO_EVENT
2024-06-11 04:00:00+00:00  2.202471         0             NO_EVENT
2024-06-12 04:00:00+00:00  2.473562         0             NO_EVENT
2024-06-13 04:00:00+00:00  2.508991        -1          SHORT_ENTRY
2024-06-14 04:00:00+00:00  2.559543        -1             NO_EVENT
2024-06-17 04:00:00+00:00  2.881451        -1             NO_EVENT
2024-06-18 04:00:00+00:00  3.030748        -1             NO_EVENT
2024-06-20 04:00:00+00:00  2.510181        -1             NO_EVENT
2024-06-21 04:00:00+00:00  2.710273        -1             NO_EVENT
2024-06-24 04:00:00+00:00  2.672408        -1             NO_EVENT
2024-06-25 04:00:00+00:00  2.798975        -1             NO_EVENT
2024-06-26 04:00:00+00:00  3.013702        -1             NO_EVENT
2024-06-27 04:00:00+00:00  2.899445        -1             NO_EVENT
2024-06-28 04:00:00+00:00  2.459034        -1             NO_EVENT
2024-07-01 04:00:00+00:00  3.150144        -1             NO_EVENT
2024-07-02 04:00:00+00:00  2.809570        -1             NO_EVENT
2024-07-03 04:00:00+00:00  2.883373        -1             NO_EVENT
2024-07-05 04:00:00+00:00  2.635932        -1             NO_EVENT
2024-07-08 04:00:00+00:00  2.136986        -1             NO_EVENT
2024-07-09 04:00:00+00:00  1.957077        -1             NO_EVENT
2024-07-10 04:00:00+00:00  1.790237        -1             NO_EVENT
2024-07-11 04:00:00+00:00  1.442537        -1             NO_EVENT
2024-07-12 04:00:00+00:00  1.414026        -1             NO_EVENT
2024-07-15 04:00:00+00:00  1.541172        -1             NO_EVENT
2024-07-16 04:00:00+00:00  1.501688        -1             NO_EVENT
2024-07-17 04:00:00+00:00  2.401320        -1             NO_EVENT
2024-07-18 04:00:00+00:00  2.495281        -1             NO_EVENT
2024-07-19 04:00:00+00:00  2.616855        -1             NO_EVENT
2024-07-22 04:00:00+00:00  2.571618        -1             NO_EVENT
2024-07-23 04:00:00+00:00  2.754481        -1             NO_EVENT
2024-07-24 04:00:00+00:00  2.685603        -1             NO_EVENT
2024-07-25 04:00:00+00:00  2.645581        -1             NO_EVENT
2024-07-26 04:00:00+00:00  2.804040        -1             NO_EVENT
2024-07-29 04:00:00+00:00  2.862957        -1             NO_EVENT
2024-07-30 04:00:00+00:00  2.778260        -1             NO_EVENT
2024-07-31 04:00:00+00:00  2.215495        -1             NO_EVENT
2024-08-01 04:00:00+00:00  2.888306        -1             NO_EVENT
2024-08-02 04:00:00+00:00  2.538630        -1             NO_EVENT
2024-08-05 04:00:00+00:00  1.867306        -1             NO_EVENT
2024-08-06 04:00:00+00:00  2.317203        -1             NO_EVENT
2024-08-07 04:00:00+00:00  2.354380        -1             NO_EVENT
2024-08-08 04:00:00+00:00  2.050264        -1             NO_EVENT
2024-08-09 04:00:00+00:00  2.296461        -1             NO_EVENT
2024-08-12 04:00:00+00:00  2.169082        -1             NO_EVENT
2024-08-13 04:00:00+00:00  2.178640        -1             NO_EVENT
2024-08-14 04:00:00+00:00  2.304017        -1             NO_EVENT
2024-08-15 04:00:00+00:00  2.062058        -1             NO_EVENT
2024-08-16 04:00:00+00:00  1.886742        -1             NO_EVENT
2024-08-19 04:00:00+00:00  1.599817        -1             NO_EVENT
2024-08-20 04:00:00+00:00  1.655120        -1             NO_EVENT
2024-08-21 04:00:00+00:00  1.542944        -1             NO_EVENT
2024-08-22 04:00:00+00:00  1.574590        -1             NO_EVENT
2024-08-23 04:00:00+00:00  1.424656        -1             NO_EVENT
2024-08-26 04:00:00+00:00  1.591906        -1             NO_EVENT
2024-08-27 04:00:00+00:00  1.572007        -1             NO_EVENT
2024-08-28 04:00:00+00:00  1.690434        -1             NO_EVENT
2024-08-29 04:00:00+00:00  1.833934        -1             NO_EVENT
2024-08-30 04:00:00+00:00  1.801122        -1             NO_EVENT
2024-09-03 04:00:00+00:00  2.189319        -1             NO_EVENT
2024-09-04 04:00:00+00:00  1.931177        -1             NO_EVENT
2024-09-05 04:00:00+00:00  1.990870         0    SHORT_MAX_HOLDING
2024-09-06 04:00:00+00:00  2.031502         0             NO_EVENT
2024-09-09 04:00:00+00:00  1.954962         0             NO_EVENT
2024-09-10 04:00:00+00:00  1.994660         0             NO_EVENT
2024-09-11 04:00:00+00:00  1.911721         0             NO_EVENT
2024-09-12 04:00:00+00:00  2.002289         0             NO_EVENT
2024-09-13 04:00:00+00:00  2.041658         0             NO_EVENT
2024-09-16 04:00:00+00:00  2.077338         0             NO_EVENT
2024-09-17 04:00:00+00:00  2.286355         0             NO_EVENT
2024-09-18 04:00:00+00:00  2.263555         0             NO_EVENT
2024-09-19 04:00:00+00:00  2.061355         0             NO_EVENT
2024-09-20 04:00:00+00:00  1.974387         0             NO_EVENT
2024-09-23 04:00:00+00:00  1.858184         0             NO_EVENT
2024-09-24 04:00:00+00:00  1.603418         0             NO_EVENT
2024-09-25 04:00:00+00:00  1.496701         0             NO_EVENT
2024-09-26 04:00:00+00:00  1.151205         0             NO_EVENT
2024-09-27 04:00:00+00:00  1.208376         0             NO_EVENT
2024-09-30 04:00:00+00:00  1.306292         0             NO_EVENT
2024-10-01 04:00:00+00:00  1.198259         0             NO_EVENT
2024-10-02 04:00:00+00:00  1.063864         0             NO_EVENT
2024-10-03 04:00:00+00:00  0.865221         0             NO_EVENT
2024-10-04 04:00:00+00:00  0.385937         0             NO_EVENT
2024-10-07 04:00:00+00:00  0.141411         0             NO_EVENT
2024-10-08 04:00:00+00:00  0.227109         0             NO_EVENT
2024-10-09 04:00:00+00:00  0.430474         0             NO_EVENT
2024-10-10 04:00:00+00:00  0.762700         0             NO_EVENT
2024-10-11 04:00:00+00:00  0.566963         0             NO_EVENT
2024-10-14 04:00:00+00:00  0.821054         0             NO_EVENT
2024-10-15 04:00:00+00:00  1.300872         0             NO_EVENT
2024-10-16 04:00:00+00:00  1.231562         0             NO_EVENT
2024-10-17 04:00:00+00:00  1.245201         0             NO_EVENT
2024-10-18 04:00:00+00:00  1.312729         0             NO_EVENT
2024-10-21 04:00:00+00:00  1.223101         0             NO_EVENT
2024-10-22 04:00:00+00:00  1.761773         0             NO_EVENT
2024-10-23 04:00:00+00:00  1.718354         0             NO_EVENT
2024-10-24 04:00:00+00:00  1.689290         0             NO_EVENT
2024-10-25 04:00:00+00:00  1.652242         0             NO_EVENT
2024-10-28 04:00:00+00:00  1.381122         0             NO_EVENT
2024-10-29 04:00:00+00:00  1.214685         0             NO_EVENT
2024-10-30 04:00:00+00:00  2.241108         0             NO_EVENT
2024-10-31 04:00:00+00:00  1.533048         0             NO_EVENT
2024-11-01 04:00:00+00:00  1.803228         0             NO_EVENT
2024-11-04 05:00:00+00:00  1.794767         0             NO_EVENT
2024-11-05 05:00:00+00:00  1.846496         0             NO_EVENT
2024-11-06 05:00:00+00:00  1.965363         0             NO_EVENT
2024-11-07 05:00:00+00:00  1.884516         0             NO_EVENT
2024-11-08 05:00:00+00:00  1.880678         0             NO_EVENT
2024-11-11 05:00:00+00:00  1.745611         0             NO_EVENT
2024-11-12 05:00:00+00:00  2.133881         0             NO_EVENT
2024-11-13 05:00:00+00:00  2.450098         0             NO_EVENT
2024-11-14 05:00:00+00:00  2.528190        -1          SHORT_ENTRY
2024-11-15 05:00:00+00:00  2.310856        -1             NO_EVENT
2024-11-18 05:00:00+00:00  2.105572        -1             NO_EVENT
2024-11-19 05:00:00+00:00  2.146919        -1             NO_EVENT
2024-11-20 05:00:00+00:00  2.158021        -1             NO_EVENT
2024-11-21 05:00:00+00:00  2.064241        -1             NO_EVENT
2024-11-22 05:00:00+00:00  2.158414        -1             NO_EVENT
2024-11-25 05:00:00+00:00  2.062068        -1             NO_EVENT
2024-11-26 05:00:00+00:00  2.572231        -1             NO_EVENT
2024-11-27 05:00:00+00:00  2.466537        -1             NO_EVENT
2024-11-29 05:00:00+00:00  2.422911        -1             NO_EVENT
2024-12-02 05:00:00+00:00  2.411973        -1             NO_EVENT
2024-12-03 05:00:00+00:00  2.415775        -1             NO_EVENT
2024-12-04 05:00:00+00:00  2.516162        -1             NO_EVENT
2024-12-05 05:00:00+00:00  2.832078        -1             NO_EVENT
2024-12-06 05:00:00+00:00  3.002574        -1             NO_EVENT
2024-12-09 05:00:00+00:00  3.489555        -2       SHORT_STOPLOSS
2024-12-10 05:00:00+00:00  3.541650        -2             NO_EVENT
2024-12-11 05:00:00+00:00  3.583451        -2             NO_EVENT
2024-12-12 05:00:00+00:00  3.554248        -2             NO_EVENT
2024-12-13 05:00:00+00:00  3.647016        -2             NO_EVENT
2024-12-16 05:00:00+00:00  3.778358        -2             NO_EVENT
2024-12-17 05:00:00+00:00  3.932869        -2             NO_EVENT
2024-12-18 05:00:00+00:00  3.519209        -2             NO_EVENT
2024-12-19 05:00:00+00:00  3.613994        -2             NO_EVENT
2024-12-20 05:00:00+00:00  3.557735        -2             NO_EVENT
2024-12-23 05:00:00+00:00  3.215476        -2             NO_EVENT
2024-12-24 05:00:00+00:00  3.244701        -2             NO_EVENT
2024-12-26 05:00:00+00:00  3.248548        -2             NO_EVENT
2024-12-27 05:00:00+00:00  2.978961        -2             NO_EVENT
2024-12-30 05:00:00+00:00  2.918547        -2             NO_EVENT
2024-12-31 05:00:00+00:00  2.880271        -2             NO_EVENT
2025-01-02 05:00:00+00:00  2.781826        -2             NO_EVENT
2025-01-03 05:00:00+00:00  2.687294        -2             NO_EVENT
2025-01-06 05:00:00+00:00  2.613139        -2             NO_EVENT
2025-01-07 05:00:00+00:00  2.538887        -2             NO_EVENT
2025-01-08 05:00:00+00:00  2.867391        -2             NO_EVENT
2025-01-10 05:00:00+00:00  2.961217        -2             NO_EVENT
2025-01-13 05:00:00+00:00  2.829721        -2             NO_EVENT
2025-01-14 05:00:00+00:00  2.829389        -2             NO_EVENT
2025-01-15 05:00:00+00:00  2.960582        -2             NO_EVENT
2025-01-16 05:00:00+00:00  2.965962        -2             NO_EVENT
2025-01-17 05:00:00+00:00  2.944236        -2             NO_EVENT
2025-01-21 05:00:00+00:00  2.874889        -2             NO_EVENT
2025-01-22 05:00:00+00:00  3.333625        -2             NO_EVENT
2025-01-23 05:00:00+00:00  3.363060        -2             NO_EVENT
2025-01-24 05:00:00+00:00  3.272016        -2             NO_EVENT
2025-01-27 05:00:00+00:00  3.333809        -2             NO_EVENT
2025-01-28 05:00:00+00:00  3.732639        -2             NO_EVENT
2025-01-29 05:00:00+00:00  3.413037        -2             NO_EVENT
2025-01-30 05:00:00+00:00  2.511423        -2             NO_EVENT
2025-01-31 05:00:00+00:00  2.638369        -2             NO_EVENT

In [24]:
equity_curve=[]
for date,rows in position_df.iterrows():
    position=position_df["position"]
    if position==1:
        pass
    elif position==-1:
        pass
    elif position in [0,-2,2]:
        continue
    priceA=trading_data.loc[date,stock1]
    priceB=trading_data.loc[date,stock2]
    daily_pnl=

SyntaxError: invalid syntax (2572151614.py, line 12)

In [ ]:
trading_data

symbol,AAPL,ADBE,AMAT,AMD,AMZN,AVGO,CRM,CSCO,GOOGL,IBM,INTC,META,MSFT,MU,NFLX,NOW,NVDA,ORCL,QCOM,TXN
timestamp,,,,,,,,,,,,,,,,,,,,
2024-01-02 05:00:00+00:00,185.64,580.07,154.370,138.580,149.930,1085.380,256.13,50.51,138.170,161.50,47.80,346.290,370.87,82.340,468.50,687.52,481.680,104.06,140.23,169.260
2024-01-03 05:00:00+00:00,184.25,571.79,151.450,135.320,148.470,1058.580,251.84,50.51,138.920,160.10,47.05,344.470,370.60,82.260,470.26,675.30,475.690,102.46,137.60,166.740
2024-01-04 05:00:00+00:00,181.91,567.05,149.310,136.010,144.570,1049.010,251.24,50.08,136.390,160.86,46.87,347.120,367.94,82.710,474.67,671.87,479.980,102.59,136.17,164.465
2024-01-05 05:00:00+00:00,181.18,564.60,149.000,138.580,145.240,1049.280,251.12,50.09,135.730,159.16,46.89,351.950,367.75,83.450,474.06,676.16,490.970,102.73,136.73,165.100
2024-01-08 05:00:00+00:00,185.56,580.55,151.560,146.180,149.100,1074.850,260.87,50.46,138.840,161.14,48.45,358.660,374.69,84.950,485.03,696.26,522.530,104.66,139.03,168.540
2024-01-09 05:00:00+00:00,185.14,586.20,151.030,149.260,151.370,1082.490,261.34,49.91,140.950,160.08,48.05,357.430,375.79,83.330,482.09,698.67,531.400,103.63,139.89,168.630
2024-01-10 05:00:00+00:00,186.19,591.03,149.810,148.540,153.730,1080.570,264.13,50.24,142.280,161.23,47.47,370.470,382.77,82.380,478.33,714.30,543.500,103.92,139.31,167.250
2024-01-11 05:00:00+00:00,185.59,597.49,151.950,148.020,155.180,1099.980,271.38,50.44,142.080,162.16,47.64,369.670,384.63,83.390,492.23,726.46,548.220,104.77,139.03,165.600
2024-01-12 05:00:00+00:00,185.92,596.54,151.250,146.560,154.620,1107.680,271.93,50.34,142.650,165.80,47.12,374.490,388.47,82.390,492.16,729.18,547.100,106.60,140.20,164.870
2024-01-16 05:00:00+00:00,183.63,597.68,153.760,158.740,153.160,1114.960,269.19,50.59,142.490,166.96,47.06,367.460,390.27,84.610,481.24,727.56,563.820,106.57,141.12,163.880
2024-01-17 05:00:00+00:00,182.68,596.10,153.370,160.170,151.710,1103.670,271.44,50.30,141.470,166.08,46.06,368.370,389.47,83.280,480.33,727.54,560.530,106.43,139.32,162.415
2024-01-18 05:00:00+00:00,188.63,593.70,160.340,162.670,153.500,1143.910,274.46,50.75,143.480,166.84,46.74,376.130,393.87,84.820,485.31,745.96,571.070,108.70,145.29,166.910
2024-01-19 05:00:00+00:00,191.56,611.55,167.940,174.230,155.340,1211.200,280.88,51.27,146.380,171.48,48.15,383.450,398.67,87.510,482.95,749.11,594.910,109.67,151.96,173.650
2024-01-22 05:00:00+00:00,193.89,603.59,168.300,168.180,154.780,1220.500,280.30,51.57,145.990,172.83,48.22,381.780,396.51,89.240,485.71,752.45,596.540,110.10,152.87,174.830
2024-01-23 05:00:00+00:00,195.18,597.18,167.050,168.420,156.020,1226.310,276.77,51.76,147.040,173.94,48.89,385.200,398.90,87.530,492.19,753.42,598.730,111.83,153.50,174.340
2024-01-24 05:00:00+00:00,194.50,606.48,174.140,178.290,156.870,1253.870,276.88,51.31,148.700,173.93,49.09,390.700,402.56,88.080,544.87,763.42,613.620,114.31,154.37,170.070
2024-01-25 05:00:00+00:00,194.17,622.58,172.630,180.330,157.750,1230.000,279.03,52.33,151.870,190.43,49.55,393.180,404.87,89.200,562.00,766.69,616.170,115.00,154.47,167.420
2024-01-26 05:00:00+00:00,192.42,613.93,166.900,177.250,159.120,1204.880,279.94,52.14,152.185,187.42,43.65,394.140,403.93,88.050,570.42,769.44,610.310,114.64,150.72,164.090
2024-01-29 05:00:00+00:00,191.73,630.23,168.480,177.830,161.260,1217.770,287.86,52.29,153.510,187.14,43.84,401.020,409.72,89.070,575.79,787.24,624.650,113.75,149.64,166.040
2024-01-30 05:00:00+00:00,188.04,627.96,166.240,172.060,159.000,1208.160,287.73,52.24,151.460,187.87,42.92,400.060,408.59,86.160,562.85,785.73,627.740,114.16,145.98,162.050
2024-01-31 05:00:00+00:00,184.40,617.78,164.300,167.690,155.200,1180.000,281.09,50.18,140.100,183.66,43.08,390.140,397.58,85.750,564.11,765.40,615.270,111.70,148.51,160.120
2024-02-01 05:00:00+00:00,186.86,627.91,166.970,170.480,159.280,1200.010,283.80,50.18,141.160,186.90,43.36,394.780,403.78,85.610,567.51,771.00,630.270,115.53,141.11,159.690
2024-02-02 05:00:00+00:00,185.85,634.76,168.180,177.660,171.810,1224.340,285.66,50.18,142.380,185.79,42.60,474.990,411.22,86.480,564.64,781.30,661.600,115.79,141.69,159.200
2024-02-05 05:00:00+00:00,187.68,630.50,171.090,174.230,170.310,1243.100,288.11,49.51,143.680,183.42,42.77,459.410,405.65,86.980,562.06,784.84,693.320,116.39,144.03,158.900
2024-02-06 05:00:00+00:00,189.30,607.14,168.700,167.880,169.150,1222.650,285.83,49.98,144.100,183.41,42.74,454.720,405.49,84.600,555.88,777.45,682.230,115.30,144.10,158.370
2024-02-07 05:00:00+00:00,189.41,615.85,170.900,170.940,170.530,1257.060,288.84,49.77,145.540,183.74,42.78,469.590,414.05,85.170,559.30,790.39,700.990,117.27,145.89,158.770
2024-02-08 05:00:00+00:00,188.32,615.86,173.890,169.350,169.840,1274.760,291.95,49.95,145.910,184.36,42.50,470.000,414.11,84.880,558.53,799.41,696.410,116.68,148.18,160.210
2024-02-09 05:00:00+00:00,188.85,627.21,185.840,172.480,174.450,1283.440,291.30,50.13,149.000,186.34,43.31,468.110,420.55,85.560,561.32,812.94,721.330,116.64,151.00,162.400
2024-02-12 05:00:00+00:00,187.15,611.84,185.540,171.910,172.340,1265.000,287.32,49.99,147.530,186.16,44.03,468.900,415.26,85.700,557.85,787.35,722.480,115.84,153.10,161.080
2024-02-13 05:00:00+00:00,185.04,601.89,180.310,171.540,168.640,1251.650,281.15,49.64,145.140,183.70,43.16,460.120,406.32,81.530,554.52,773.76,721.280,113.68,150.04,156.850
2024-02-14 05:00:00+00:00,184.15,604.66,186.190,178.700,170.980,1262.220,289.15,50.28,145.940,183.57,44.19,473.280,409.49,81.830,579.33,792.00,739.000,114.26,153.94,157.870
2024-02-15 05:00:00+00:00,183.86,590.44,187.660,176.760,169.800,1265.070,291.94,49.06,142.770,186.87,44.05,484.030,406.56,81.630,593.46,780.00,726.580,112.78,155.98,160.710
2024-02-16 05:00:00+00:00,182.31,546.66,199.570,173.870,169.510,1245.480,289.72,48.44,140.520,187.64,43.51,473.320,404.06,79.500,583.95,765.00,726.130,111.31,152.69,160.380
2024-02-20 05:00:00+00:00,181.56,541.91,189.140,165.690,167.080,1226.550,286.39,48.28,141.120,183.44,44.52,471.750,402.79,80.710,575.13,752.84,694.520,108.45,151.96,162.740
2024-02-21 05:00:00+00:00,182.32,538.52,190.330,164.290,168.590,1227.450,283.55,48.48,142.550,179.70,43.47,468.030,402.18,81.490,573.35,747.94,674.720,108.16,152.01,164.080
2024-02-22 05:00:00+00:00,184.37,537.57,199.730,181.860,174.580,1304.900,293.65,48.57,144.090,184.21,42.98,486.130,411.65,85.910,588.47,769.21,785.380,111.01,154.75,165.430
2024-02-23 05:00:00+00:00,182.52,553.44,197.160,176.520,174.990,1296.370,292.80,48.86,143.960,185.72,42.99,484.030,410.34,86.000,583.56,770.97,788.170,111.95,154.91,163.690
2024-02-26 05:00:00+00:00,181.16,560.48,203.550,176.010,174.730,1309.130,300.39,48.40,137.570,184.13,42.99,481.740,407.54,89.460,587.65,779.66,790.920,110.97,157.03,164.300
2024-02-27 05:00:00+00:00,182.63,552.49,202.860,178.000,173.540,1296.230,299.50,48.31,138.880,184.87,42.73,487.050,407.48,91.850,601.67,767.14,787.010,111.38,158.30,164.940
2024-02-28 05:00:00+00:00,181.42,551.82,197.540,176.540,173.160,1289.420,299.77,48.06,136.380,185.30,41.99,484.020,407.72,89.710,596.48,759.79,776.630,111.68,155.85,163.040
2024-02-29 05:00:00+00:00,180.75,560.28,201.620,192.530,176.760,1300.490,308.82,48.37,138.460,185.03,43.05,490.130,413.64,90.610,602.92,771.34,791.120,111.68,157.79,167.330
2024-03-01 05:00:00+00:00,179.66,570.93,210.250,202.640,178.220,1399.170,316.88,48.40,137.140,188.20,43.82,502.300,415.50,95.150,619.34,773.63,822.790,113.78,163.09,171.050
2024-03-04 05:00:00+00:00,175.10,567.94,209.490,205.360,177.580,1402.260,314.64,49.13,133.350,193.06,45.61,498.190,414.92,95.770,615.83,776.09,852.370,114.06,166.56,172.440
2024-03-05 05:00:00+00:00,170.12,544.84,207.390,205.130,174.120,1342.750,298.75,48.95,132.670,191.95,43.16,490.220,402.65,94.470,598.50,740.15,859.640,110.94,161.45,170.640
2024-03-06 05:00:00+00:00,169.12,543.09,212.170,210.630,173.510,1350.000,303.77,49.17,131.400,196.16,44.51,496.090,402.09,95.560,597.69,741.06,887.000,112.27,167.89,171.870
2024-03-07 05:00:00+00:00,169.00,556.04,212.610,211.380,176.820,1407.010,302.42,48.90,134.380,196.54,46.15,512.190,409.14,98.980,608.51,768.08,926.690,114.54,175.72,175.270
2024-03-08 05:00:00+00:00,170.73,551.69,205.560,207.390,175.350,1308.720,305.28,49.50,135.410,195.95,44.00,505.950,406.22,97.620,604.82,757.68,875.280,112.42,170.57,172.300
2024-03-11 04:00:00+00:00,172.75,560.42,201.370,198.390,171.960,1293.120,306.00,50.22,137.670,191.73,44.86,483.590,404.52,94.510,600.93,756.74,857.740,114.13,171.12,174.190
2024-03-12 04:00:00+00:00,173.23,579.14,204.940,202.760,175.390,1291.880,306.62,50.07,138.500,197.78,45.24,499.750,415.28,97.420,611.08,789.56,919.130,127.54,173.08,174.800
2024-03-13 04:00:00+00:00,171.13,573.55,200.560,194.790,176.555,1257.870,304.68,50.11,139.790,196.70,43.23,495.570,415.10,94.160,609.45,776.88,908.880,125.52,169.25,172.680
2024-03-14 04:00:00+00:00,173.00,570.45,200.750,187.060,178.750,1262.270,303.32,49.79,143.100,193.43,42.75,491.830,425.22,91.430,613.01,779.49,879.440,125.53,168.45,171.140
2024-03-15 04:00:00+00:00,172.62,492.46,198.650,191.060,174.420,1235.500,294.33,48.93,141.180,191.07,42.64,484.100,416.42,93.250,605.88,743.91,878.365,125.54,167.20,172.520
2024-03-18 04:00:00+00:00,173.72,513.86,200.730,190.650,174.480,1237.240,300.51,49.27,147.680,191.69,42.71,496.980,417.32,93.780,618.39,755.80,884.550,127.80,166.92,169.210
2024-03-19 04:00:00+00:00,176.08,521.19,201.340,181.420,175.900,1238.010,301.45,49.14,147.030,193.34,42.05,496.240,421.41,94.000,620.74,756.94,893.980,129.19,164.10,166.760
2024-03-20 04:00:00+00:00,178.67,519.14,205.060,179.730,178.150,1276.000,306.08,49.55,148.740,193.96,42.20,505.520,425.23,96.250,627.69,767.56,903.720,129.24,167.67,169.980
2024-03-21 04:00:00+00:00,171.37,511.25,210.800,178.680,178.150,1348.000,308.39,49.88,147.600,191.90,42.42,507.760,429.37,109.850,622.71,773.18,914.350,129.01,170.85,172.590
2024-03-22 04:00:00+00:00,172.28,499.52,210.250,179.650,178.870,1353.470,307.77,49.78,150.770,190.84,42.57,509.580,428.74,110.210,628.01,774.15,942.890,127.79,170.10,172.480
2024-03-25 04:00:00+00:00,170.85,507.23,208.460,178.630,179.710,1351.580,306.06,49.68,150.070,188.79,41.83,503.020,422.86,117.130,627.46,774.64,950.020,126.08,167.52,170.850
2024-03-26 04:00:00+00:00,169.71,507.60,206.670,177.870,178.300,1331.490,305.83,49.55,150.670,188.50,41.99,495.890,421.65,118.800,629.24,778.57,925.610,126.47,167.07,167.910
2024-03-27 04:00:00+00:00,173.31,504.40,208.000,179.590,179.830,1318.730,301.38,49.77,150.870,190.80,43.77,493.860,421.43,119.250,613.53,759.00,902.500,125.27,169.13,172.870
2024-03-28 04:00:00+00:00,171.48,504.60,206.230,180.490,180.380,1325.410,301.18,49.91,150.930,190.96,44.17,485.580,420.72,117.890,607.33,762.40,903.560,125.61,169.30,174.210
2024-04-01 04:00:00+00:00,170.03,502.09,208.690,183.340,180.970,1350.260,302.26,50.04,155.490,189.83,44.52,491.350,424.57,124.300,614.31,768.37,903.630,125.48,171.72,173.170
2024-04-02 04:00:00+00:00,168.84,499.21,206.110,178.700,180.690,1338.760,304.00,49.36,154.560,188.88,43.94,497.370,421.44,122.750,614.21,757.00,894.520,124.34,171.04,170.360
2024-04-03 04:00:00+00:00,169.65,497.01,207.380,180.770,182.410,1363.210,304.74,48.74,154.920,190.90,40.33,506.740,420.45,128.010,630.08,759.16,889.640,126.24,173.91,170.340
2024-04-04 04:00:00+00:00,168.82,487.11,203.390,165.830,180.000,1317.500,294.14,48.11,150.530,187.94,39.73,510.920,417.88,124.090,617.14,757.55,859.050,124.19,169.76,168.530
2024-04-05 04:00:00+00:00,169.58,485.12,207.850,170.420,185.070,1339.430,301.91,48.55,152.500,189.14,38.71,527.340,425.52,123.580,636.18,783.50,880.080,124.90,171.53,167.500
2024-04-08 04:00:00+00:00,168.45,484.28,209.040,169.900,185.190,1336.100,301.73,48.24,154.850,189.82,37.98,519.250,424.59,122.950,628.41,785.60,871.330,124.35,173.62,169.460
2024-04-09 04:00:00+00:00,169.67,492.55,210.410,170.780,185.670,1334.080,302.37,50.01,156.600,189.31,38.33,516.900,426.28,122.630,618.20,782.22,853.540,123.23,175.57,173.460
2024-04-10 04:00:00+00:00,167.78,487.22,209.250,167.140,185.950,1322.370,299.62,49.21,156.140,186.04,37.20,519.830,423.26,122.200,618.58,769.19,870.390,121.75,170.86,168.920
2024-04-11 04:00:00+00:00,175.04,484.28,212.980,170.500,189.050,1382.460,299.15,49.53,159.410,185.90,37.63,523.160,427.93,127.510,628.78,771.34,906.160,123.24,175.13,171.200
2024-04-12 04:00:00+00:00,176.55,474.09,207.860,163.280,186.130,1344.070,294.32,48.49,157.730,182.27,35.69,511.900,421.90,122.520,622.83,768.71,881.860,121.11,171.29,166.330
2024-04-15 04:00:00+00:00,172.69,470.10,205.680,160.320,183.620,1310.690,272.90,48.24,154.860,181.25,36.31,500.230,413.64,121.370,607.15,735.81,860.010,119.88,169.84,166.350
2024-04-16 04:00:00+00:00,169.38,476.22,209.480,163.460,183.320,1329.060,277.41,47.92,154.400,183.75,36.26,499.760,414.58,121.770,617.52,744.78,874.150,120.62,168.58,167.590
2024-04-17 04:00:00+00:00,168.00,474.45,199.890,154.020,181.280,1282.630,276.32,47.79,155.470,183.10,35.68,494.170,411.84,116.330,613.69,736.45,840.350,118.67,164.32,165.700
2024-04-18 04:00:00+00:00,167.04,473.18,194.320,155.080,179.220,1258.990,271.92,48.11,156.010,181.47,35.04,501.800,404.27,111.930,610.56,731.36,846.710,116.00,161.44,163.670
2024-04-19 04:00:00+00:00,165.00,465.02,189.770,146.640,174.630,1204.710,270.37,48.32,154.090,181.58,34.20,481.070,399.12,106.770,555.04,713.91,762.000,114.88,157.63,159.680
2024-04-22 04:00:00+00:00,165.84,466.89,189.460,148.640,177.230,1224.460,273.81,48.14,156.280,181.90,34.41,481.730,400.96,109.120,554.60,721.95,795.180,114.53,160.18,163.430
2024-04-23 04:00:00+00:00,166.90,472.90,193.240,152.270,179.540,1249.190,276.68,48.32,158.260,182.19,34.28,496.100,407.57,112.460,577.75,740.95,824.230,115.09,161.35,165.470
2024-04-24 04:00:00+00:00,169.02,477.12,196.060,151.740,176.590,1256.820,276.19,48.35,159.130,184.10,34.50,493.500,409.06,111.780,555.12,746.29,796.770,115.34,163.63,174.810
2024-04-25 04:00:00+00:00,169.89,473.44,197.500,153.760,173.670,1294.420,273.14,48.10,156.000,168.91,35.11,441.380,399.04,111.580,564.80,716.25,826.320,114.89,163.30,175.250
2024-04-26 04:00:00+00:00,169.30,477.56,203.380,157.400,179.620,1344.070,274.29,47.86,171.950,167.13,31.88,443.290,406.32,114.840,561.23,723.55,877.350,117.21,165.66,177.480
2024-04-29 04:00:00+00:00,173.50,473.07,205.260,160.200,180.960,1338.620,275.74,47.78,166.150,167.43,31.36,432.620,402.25,114.360,559.49,721.16,877.570,116.49,169.20,179.290
2024-04-30 04:00:00+00:00,170.33,462.83,198.650,158.380,175.000,1300.270,268.94,46.98,162.780,166.20,30.47,430.170,389.33,112.960,550.64,693.33,864.020,113.75,165.85,176.420
2024-05-01 04:00:00+00:00,169.30,469.39,193.990,144.270,179.000,1242.860,268.69,46.84,163.860,164.43,30.37,439.190,394.94,109.700,551.71,685.61,830.410,114.63,164.11,175.200
2024-05-02 04:00:00+00:00,173.03,476.57,197.910,146.160,184.720,1238.570,272.13,46.79,166.620,164.69,30.51,441.680,397.84,112.330,565.15,695.72,858.170,114.96,180.10,175.800
2024-05-03 04:00:00+00:00,183.38,486.18,204.090,150.600,186.210,1278.110,273.66,47.12,167.240,165.71,30.90,451.960,406.66,114.700,579.34,716.65,887.890,115.80,179.64,178.910
2024-05-06 04:00:00+00:00,181.71,493.59,208.860,155.780,188.700,1310.310,275.63,47.11,168.100,168.61,30.97,465.680,413.54,120.130,596.97,726.56,921.400,118.34,181.85,181.670
2024-05-07 04:00:00+00:00,182.40,492.27,207.320,154.430,188.760,1303.110,277.18,47.28,171.250,168.38,30.68,468.240,409.34,119.210,606.00,713.33,905.540,117.93,180.15,182.670
2024-05-08 04:00:00+00:00,182.74,488.10,207.360,153.620,188.000,1325.370,278.97,48.00,169.380,169.90,30.00,472.600,410.54,119.320,609.47,721.03,904.120,117.39,180.55,183.950
2024-05-09 04:00:00+00:00,184.57,482.65,206.330,152.390,189.500,1305.670,275.17,47.79,169.960,166.27,30.09,475.420,412.32,117.810,612.09,722.94,887.470,116.64,180.54,185.320
2024-05-10 04:00:00+00:00,183.05,482.29,209.730,151.920,187.480,1332.800,276.67,48.06,168.650,167.15,29.85,476.200,414.74,121.240,610.87,729.79,898.780,116.67,182.08,187.050
2024-05-13 04:00:00+00:00,186.28,483.11,206.630,150.560,186.570,1337.510,277.52,48.68,169.140,167.56,30.51,468.010,413.72,123.000,616.59,730.12,903.990,116.37,184.21,187.820
2024-05-14 04:00:00+00:00,187.43,475.95,209.820,153.160,187.070,1380.030,276.80,48.95,170.340,167.36,31.05,471.850,416.56,124.810,613.66,721.62,913.560,120.87,188.97,191.130
2024-05-15 04:00:00+00:00,189.72,485.35,217.490,159.670,185.990,1436.170,287.54,49.67,172.510,168.26,31.27,481.540,423.08,127.810,613.52,760.57,946.300,121.63,194.61,195.530
2024-05-16 04:00:00+00:00,189.84,482.88,214.030,162.620,183.630,1412.130,284.68,48.34,174.180,168.97,32.03,473.230,420.99,127.890,610.52,758.01,943.590,122.16,193.27,194.970
2024-05-17 04:00:00+00:00,189.87,483.43,212.080,164.470,184.700,1395.290,285.61,48.17,176.060,169.03,31.83,471.910,420.21,125.290,621.10,765.05,924.790,123.50,193.86,195.020
2024-05-20 04:00:00+00:00,191.04,484.69,219.950,166.330,183.540,1414.030,287.07,47.13,176.920,169.92,32.10,468.840,425.34,129.000,640.82,774.18,947.800,124.52,197.76,199.200
2024-05-21 04:00:00+00:00,192.35,481.85,219.800,164.660,183.150,1399.200,283.76,46.94,177.850,173.47,31.74,464.630,429.04,127.500,650.61,777.05,953.860,124.63,200.85,199.010
2024-05-22 04:00:00+00:00,190.90,483.93,218.150,165.520,183.130,1392.240,283.82,47.43,176.380,173.69,31.42,467.780,430.52,126.280,640.47,770.83,949.500,124.60,202.93,202.540
2024-05-23 04:00:00+00:00,186.88,483.31,217.950,160.430,181.050,1393.290,278.57,46.60,173.550,170.67,30.08,465.780,427.00,126.270,635.67,758.15,1037.990,124.09,201.76,197.290
2024-05-24 04:00:00+00:00,189.98,475.43,220.890,166.360,180.750,1407.840,272.29,46.42,174.990,170.89,30.72,478.220,430.16,129.490,646.75,738.51,1064.690,122.91,210.36,199.180
2024-05-28 04:00:00+00:00,189.99,478.43,221.320,171.610,182.150,1412.450,269.83,46.28,176.400,169.66,31.06,479.920,430.32,132.670,649.00,728.86,1139.010,124.49,213.08,199.600
2024-05-29 04:00:00+00:00,190.29,477.60,219.050,165.140,182.020,1390.670,271.62,46.08,175.900,167.05,30.13,474.360,429.17,131.580,654.62,731.12,1148.250,123.74,208.26,194.910
2024-05-30 04:00:00+00:00,191.29,445.87,216.540,166.750,179.320,1364.080,218.01,46.12,172.110,165.63,30.19,467.050,414.67,126.290,647.66,643.29,1105.000,117.09,204.80,195.680
2024-05-31 04:00:00+00:00,192.25,444.76,215.080,166.900,176.440,1328.550,234.44,46.50,172.500,166.85,30.85,466.830,415.13,125.000,641.62,656.93,1096.330,117.19,204.05,195.010
2024-06-03 04:00:00+00:00,194.03,439.02,214.210,163.550,178.340,1321.900,236.62,46.65,173.170,165.28,30.29,477.490,413.52,128.170,633.79,660.11,1150.000,119.28,205.91,193.720
2024-06-04 04:00:00+00:00,194.35,448.37,212.220,159.990,179.340,1330.820,234.86,47.42,173.790,165.81,30.03,476.990,416.07,126.640,631.62,672.00,1164.370,120.07,204.37,193.300
2024-06-05 04:00:00+00:00,195.87,455.80,223.370,166.170,181.280,1413.090,236.53,46.02,175.410,167.38,30.78,495.060,424.01,133.710,650.27,704.11,1224.400,122.63,211.90,196.080
2024-06-06 04:00:00+00:00,194.48,458.13,221.750,166.780,185.000,1401.270,242.76,46.23,176.730,168.20,30.42,493.760,424.52,130.070,648.52,703.16,1209.980,123.50,209.44,196.240
2024-06-07 04:00:00+00:00,196.89,465.43,221.730,167.870,184.300,1406.640,241.85,45.84,174.460,170.01,30.74,492.960,423.85,130.940,641.47,698.81,1208.880,125.92,206.62,195.610
2024-06-10 04:00:00+00:00,193.12,459.94,228.160,160.340,187.060,1440.470,241.84,45.85,175.010,170.38,30.91,502.600,427.87,134.820,644.50,709.15,121.790,124.50,209.35,197.620
2024-06-11 04:00:00+00:00,207.15,462.69,229.970,158.960,187.230,1461.030,240.99,45.77,176.620,169.32,30.92,507.470,432.68,135.070,648.55,712.04,120.910,123.88,208.52,197.440
2024-06-12 04:00:00+00:00,213.07,459.87,237.650,160.240,186.890,1495.510,235.80,45.62,177.790,169.00,30.76,508.840,441.06,140.750,650.06,721.50,125.200,140.38,215.39,198.980
2024-06-13 04:00:00+00:00,214.24,458.74,237.550,159.900,183.830,1678.990,229.03,45.52,175.160,169.12,30.46,504.100,441.58,143.140,653.26,709.76,129.610,139.85,217.81,196.280

In [ ]:
from src.backtest.portfolio import build_daily_equity_curve
equity_curve=build_daily_equity_curve(pnl_df,trading_data,initial_capital,stock1,stock2)
equity_curve

KeyError: "['date'] not in index"

In [25]:
import inspect
from src.backtest.portfolio import build_daily_equity_curve

print(inspect.getsource(build_daily_equity_curve))

def build_daily_equity_curve(
    pnl_df,
    trading_data,
    initial_capital,
    ticker_A,
    ticker_B,
):
    daily_data = trading_data[[ticker_A, ticker_B]].copy()
    daily_data["daily_pnl"] = 0.0

    for _, trade in pnl_df.iterrows():
        entry_date = trade["entry_date"]
        exit_date = trade["exit_date"]

        shares_A = trade["shares_A"]
        shares_B = trade["shares_B"]

        # Price movement starts after entry and ends on the exit date.
        trade_days = daily_data.loc[entry_date:exit_date].copy()
        price_change_A = trade_days[ticker_A].diff()
        price_change_B = trade_days[ticker_B].diff()

        if trade["direction"] == "LONG":
            # Long AMD, short MSFT
            trade_pnl = (
                shares_A * price_change_A
                - shares_B * price_change_B
            )

        else:
            # Short AMD, long MSFT
            trade_pnl = (
                -shares_A * price_change_A
                + shares_B * price_change_B
            )

        daily_data.loc[trade_days.index, "daily_pnl"] += (
            trade_pnl.fillna(0)
        )

    daily_data["equity"] = (
        initial_capital + daily_data["daily_pnl"].cumsum()
    )

    daily_data["daily_return"] = (
        daily_data["daily_pnl"]
        / daily_data["equity"].shift(1)
    )

    # Ensure the output has a consistent date column even when the input
    # price index is unnamed or is named something other than "date".
    daily_data.index.name = "date"
    equity_curve_df = daily_data.reset_index()

    equity_curve_df = equity_curve_df.rename(
        columns={"index": "date"}
    )

    equity_curve_df = equity_curve_df[
        ["date", "daily_pnl", "equity", "daily_return"]
    ]

    return equity_curve_df

In [26]:
print(trading_data.index.name)
print(trading_data.index)

timestamp
DatetimeIndex(['2024-01-02 05:00:00+00:00', '2024-01-03 05:00:00+00:00',
               '2024-01-04 05:00:00+00:00', '2024-01-05 05:00:00+00:00',
               '2024-01-08 05:00:00+00:00', '2024-01-09 05:00:00+00:00',
               '2024-01-10 05:00:00+00:00', '2024-01-11 05:00:00+00:00',
               '2024-01-12 05:00:00+00:00', '2024-01-16 05:00:00+00:00',
               ...
               '2025-01-17 05:00:00+00:00', '2025-01-21 05:00:00+00:00',
               '2025-01-22 05:00:00+00:00', '2025-01-23 05:00:00+00:00',
               '2025-01-24 05:00:00+00:00', '2025-01-27 05:00:00+00:00',
               '2025-01-28 05:00:00+00:00', '2025-01-29 05:00:00+00:00',
               '2025-01-30 05:00:00+00:00', '2025-01-31 05:00:00+00:00'],
              dtype='datetime64[us, UTC]', name='timestamp', length=272, freq=None)