In [45]:
import sys
import os

sys.path.append(os.path.abspath(".."))

In [46]:
from src.data.alpaca_data import get_stock_bars
tickers = [
    "AAPL", "ADBE", "AMAT", "AMD", "AMZN",
    "AVGO", "CRM", "CSCO", "GOOGL", "IBM",
    "INTC", "META", "MSFT", "MU", "NFLX",
    "NOW", "NVDA", "ORCL", "QCOM", "TXN"
]
bars = get_stock_bars(tickers,"2021-01-01","2025-02-01")

In [47]:
from src.data.preprocessing import prepare_price_data,split_data
prices = prepare_price_data(bars)
formation_data,trading_data=split_data(prices,"2023-12-29")
formation_data

symbol,AAPL,ADBE,AMAT,AMD,AMZN,AVGO,CRM,CSCO,GOOGL,IBM,INTC,META,MSFT,MU,NFLX,NOW,NVDA,ORCL,QCOM,TXN
timestamp,,,,,,,,,,,,,,,,,,,,
2021-01-04 05:00:00+00:00,129.410,485.340,86.870,92.300,3186.630,425.22,220.31,43.960,1726.130,123.940,49.670,268.940,217.690,74.050,522.860,526.83,524.540,63.75,148.500,162.220
2021-01-05 05:00:00+00:00,131.010,485.690,89.600,92.770,3218.510,428.10,221.52,43.980,1740.050,126.140,50.610,270.970,217.900,77.260,520.800,531.97,536.190,62.96,152.430,163.410
2021-01-06 05:00:00+00:00,126.660,466.310,90.830,90.330,3138.380,425.46,216.15,44.400,1722.880,129.290,51.100,263.340,212.250,77.110,500.490,507.25,504.580,62.57,151.190,164.220
2021-01-07 05:00:00+00:00,130.920,477.740,94.560,95.160,3162.160,443.39,217.98,44.960,1774.340,128.990,52.190,268.740,218.290,79.110,508.890,511.41,533.760,63.07,155.700,167.940
2021-01-08 05:00:00+00:00,132.050,485.100,95.560,94.580,3182.700,445.64,222.04,45.060,1797.830,128.530,51.650,267.570,219.620,77.420,510.400,529.64,531.070,63.38,156.640,171.160
2021-01-11 05:00:00+00:00,128.980,474.240,97.960,97.250,3114.210,445.76,218.25,45.360,1756.290,128.580,51.540,256.840,217.490,78.670,499.100,523.06,544.860,63.03,156.110,171.310
2021-01-12 05:00:00+00:00,128.800,471.650,100.010,95.355,3120.830,449.39,215.52,45.790,1737.430,129.210,53.240,251.090,214.930,79.460,494.250,513.21,539.390,62.42,154.450,172.300
2021-01-13 05:00:00+00:00,130.890,472.050,98.050,91.780,3165.890,451.21,218.18,45.360,1747.250,126.920,56.950,251.640,216.340,79.910,507.790,521.71,541.270,62.06,157.420,171.410
2021-01-14 05:00:00+00:00,128.910,463.270,105.800,90.790,3127.470,452.07,215.60,45.150,1730.920,128.970,59.250,245.640,213.020,81.300,500.860,514.34,528.010,61.60,160.850,171.710
2021-01-15 05:00:00+00:00,127.140,458.080,103.140,88.210,3104.250,445.85,213.14,45.430,1727.620,128.390,57.580,251.360,212.650,80.720,497.980,513.76,514.380,61.78,157.090,169.190
2021-01-19 05:00:00+00:00,127.830,456.500,109.220,89.450,3120.760,459.27,216.76,45.190,1784.470,129.020,57.990,261.100,216.440,85.500,501.770,519.42,521.010,61.29,163.770,174.190
2021-01-20 05:00:00+00:00,132.030,469.730,107.840,88.750,3263.380,461.88,223.44,45.340,1880.070,130.080,58.670,267.480,224.340,83.500,586.340,542.19,534.630,61.56,164.600,173.330
2021-01-21 05:00:00+00:00,136.870,472.020,107.970,91.530,3306.990,466.82,222.17,45.110,1884.150,131.650,62.460,272.870,224.970,85.010,579.840,544.33,554.700,61.21,164.750,175.100
2021-01-22 05:00:00+00:00,139.070,472.440,106.330,92.790,3292.230,465.02,225.77,44.770,1892.560,118.610,56.660,274.500,225.950,82.280,565.170,541.09,548.500,60.36,162.420,172.810
2021-01-25 05:00:00+00:00,142.920,473.440,108.120,94.130,3294.000,464.79,225.92,45.030,1893.540,118.580,55.440,278.010,229.530,81.280,556.780,537.88,546.130,60.90,164.400,172.920
2021-01-26 05:00:00+00:00,143.160,476.280,105.530,94.710,3326.130,463.87,226.26,45.260,1907.950,122.490,55.210,282.050,232.330,79.510,561.930,532.46,537.410,61.80,162.550,171.470
2021-01-27 05:00:00+00:00,142.060,460.000,98.580,88.840,3232.580,444.70,224.78,45.700,1818.940,122.470,53.590,272.140,232.900,75.090,523.280,516.50,516.710,62.55,153.670,162.930
2021-01-28 05:00:00+00:00,137.090,465.670,101.150,87.520,3237.620,451.74,226.50,45.340,1853.200,120.080,56.065,265.000,238.930,78.390,538.600,554.24,522.040,61.22,155.550,169.230
2021-01-29 05:00:00+00:00,131.960,458.770,96.680,85.640,3206.200,450.50,225.56,44.580,1827.360,119.110,55.510,258.330,231.960,78.270,532.390,543.16,519.590,60.43,156.280,165.690
2021-02-01 05:00:00+00:00,134.100,470.000,101.210,87.660,3342.880,466.74,228.46,45.400,1893.070,120.540,56.690,262.010,239.650,80.430,539.040,558.56,529.480,61.51,161.580,172.460
2021-02-02 05:00:00+00:00,134.990,484.930,103.590,88.860,3380.000,476.88,234.20,45.830,1919.120,119.440,58.000,267.080,239.510,81.620,548.160,583.51,542.270,62.37,164.780,174.750
2021-02-03 05:00:00+00:00,133.940,481.920,99.870,87.890,3312.530,465.19,234.82,45.770,2058.880,119.120,57.680,266.650,243.000,79.110,539.450,576.65,541.220,62.17,162.300,168.580
2021-02-04 05:00:00+00:00,137.390,489.380,103.240,87.840,3331.000,470.63,237.98,47.250,2053.630,121.020,58.790,266.490,242.010,81.250,552.160,588.98,546.570,63.35,147.970,172.000
2021-02-05 05:00:00+00:00,136.760,492.120,100.710,87.900,3352.150,466.01,238.89,48.080,2088.830,121.790,58.180,268.100,242.200,81.100,550.790,589.73,543.640,63.60,145.840,169.930
2021-02-08 05:00:00+00:00,136.910,493.760,106.190,91.470,3322.940,472.70,238.93,48.940,2084.520,123.610,59.160,266.580,242.470,84.010,547.920,587.91,577.550,63.11,147.380,175.120
2021-02-09 05:00:00+00:00,136.010,496.050,105.380,90.910,3305.000,474.63,236.70,48.500,2075.390,122.100,58.780,269.450,243.770,83.320,559.070,581.78,570.530,63.67,146.110,173.690
2021-02-10 05:00:00+00:00,135.390,492.670,105.880,92.350,3286.580,470.05,236.72,47.240,2086.480,122.240,58.860,271.870,242.820,82.350,563.590,589.36,590.570,63.27,145.500,174.360
2021-02-11 05:00:00+00:00,135.130,496.620,113.000,92.660,3262.130,478.39,241.24,47.580,2088.750,120.910,60.660,270.390,244.490,86.480,557.590,594.47,610.030,62.70,145.560,179.220
2021-02-12 05:00:00+00:00,135.370,498.840,116.700,93.770,3277.710,486.32,240.37,47.290,2095.030,120.800,61.865,270.500,244.990,88.010,556.520,591.29,598.450,63.08,147.980,179.640
2021-02-16 05:00:00+00:00,133.190,501.640,118.350,91.460,3268.950,489.13,248.59,46.510,2110.700,120.070,62.470,273.900,243.700,87.740,557.280,585.74,613.210,62.14,147.160,180.760
2021-02-17 05:00:00+00:00,130.840,491.230,115.710,89.940,3308.640,482.48,247.66,46.250,2118.620,119.970,61.850,273.570,244.200,86.050,551.340,580.94,596.240,62.09,144.750,178.530
2021-02-18 05:00:00+00:00,129.710,488.370,113.430,88.640,3328.230,483.26,247.01,46.340,2105.810,120.730,61.610,269.390,243.790,88.535,548.220,575.80,593.160,62.07,143.910,176.510
2021-02-19 05:00:00+00:00,129.870,479.120,119.460,89.580,3249.900,489.96,246.56,45.680,2088.810,118.990,63.010,261.560,240.970,90.960,540.220,570.73,597.060,61.13,144.940,178.350
2021-02-22 05:00:00+00:00,126.000,467.330,115.230,85.370,3180.740,476.36,240.95,45.430,2054.260,120.860,60.710,260.330,234.510,86.280,533.780,550.26,574.230,64.45,139.460,173.090
2021-02-23 05:00:00+00:00,125.860,467.800,116.140,84.740,3194.500,471.90,235.64,45.510,2060.120,120.710,61.120,265.855,233.270,88.230,546.150,551.75,565.680,64.50,137.120,172.850
2021-02-24 05:00:00+00:00,125.350,476.620,122.810,86.940,3159.530,480.88,240.47,45.740,2083.810,123.210,63.190,264.310,234.550,92.520,553.410,551.83,579.960,64.70,141.100,179.390
2021-02-25 05:00:00+00:00,121.000,459.160,113.930,82.420,3057.160,457.16,231.08,45.520,2015.950,122.470,60.400,254.690,228.990,88.120,546.700,528.79,532.300,65.30,135.530,170.530
2021-02-26 05:00:00+00:00,121.260,459.670,118.190,84.510,3092.930,469.87,216.50,44.870,2021.910,118.930,60.780,257.620,232.380,91.530,538.850,533.46,548.580,64.51,136.190,172.270
2021-03-01 05:00:00+00:00,127.790,469.570,122.250,86.390,3146.140,489.58,217.54,45.920,2069.660,120.740,62.880,264.910,236.940,94.760,550.640,556.47,553.670,66.17,139.490,177.670
2021-03-02 05:00:00+00:00,125.120,466.590,117.500,84.130,3094.530,480.51,213.47,45.515,2064.480,120.330,61.240,259.000,233.870,91.090,547.820,549.30,536.250,66.66,137.040,174.890
2021-03-03 05:00:00+00:00,122.060,448.450,115.440,80.860,3005.000,463.06,206.00,45.130,2011.410,122.360,59.900,255.410,227.560,89.110,520.700,516.00,512.190,66.91,131.660,170.590
2021-03-04 05:00:00+00:00,120.130,439.060,108.240,77.750,2977.570,443.59,205.33,44.560,2033.930,120.110,58.330,257.640,226.730,84.330,511.290,490.63,494.810,65.61,127.800,163.250
2021-03-05 05:00:00+00:00,121.420,440.830,113.450,78.520,3000.460,450.14,210.76,46.250,2097.070,122.830,60.740,264.280,231.600,88.930,516.390,486.96,498.460,69.97,129.750,167.940
2021-03-08 05:00:00+00:00,116.360,421.200,105.680,73.960,2951.950,421.25,207.72,47.510,2007.500,124.810,59.850,255.310,227.390,85.050,493.330,464.05,463.730,72.16,123.200,162.110
2021-03-09 05:00:00+00:00,121.085,439.180,114.220,78.530,3062.850,443.60,211.53,47.890,2040.360,124.180,62.670,265.740,233.780,89.300,506.440,488.95,500.810,72.64,129.110,170.360
2021-03-10 05:00:00+00:00,119.980,437.010,112.680,77.520,3057.640,437.59,211.96,48.290,2036.190,127.870,62.250,264.900,232.420,85.410,504.540,474.00,498.730,72.12,127.870,169.420
2021-03-11 05:00:00+00:00,121.960,451.060,117.190,81.230,3113.590,453.69,215.95,48.800,2100.540,127.140,63.310,273.880,237.130,89.310,523.060,502.87,519.740,67.41,131.740,174.950
2021-03-12 05:00:00+00:00,121.050,444.300,114.290,81.050,3089.490,451.17,212.21,48.820,2050.000,127.610,62.900,268.400,235.750,87.770,518.020,489.22,514.240,67.16,129.980,173.570
2021-03-15 04:00:00+00:00,123.990,447.590,114.880,82.500,3081.680,470.77,212.80,49.410,2054.440,128.580,63.790,273.750,234.810,88.850,520.250,496.77,527.650,67.73,131.640,174.910
2021-03-16 04:00:00+00:00,125.570,450.540,118.500,82.750,3091.860,478.18,214.48,49.670,2083.890,128.240,64.780,279.280,237.710,91.430,524.030,498.99,531.650,66.85,133.650,177.140
2021-03-17 04:00:00+00:00,124.760,451.010,119.900,82.630,3135.730,483.59,213.12,49.420,2082.220,129.030,65.780,284.010,237.040,94.760,524.440,485.00,533.650,66.22,133.920,179.350
2021-03-18 04:00:00+00:00,120.530,439.180,114.280,78.120,3027.990,464.15,209.48,48.800,2021.340,130.060,63.725,278.620,230.720,89.820,504.660,466.18,508.900,66.74,129.750,174.360
2021-03-19 04:00:00+00:00,119.990,441.500,114.860,79.060,3074.960,474.46,212.20,48.980,2026.960,128.900,63.760,290.110,230.350,90.510,512.180,470.84,513.830,66.26,131.020,175.980
2021-03-22 04:00:00+00:00,123.390,452.410,119.330,80.300,3110.870,475.28,215.17,50.300,2030.690,130.550,65.630,293.540,235.990,91.280,523.110,476.65,527.450,66.32,134.090,180.100
2021-03-23 04:00:00+00:00,122.540,460.200,116.380,78.380,3137.500,464.06,215.00,50.010,2041.330,130.460,63.480,290.630,237.580,85.400,535.090,478.17,522.830,67.27,132.520,178.780
2021-03-24 04:00:00+00:00,120.090,451.510,121.100,76.480,3087.070,457.27,209.53,49.650,2032.530,130.620,62.040,282.140,235.460,83.000,520.810,472.32,505.720,66.83,127.180,178.900
2021-03-25 04:00:00+00:00,120.590,450.990,119.720,76.220,3046.260,461.70,205.44,50.510,2032.460,133.070,62.020,278.740,232.340,84.090,502.860,472.18,501.410,68.63,127.280,178.490
2021-03-26 04:00:00+00:00,121.210,469.090,128.640,77.410,3052.030,482.04,209.09,52.570,2024.730,136.380,64.870,283.020,236.480,87.990,508.050,495.00,513.570,70.25,132.990,188.200
2021-03-29 04:00:00+00:00,121.390,469.320,125.710,77.140,3075.730,472.62,210.77,52.520,2045.790,135.860,64.500,290.820,235.240,86.590,513.950,485.39,517.930,71.13,131.270,186.180
2021-03-30 04:00:00+00:00,119.900,465.460,126.760,76.000,3055.290,456.16,210.00,51.770,2046.470,134.720,63.770,288.000,231.850,86.540,513.390,487.57,514.870,70.55,130.110,185.940
2021-03-31 04:00:00+00:00,122.150,475.370,133.600,78.500,3094.080,463.66,211.87,51.710,2062.520,133.260,64.000,294.530,235.770,88.210,521.660,500.11,533.930,70.17,132.590,188.990
2021-04-01 04:00:00+00:00,123.000,483.340,141.520,81.090,3161.000,475.95,218.72,51.980,2129.780,133.230,64.550,298.660,242.350,92.410,539.420,507.01,552.470,71.81,137.790,192.060
2021-04-05 04:00:00+00:00,125.900,491.620,143.050,81.430,3226.730,488.48,220.29,52.410,2218.960,135.930,66.540,308.910,249.070,93.750,540.670,514.02,559.500,74.16,140.330,196.930
2021-04-06 04:00:00+00:00,126.210,491.340,139.540,81.440,3223.820,483.87,221.09,52.025,2209.260,134.220,65.560,306.260,247.860,93.490,544.530,509.08,554.460,74.28,138.060,194.590
2021-04-07 04:00:00+00:00,127.900,493.410,139.140,82.200,3279.390,482.46,220.79,51.770,2239.030,134.930,66.250,313.090,249.900,93.960,546.990,510.73,565.740,74.07,139.430,193.090
2021-04-08 04:00:00+00:00,130.360,499.840,139.350,83.350,3299.300,485.48,224.45,51.910,2250.430,135.120,67.050,313.020,253.250,95.290,554.580,524.04,572.680,75.28,140.340,195.200
2021-04-09 04:00:00+00:00,132.995,504.040,138.910,82.760,3372.200,485.09,231.28,52.090,2270.670,135.730,68.260,312.460,255.850,95.300,555.310,530.00,576.000,75.58,140.570,195.430
2021-04-12 04:00:00+00:00,131.240,506.030,135.000,78.580,3379.390,483.67,228.76,51.570,2244.620,134.590,65.405,311.540,255.910,95.590,552.780,537.00,608.360,76.12,137.440,192.430
2021-04-13 04:00:00+00:00,134.430,514.860,135.100,80.190,3400.000,484.96,232.00,51.660,2254.430,131.180,65.220,309.760,258.490,92.150,553.730,548.93,627.180,76.67,137.300,191.240
2021-04-14 04:00:00+00:00,132.030,510.630,134.140,78.550,3333.000,477.30,228.02,51.370,2241.910,132.630,64.190,302.820,255.590,90.670,540.020,544.84,611.080,76.82,134.750,190.330
2021-04-15 04:00:00+00:00,134.500,523.250,134.410,83.010,3379.090,480.00,233.00,51.640,2285.250,132.580,65.020,307.820,259.500,90.270,549.220,559.35,645.490,78.29,137.840,193.170
2021-04-16 04:00:00+00:00,134.160,525.080,133.730,82.150,3399.440,478.79,231.91,52.800,2282.750,133.590,64.750,306.180,260.740,90.660,546.540,556.91,636.500,78.95,138.210,191.930
2021-04-19 04:00:00+00:00,134.840,516.170,130.890,81.110,3372.010,462.00,230.50,52.850,2289.760,133.120,63.630,302.240,258.740,88.410,554.440,549.37,614.470,78.75,135.250,187.060
2021-04-20 04:00:00+00:00,133.110,514.210,128.590,79.270,3334.690,457.26,227.96,51.790,2279.010,138.160,62.700,302.650,258.260,87.480,549.570,540.78,606.850,79.24,133.400,185.270
2021-04-21 04:00:00+00:00,133.500,512.340,135.050,81.610,3362.020,459.79,230.56,51.930,2278.350,143.550,63.700,301.470,260.580,89.490,508.900,546.47,614.420,76.66,136.190,188.900
2021-04-22 04:00:00+00:00,131.940,507.290,131.750,79.060,3309.040,455.11,231.35,51.500,2252.520,141.280,62.570,296.520,257.170,84.710,508.780,548.49,594.010,74.87,132.970,185.800
2021-04-23 04:00:00+00:00,134.320,515.840,134.860,82.760,3340.880,466.13,233.51,51.910,2299.930,142.430,59.240,301.130,261.150,86.030,505.550,552.70,610.610,74.97,135.430,188.820
2021-04-26 04:00:00+00:00,134.720,515.700,137.300,85.410,3409.000,471.85,235.46,51.640,2309.930,141.570,58.760,303.040,261.550,87.840,510.300,559.21,619.120,74.50,138.960,191.360
2021-04-27 04:00:00+00:00,134.390,517.320,136.780,85.210,3417.430,466.35,234.21,51.370,2290.980,142.010,57.970,303.570,261.970,89.460,505.550,562.63,615.270,75.22,138.010,190.210
2021-04-28 04:00:00+00:00,133.580,515.480,135.690,84.020,3458.500,459.20,236.88,51.110,2359.040,143.000,57.620,307.100,254.560,86.030,506.520,557.24,611.070,74.77,136.570,181.820
2021-04-29 04:00:00+00:00,133.480,516.090,135.390,83.910,3471.310,466.29,234.36,51.460,2392.760,144.240,58.280,329.510,252.510,88.060,509.000,505.00,612.990,75.87,142.680,185.820
2021-04-30 04:00:00+00:00,131.460,508.340,132.710,81.620,3467.420,456.20,230.32,50.910,2353.500,141.880,57.530,325.080,252.180,86.070,513.470,506.37,600.380,75.79,138.800,180.510
2021-05-03 04:00:00+00:00,132.540,503.460,132.850,78.550,3386.490,450.14,223.76,51.170,2343.080,144.750,57.260,322.580,251.860,85.020,509.110,490.32,593.470,77.33,137.430,178.795
2021-05-04 04:00:00+00:00,127.850,490.700,128.720,78.610,3311.870,444.54,217.18,50.710,2306.830,145.750,56.900,318.360,247.790,84.410,503.180,483.30,574.050,78.53,134.120,179.030
2021-05-05 04:00:00+00:00,128.100,486.690,130.290,77.830,3270.540,443.83,215.40,51.130,2314.770,145.220,56.850,315.020,246.470,85.150,496.080,479.97,578.340,79.19,134.650,181.650
2021-05-06 04:00:00+00:00,129.740,483.610,131.730,77.890,3306.370,448.58,218.05,52.440,2337.350,148.420,57.190,320.020,249.730,84.800,499.550,485.84,580.920,79.74,136.000,184.270
2021-05-07 04:00:00+00:00,130.210,488.730,132.950,78.810,3291.610,452.58,216.50,53.430,2351.930,145.460,57.670,319.080,252.460,85.980,503.840,483.51,592.490,80.40,137.850,187.760
2021-05-10 04:00:00+00:00,126.850,479.380,124.690,75.990,3190.490,436.10,213.89,53.160,2291.750,146.170,55.970,305.970,247.180,80.850,486.690,466.80,570.630,80.15,128.940,182.050
2021-05-11 04:00:00+00:00,125.910,485.190,123.550,76.830,3223.910,440.07,215.56,52.830,2270.060,144.220,55.040,306.530,246.230,80.680,495.080,481.50,572.250,77.69,128.370,183.200
2021-05-12 04:00:00+00:00,122.770,472.090,114.880,74.640,3151.940,422.38,210.54,51.600,2200.250,141.300,53.620,302.550,239.000,76.800,484.980,464.71,550.340,76.75,124.620,176.600
2021-05-13 04:00:00+00:00,124.970,474.160,119.920,73.090,3161.470,430.60,211.86,52.490,2229.040,144.170,54.010,305.260,243.030,77.190,486.660,454.98,546.610,78.14,127.110,178.990
2021-05-14 04:00:00+00:00,127.450,486.560,124.830,74.590,3222.900,441.62,217.66,52.900,2278.380,144.680,55.350,315.940,248.150,79.700,493.370,460.33,569.720,78.89,130.150,183.270
2021-05-17 04:00:00+00:00,126.270,482.740,123.570,74.650,3270.390,439.94,215.06,52.940,2288.920,145.110,55.330,315.460,245.180,80.390,488.940,454.40,566.620,79.08,129.800,180.830
2021-05-18 04:00:00+00:00,124.850,480.620,121.810,74.440,3232.280,433.74,214.33,52.930,2262.470,143.910,54.840,309.960,243.080,78.880,486.280,457.22,560.630,78.69,128.910,178.870
2021-05-19 04:00:00+00:00,124.690,480.470,124.800,76.230,3231.800,441.72,221.34,52.470,2271.500,143.190,55.360,313.590,243.120,79.930,487.700,459.76,562.630,78.74,130.660,181.720
2021-05-20 04:00:00+00:00,127.310,491.670,130.310,78.060,3247.680,455.00,223.78,52.850,2306.950,143.880,55.950,318.610,246.480,81.130,501.670,471.13,584.500,78.72,132.640,185.300
2021-05-21 04:00:00+00:00,125.430,488.070,128.660,77.170,3203.080,451.24,222.58,52.430,2294.130,144.740,56.080,316.230,245.170,80.720,497.890,469.47,599.670,79.03,131.460,185.010
2021-05-24 04:00:00+00:00,127.100,497.830,134.580,77.440,3244.990,459.19,226.99,53.390,2361.040,144.720,56.960,324.630,250.780,82.900,502.900,476.36,624.480,79.38,132.910,188.690
2021-05-25 04:00:00+00:00,126.900,505.080,137.500,77.860,3259.050,459.54,227.71,53.310,2362.870,143.790,56.870,327.790,251.720,81.230,501.340,479.90,625.910,78.83,133.750,188.700
2021-05-26 04:00:00+00:00,126.850,506.980,136.900,78.340,3265.160,460.49,229.68,52.910,2380.310,143.380,56.920,327.660,251.490,82.240,502.360,485.41,628.000,79.26,133.090,188.360
2021-05-27 04:00:00+00:00,125.280,498.280,137.820,78.420,3230.110,467.68,225.83,52.920,2362.680,143.820,57.730,332.750,249.310,83.930,503.860,479.22,619.520,78.98,133.640,189.130
2021-05-28 04:00:00+00:00,124.610,504.580,138.130,80.080,3223.070,472.33,238.10,52.900,2356.850,143.740,57.120,328.730,249.680,84.140,502.810,473.88,649.780,78.74,134.540,189.820
2021-06-01 04:00:00+00:00,124.280,495.910,138.210,80.810,3218.650,468.31,236.20,52.620,2381.180,144.190,56.890,329.130,247.400,84.150,499.080,469.17,650.580,79.57,133.940,189.000
2021-06-02 04:00:00+00:00,125.060,495.770,139.010,81.970,3233.990,473.73,234.62,52.960,2370.590,145.720,57.480,329.150,247.300,84.340,499.240,467.01,671.130,80.27,133.820,190.750
2021-06-03 04:00:00+00:00,123.540,493.140,136.380,80.280,3187.010,464.80,230.84,53.330,2347.580,145.550,56.240,326.040,245.710,82.030,489.430,459.20,678.790,81.09,131.780,186.000
2021-06-04 04:00:00+00:00,125.890,504.500,139.850,81.580,3206.220,475.00,237.48,54.070,2393.570,147.420,57.370,330.350,250.790,83.760,494.740,460.65,703.130,82.89,134.340,190.070
2021-06-07 04:00:00+00:00,125.900,509.470,138.970,81.350,3198.010,463.78,238.14,53.920,2402.300,148.020,57.090,336.580,253.810,84.040,494.660,459.46,704.760,83.94,133.320,188.550
2021-06-08 04:00:00+00:00,126.740,509.200,135.860,80.890,3264.110,463.53,236.42,54.130,2398.440,149.070,57.000,333.680,252.570,80.530,492.390,460.76,698.280,84.61,134.200,186.930
2021-06-09 04:00:00+00:00,127.130,514.680,134.650,79.960,3281.150,463.93,236.09,54.020,2407.940,150.670,57.000,330.250,253.590,78.660,485.810,464.71,694.330,84.52,132.890,186.450
2021-06-10 04:00:00+00:00,126.110,535.520,137.160,81.560,3349.650,468.67,240.19,55.030,2435.130,150.540,57.380,332.460,257.240,79.280,487.270,489.13,697.000,82.30,134.220,188.000
2021-06-11 04:00:00+00:00,127.350,541.260,136.820,81.310,3346.830,470.70,240.31,54.770,2430.200,151.280,57.850,331.260,257.890,79.340,488.770,498.01,713.010,82.90,134.620,188.670

In [48]:
trading_data

symbol,AAPL,ADBE,AMAT,AMD,AMZN,AVGO,CRM,CSCO,GOOGL,IBM,INTC,META,MSFT,MU,NFLX,NOW,NVDA,ORCL,QCOM,TXN
timestamp,,,,,,,,,,,,,,,,,,,,
2024-01-02 05:00:00+00:00,185.64,580.07,154.370,138.580,149.930,1085.380,256.13,50.51,138.170,161.50,47.80,346.290,370.87,82.340,468.50,687.52,481.680,104.06,140.23,169.260
2024-01-03 05:00:00+00:00,184.25,571.79,151.450,135.320,148.470,1058.580,251.84,50.51,138.920,160.10,47.05,344.470,370.60,82.260,470.26,675.30,475.690,102.46,137.60,166.740
2024-01-04 05:00:00+00:00,181.91,567.05,149.310,136.010,144.570,1049.010,251.24,50.08,136.390,160.86,46.87,347.120,367.94,82.710,474.67,671.87,479.980,102.59,136.17,164.465
2024-01-05 05:00:00+00:00,181.18,564.60,149.000,138.580,145.240,1049.280,251.12,50.09,135.730,159.16,46.89,351.950,367.75,83.450,474.06,676.16,490.970,102.73,136.73,165.100
2024-01-08 05:00:00+00:00,185.56,580.55,151.560,146.180,149.100,1074.850,260.87,50.46,138.840,161.14,48.45,358.660,374.69,84.950,485.03,696.26,522.530,104.66,139.03,168.540
2024-01-09 05:00:00+00:00,185.14,586.20,151.030,149.260,151.370,1082.490,261.34,49.91,140.950,160.08,48.05,357.430,375.79,83.330,482.09,698.67,531.400,103.63,139.89,168.630
2024-01-10 05:00:00+00:00,186.19,591.03,149.810,148.540,153.730,1080.570,264.13,50.24,142.280,161.23,47.47,370.470,382.77,82.380,478.33,714.30,543.500,103.92,139.31,167.250
2024-01-11 05:00:00+00:00,185.59,597.49,151.950,148.020,155.180,1099.980,271.38,50.44,142.080,162.16,47.64,369.670,384.63,83.390,492.23,726.46,548.220,104.77,139.03,165.600
2024-01-12 05:00:00+00:00,185.92,596.54,151.250,146.560,154.620,1107.680,271.93,50.34,142.650,165.80,47.12,374.490,388.47,82.390,492.16,729.18,547.100,106.60,140.20,164.870
2024-01-16 05:00:00+00:00,183.63,597.68,153.760,158.740,153.160,1114.960,269.19,50.59,142.490,166.96,47.06,367.460,390.27,84.610,481.24,727.56,563.820,106.57,141.12,163.880
2024-01-17 05:00:00+00:00,182.68,596.10,153.370,160.170,151.710,1103.670,271.44,50.30,141.470,166.08,46.06,368.370,389.47,83.280,480.33,727.54,560.530,106.43,139.32,162.415
2024-01-18 05:00:00+00:00,188.63,593.70,160.340,162.670,153.500,1143.910,274.46,50.75,143.480,166.84,46.74,376.130,393.87,84.820,485.31,745.96,571.070,108.70,145.29,166.910
2024-01-19 05:00:00+00:00,191.56,611.55,167.940,174.230,155.340,1211.200,280.88,51.27,146.380,171.48,48.15,383.450,398.67,87.510,482.95,749.11,594.910,109.67,151.96,173.650
2024-01-22 05:00:00+00:00,193.89,603.59,168.300,168.180,154.780,1220.500,280.30,51.57,145.990,172.83,48.22,381.780,396.51,89.240,485.71,752.45,596.540,110.10,152.87,174.830
2024-01-23 05:00:00+00:00,195.18,597.18,167.050,168.420,156.020,1226.310,276.77,51.76,147.040,173.94,48.89,385.200,398.90,87.530,492.19,753.42,598.730,111.83,153.50,174.340
2024-01-24 05:00:00+00:00,194.50,606.48,174.140,178.290,156.870,1253.870,276.88,51.31,148.700,173.93,49.09,390.700,402.56,88.080,544.87,763.42,613.620,114.31,154.37,170.070
2024-01-25 05:00:00+00:00,194.17,622.58,172.630,180.330,157.750,1230.000,279.03,52.33,151.870,190.43,49.55,393.180,404.87,89.200,562.00,766.69,616.170,115.00,154.47,167.420
2024-01-26 05:00:00+00:00,192.42,613.93,166.900,177.250,159.120,1204.880,279.94,52.14,152.185,187.42,43.65,394.140,403.93,88.050,570.42,769.44,610.310,114.64,150.72,164.090
2024-01-29 05:00:00+00:00,191.73,630.23,168.480,177.830,161.260,1217.770,287.86,52.29,153.510,187.14,43.84,401.020,409.72,89.070,575.79,787.24,624.650,113.75,149.64,166.040
2024-01-30 05:00:00+00:00,188.04,627.96,166.240,172.060,159.000,1208.160,287.73,52.24,151.460,187.87,42.92,400.060,408.59,86.160,562.85,785.73,627.740,114.16,145.98,162.050
2024-01-31 05:00:00+00:00,184.40,617.78,164.300,167.690,155.200,1180.000,281.09,50.18,140.100,183.66,43.08,390.140,397.58,85.750,564.11,765.40,615.270,111.70,148.51,160.120
2024-02-01 05:00:00+00:00,186.86,627.91,166.970,170.480,159.280,1200.010,283.80,50.18,141.160,186.90,43.36,394.780,403.78,85.610,567.51,771.00,630.270,115.53,141.11,159.690
2024-02-02 05:00:00+00:00,185.85,634.76,168.180,177.660,171.810,1224.340,285.66,50.18,142.380,185.79,42.60,474.990,411.22,86.480,564.64,781.30,661.600,115.79,141.69,159.200
2024-02-05 05:00:00+00:00,187.68,630.50,171.090,174.230,170.310,1243.100,288.11,49.51,143.680,183.42,42.77,459.410,405.65,86.980,562.06,784.84,693.320,116.39,144.03,158.900
2024-02-06 05:00:00+00:00,189.30,607.14,168.700,167.880,169.150,1222.650,285.83,49.98,144.100,183.41,42.74,454.720,405.49,84.600,555.88,777.45,682.230,115.30,144.10,158.370
2024-02-07 05:00:00+00:00,189.41,615.85,170.900,170.940,170.530,1257.060,288.84,49.77,145.540,183.74,42.78,469.590,414.05,85.170,559.30,790.39,700.990,117.27,145.89,158.770
2024-02-08 05:00:00+00:00,188.32,615.86,173.890,169.350,169.840,1274.760,291.95,49.95,145.910,184.36,42.50,470.000,414.11,84.880,558.53,799.41,696.410,116.68,148.18,160.210
2024-02-09 05:00:00+00:00,188.85,627.21,185.840,172.480,174.450,1283.440,291.30,50.13,149.000,186.34,43.31,468.110,420.55,85.560,561.32,812.94,721.330,116.64,151.00,162.400
2024-02-12 05:00:00+00:00,187.15,611.84,185.540,171.910,172.340,1265.000,287.32,49.99,147.530,186.16,44.03,468.900,415.26,85.700,557.85,787.35,722.480,115.84,153.10,161.080
2024-02-13 05:00:00+00:00,185.04,601.89,180.310,171.540,168.640,1251.650,281.15,49.64,145.140,183.70,43.16,460.120,406.32,81.530,554.52,773.76,721.280,113.68,150.04,156.850
2024-02-14 05:00:00+00:00,184.15,604.66,186.190,178.700,170.980,1262.220,289.15,50.28,145.940,183.57,44.19,473.280,409.49,81.830,579.33,792.00,739.000,114.26,153.94,157.870
2024-02-15 05:00:00+00:00,183.86,590.44,187.660,176.760,169.800,1265.070,291.94,49.06,142.770,186.87,44.05,484.030,406.56,81.630,593.46,780.00,726.580,112.78,155.98,160.710
2024-02-16 05:00:00+00:00,182.31,546.66,199.570,173.870,169.510,1245.480,289.72,48.44,140.520,187.64,43.51,473.320,404.06,79.500,583.95,765.00,726.130,111.31,152.69,160.380
2024-02-20 05:00:00+00:00,181.56,541.91,189.140,165.690,167.080,1226.550,286.39,48.28,141.120,183.44,44.52,471.750,402.79,80.710,575.13,752.84,694.520,108.45,151.96,162.740
2024-02-21 05:00:00+00:00,182.32,538.52,190.330,164.290,168.590,1227.450,283.55,48.48,142.550,179.70,43.47,468.030,402.18,81.490,573.35,747.94,674.720,108.16,152.01,164.080
2024-02-22 05:00:00+00:00,184.37,537.57,199.730,181.860,174.580,1304.900,293.65,48.57,144.090,184.21,42.98,486.130,411.65,85.910,588.47,769.21,785.380,111.01,154.75,165.430
2024-02-23 05:00:00+00:00,182.52,553.44,197.160,176.520,174.990,1296.370,292.80,48.86,143.960,185.72,42.99,484.030,410.34,86.000,583.56,770.97,788.170,111.95,154.91,163.690
2024-02-26 05:00:00+00:00,181.16,560.48,203.550,176.010,174.730,1309.130,300.39,48.40,137.570,184.13,42.99,481.740,407.54,89.460,587.65,779.66,790.920,110.97,157.03,164.300
2024-02-27 05:00:00+00:00,182.63,552.49,202.860,178.000,173.540,1296.230,299.50,48.31,138.880,184.87,42.73,487.050,407.48,91.850,601.67,767.14,787.010,111.38,158.30,164.940
2024-02-28 05:00:00+00:00,181.42,551.82,197.540,176.540,173.160,1289.420,299.77,48.06,136.380,185.30,41.99,484.020,407.72,89.710,596.48,759.79,776.630,111.68,155.85,163.040
2024-02-29 05:00:00+00:00,180.75,560.28,201.620,192.530,176.760,1300.490,308.82,48.37,138.460,185.03,43.05,490.130,413.64,90.610,602.92,771.34,791.120,111.68,157.79,167.330
2024-03-01 05:00:00+00:00,179.66,570.93,210.250,202.640,178.220,1399.170,316.88,48.40,137.140,188.20,43.82,502.300,415.50,95.150,619.34,773.63,822.790,113.78,163.09,171.050
2024-03-04 05:00:00+00:00,175.10,567.94,209.490,205.360,177.580,1402.260,314.64,49.13,133.350,193.06,45.61,498.190,414.92,95.770,615.83,776.09,852.370,114.06,166.56,172.440
2024-03-05 05:00:00+00:00,170.12,544.84,207.390,205.130,174.120,1342.750,298.75,48.95,132.670,191.95,43.16,490.220,402.65,94.470,598.50,740.15,859.640,110.94,161.45,170.640
2024-03-06 05:00:00+00:00,169.12,543.09,212.170,210.630,173.510,1350.000,303.77,49.17,131.400,196.16,44.51,496.090,402.09,95.560,597.69,741.06,887.000,112.27,167.89,171.870
2024-03-07 05:00:00+00:00,169.00,556.04,212.610,211.380,176.820,1407.010,302.42,48.90,134.380,196.54,46.15,512.190,409.14,98.980,608.51,768.08,926.690,114.54,175.72,175.270
2024-03-08 05:00:00+00:00,170.73,551.69,205.560,207.390,175.350,1308.720,305.28,49.50,135.410,195.95,44.00,505.950,406.22,97.620,604.82,757.68,875.280,112.42,170.57,172.300
2024-03-11 04:00:00+00:00,172.75,560.42,201.370,198.390,171.960,1293.120,306.00,50.22,137.670,191.73,44.86,483.590,404.52,94.510,600.93,756.74,857.740,114.13,171.12,174.190
2024-03-12 04:00:00+00:00,173.23,579.14,204.940,202.760,175.390,1291.880,306.62,50.07,138.500,197.78,45.24,499.750,415.28,97.420,611.08,789.56,919.130,127.54,173.08,174.800
2024-03-13 04:00:00+00:00,171.13,573.55,200.560,194.790,176.555,1257.870,304.68,50.11,139.790,196.70,43.23,495.570,415.10,94.160,609.45,776.88,908.880,125.52,169.25,172.680
2024-03-14 04:00:00+00:00,173.00,570.45,200.750,187.060,178.750,1262.270,303.32,49.79,143.100,193.43,42.75,491.830,425.22,91.430,613.01,779.49,879.440,125.53,168.45,171.140
2024-03-15 04:00:00+00:00,172.62,492.46,198.650,191.060,174.420,1235.500,294.33,48.93,141.180,191.07,42.64,484.100,416.42,93.250,605.88,743.91,878.365,125.54,167.20,172.520
2024-03-18 04:00:00+00:00,173.72,513.86,200.730,190.650,174.480,1237.240,300.51,49.27,147.680,191.69,42.71,496.980,417.32,93.780,618.39,755.80,884.550,127.80,166.92,169.210
2024-03-19 04:00:00+00:00,176.08,521.19,201.340,181.420,175.900,1238.010,301.45,49.14,147.030,193.34,42.05,496.240,421.41,94.000,620.74,756.94,893.980,129.19,164.10,166.760
2024-03-20 04:00:00+00:00,178.67,519.14,205.060,179.730,178.150,1276.000,306.08,49.55,148.740,193.96,42.20,505.520,425.23,96.250,627.69,767.56,903.720,129.24,167.67,169.980
2024-03-21 04:00:00+00:00,171.37,511.25,210.800,178.680,178.150,1348.000,308.39,49.88,147.600,191.90,42.42,507.760,429.37,109.850,622.71,773.18,914.350,129.01,170.85,172.590
2024-03-22 04:00:00+00:00,172.28,499.52,210.250,179.650,178.870,1353.470,307.77,49.78,150.770,190.84,42.57,509.580,428.74,110.210,628.01,774.15,942.890,127.79,170.10,172.480
2024-03-25 04:00:00+00:00,170.85,507.23,208.460,178.630,179.710,1351.580,306.06,49.68,150.070,188.79,41.83,503.020,422.86,117.130,627.46,774.64,950.020,126.08,167.52,170.850
2024-03-26 04:00:00+00:00,169.71,507.60,206.670,177.870,178.300,1331.490,305.83,49.55,150.670,188.50,41.99,495.890,421.65,118.800,629.24,778.57,925.610,126.47,167.07,167.910
2024-03-27 04:00:00+00:00,173.31,504.40,208.000,179.590,179.830,1318.730,301.38,49.77,150.870,190.80,43.77,493.860,421.43,119.250,613.53,759.00,902.500,125.27,169.13,172.870
2024-03-28 04:00:00+00:00,171.48,504.60,206.230,180.490,180.380,1325.410,301.18,49.91,150.930,190.96,44.17,485.580,420.72,117.890,607.33,762.40,903.560,125.61,169.30,174.210
2024-04-01 04:00:00+00:00,170.03,502.09,208.690,183.340,180.970,1350.260,302.26,50.04,155.490,189.83,44.52,491.350,424.57,124.300,614.31,768.37,903.630,125.48,171.72,173.170
2024-04-02 04:00:00+00:00,168.84,499.21,206.110,178.700,180.690,1338.760,304.00,49.36,154.560,188.88,43.94,497.370,421.44,122.750,614.21,757.00,894.520,124.34,171.04,170.360
2024-04-03 04:00:00+00:00,169.65,497.01,207.380,180.770,182.410,1363.210,304.74,48.74,154.920,190.90,40.33,506.740,420.45,128.010,630.08,759.16,889.640,126.24,173.91,170.340
2024-04-04 04:00:00+00:00,168.82,487.11,203.390,165.830,180.000,1317.500,294.14,48.11,150.530,187.94,39.73,510.920,417.88,124.090,617.14,757.55,859.050,124.19,169.76,168.530
2024-04-05 04:00:00+00:00,169.58,485.12,207.850,170.420,185.070,1339.430,301.91,48.55,152.500,189.14,38.71,527.340,425.52,123.580,636.18,783.50,880.080,124.90,171.53,167.500
2024-04-08 04:00:00+00:00,168.45,484.28,209.040,169.900,185.190,1336.100,301.73,48.24,154.850,189.82,37.98,519.250,424.59,122.950,628.41,785.60,871.330,124.35,173.62,169.460
2024-04-09 04:00:00+00:00,169.67,492.55,210.410,170.780,185.670,1334.080,302.37,50.01,156.600,189.31,38.33,516.900,426.28,122.630,618.20,782.22,853.540,123.23,175.57,173.460
2024-04-10 04:00:00+00:00,167.78,487.22,209.250,167.140,185.950,1322.370,299.62,49.21,156.140,186.04,37.20,519.830,423.26,122.200,618.58,769.19,870.390,121.75,170.86,168.920
2024-04-11 04:00:00+00:00,175.04,484.28,212.980,170.500,189.050,1382.460,299.15,49.53,159.410,185.90,37.63,523.160,427.93,127.510,628.78,771.34,906.160,123.24,175.13,171.200
2024-04-12 04:00:00+00:00,176.55,474.09,207.860,163.280,186.130,1344.070,294.32,48.49,157.730,182.27,35.69,511.900,421.90,122.520,622.83,768.71,881.860,121.11,171.29,166.330
2024-04-15 04:00:00+00:00,172.69,470.10,205.680,160.320,183.620,1310.690,272.90,48.24,154.860,181.25,36.31,500.230,413.64,121.370,607.15,735.81,860.010,119.88,169.84,166.350
2024-04-16 04:00:00+00:00,169.38,476.22,209.480,163.460,183.320,1329.060,277.41,47.92,154.400,183.75,36.26,499.760,414.58,121.770,617.52,744.78,874.150,120.62,168.58,167.590
2024-04-17 04:00:00+00:00,168.00,474.45,199.890,154.020,181.280,1282.630,276.32,47.79,155.470,183.10,35.68,494.170,411.84,116.330,613.69,736.45,840.350,118.67,164.32,165.700
2024-04-18 04:00:00+00:00,167.04,473.18,194.320,155.080,179.220,1258.990,271.92,48.11,156.010,181.47,35.04,501.800,404.27,111.930,610.56,731.36,846.710,116.00,161.44,163.670
2024-04-19 04:00:00+00:00,165.00,465.02,189.770,146.640,174.630,1204.710,270.37,48.32,154.090,181.58,34.20,481.070,399.12,106.770,555.04,713.91,762.000,114.88,157.63,159.680
2024-04-22 04:00:00+00:00,165.84,466.89,189.460,148.640,177.230,1224.460,273.81,48.14,156.280,181.90,34.41,481.730,400.96,109.120,554.60,721.95,795.180,114.53,160.18,163.430
2024-04-23 04:00:00+00:00,166.90,472.90,193.240,152.270,179.540,1249.190,276.68,48.32,158.260,182.19,34.28,496.100,407.57,112.460,577.75,740.95,824.230,115.09,161.35,165.470
2024-04-24 04:00:00+00:00,169.02,477.12,196.060,151.740,176.590,1256.820,276.19,48.35,159.130,184.10,34.50,493.500,409.06,111.780,555.12,746.29,796.770,115.34,163.63,174.810
2024-04-25 04:00:00+00:00,169.89,473.44,197.500,153.760,173.670,1294.420,273.14,48.10,156.000,168.91,35.11,441.380,399.04,111.580,564.80,716.25,826.320,114.89,163.30,175.250
2024-04-26 04:00:00+00:00,169.30,477.56,203.380,157.400,179.620,1344.070,274.29,47.86,171.950,167.13,31.88,443.290,406.32,114.840,561.23,723.55,877.350,117.21,165.66,177.480
2024-04-29 04:00:00+00:00,173.50,473.07,205.260,160.200,180.960,1338.620,275.74,47.78,166.150,167.43,31.36,432.620,402.25,114.360,559.49,721.16,877.570,116.49,169.20,179.290
2024-04-30 04:00:00+00:00,170.33,462.83,198.650,158.380,175.000,1300.270,268.94,46.98,162.780,166.20,30.47,430.170,389.33,112.960,550.64,693.33,864.020,113.75,165.85,176.420
2024-05-01 04:00:00+00:00,169.30,469.39,193.990,144.270,179.000,1242.860,268.69,46.84,163.860,164.43,30.37,439.190,394.94,109.700,551.71,685.61,830.410,114.63,164.11,175.200
2024-05-02 04:00:00+00:00,173.03,476.57,197.910,146.160,184.720,1238.570,272.13,46.79,166.620,164.69,30.51,441.680,397.84,112.330,565.15,695.72,858.170,114.96,180.10,175.800
2024-05-03 04:00:00+00:00,183.38,486.18,204.090,150.600,186.210,1278.110,273.66,47.12,167.240,165.71,30.90,451.960,406.66,114.700,579.34,716.65,887.890,115.80,179.64,178.910
2024-05-06 04:00:00+00:00,181.71,493.59,208.860,155.780,188.700,1310.310,275.63,47.11,168.100,168.61,30.97,465.680,413.54,120.130,596.97,726.56,921.400,118.34,181.85,181.670
2024-05-07 04:00:00+00:00,182.40,492.27,207.320,154.430,188.760,1303.110,277.18,47.28,171.250,168.38,30.68,468.240,409.34,119.210,606.00,713.33,905.540,117.93,180.15,182.670
2024-05-08 04:00:00+00:00,182.74,488.10,207.360,153.620,188.000,1325.370,278.97,48.00,169.380,169.90,30.00,472.600,410.54,119.320,609.47,721.03,904.120,117.39,180.55,183.950
2024-05-09 04:00:00+00:00,184.57,482.65,206.330,152.390,189.500,1305.670,275.17,47.79,169.960,166.27,30.09,475.420,412.32,117.810,612.09,722.94,887.470,116.64,180.54,185.320
2024-05-10 04:00:00+00:00,183.05,482.29,209.730,151.920,187.480,1332.800,276.67,48.06,168.650,167.15,29.85,476.200,414.74,121.240,610.87,729.79,898.780,116.67,182.08,187.050
2024-05-13 04:00:00+00:00,186.28,483.11,206.630,150.560,186.570,1337.510,277.52,48.68,169.140,167.56,30.51,468.010,413.72,123.000,616.59,730.12,903.990,116.37,184.21,187.820
2024-05-14 04:00:00+00:00,187.43,475.95,209.820,153.160,187.070,1380.030,276.80,48.95,170.340,167.36,31.05,471.850,416.56,124.810,613.66,721.62,913.560,120.87,188.97,191.130
2024-05-15 04:00:00+00:00,189.72,485.35,217.490,159.670,185.990,1436.170,287.54,49.67,172.510,168.26,31.27,481.540,423.08,127.810,613.52,760.57,946.300,121.63,194.61,195.530
2024-05-16 04:00:00+00:00,189.84,482.88,214.030,162.620,183.630,1412.130,284.68,48.34,174.180,168.97,32.03,473.230,420.99,127.890,610.52,758.01,943.590,122.16,193.27,194.970
2024-05-17 04:00:00+00:00,189.87,483.43,212.080,164.470,184.700,1395.290,285.61,48.17,176.060,169.03,31.83,471.910,420.21,125.290,621.10,765.05,924.790,123.50,193.86,195.020
2024-05-20 04:00:00+00:00,191.04,484.69,219.950,166.330,183.540,1414.030,287.07,47.13,176.920,169.92,32.10,468.840,425.34,129.000,640.82,774.18,947.800,124.52,197.76,199.200
2024-05-21 04:00:00+00:00,192.35,481.85,219.800,164.660,183.150,1399.200,283.76,46.94,177.850,173.47,31.74,464.630,429.04,127.500,650.61,777.05,953.860,124.63,200.85,199.010
2024-05-22 04:00:00+00:00,190.90,483.93,218.150,165.520,183.130,1392.240,283.82,47.43,176.380,173.69,31.42,467.780,430.52,126.280,640.47,770.83,949.500,124.60,202.93,202.540
2024-05-23 04:00:00+00:00,186.88,483.31,217.950,160.430,181.050,1393.290,278.57,46.60,173.550,170.67,30.08,465.780,427.00,126.270,635.67,758.15,1037.990,124.09,201.76,197.290
2024-05-24 04:00:00+00:00,189.98,475.43,220.890,166.360,180.750,1407.840,272.29,46.42,174.990,170.89,30.72,478.220,430.16,129.490,646.75,738.51,1064.690,122.91,210.36,199.180
2024-05-28 04:00:00+00:00,189.99,478.43,221.320,171.610,182.150,1412.450,269.83,46.28,176.400,169.66,31.06,479.920,430.32,132.670,649.00,728.86,1139.010,124.49,213.08,199.600
2024-05-29 04:00:00+00:00,190.29,477.60,219.050,165.140,182.020,1390.670,271.62,46.08,175.900,167.05,30.13,474.360,429.17,131.580,654.62,731.12,1148.250,123.74,208.26,194.910
2024-05-30 04:00:00+00:00,191.29,445.87,216.540,166.750,179.320,1364.080,218.01,46.12,172.110,165.63,30.19,467.050,414.67,126.290,647.66,643.29,1105.000,117.09,204.80,195.680
2024-05-31 04:00:00+00:00,192.25,444.76,215.080,166.900,176.440,1328.550,234.44,46.50,172.500,166.85,30.85,466.830,415.13,125.000,641.62,656.93,1096.330,117.19,204.05,195.010
2024-06-03 04:00:00+00:00,194.03,439.02,214.210,163.550,178.340,1321.900,236.62,46.65,173.170,165.28,30.29,477.490,413.52,128.170,633.79,660.11,1150.000,119.28,205.91,193.720
2024-06-04 04:00:00+00:00,194.35,448.37,212.220,159.990,179.340,1330.820,234.86,47.42,173.790,165.81,30.03,476.990,416.07,126.640,631.62,672.00,1164.370,120.07,204.37,193.300
2024-06-05 04:00:00+00:00,195.87,455.80,223.370,166.170,181.280,1413.090,236.53,46.02,175.410,167.38,30.78,495.060,424.01,133.710,650.27,704.11,1224.400,122.63,211.90,196.080
2024-06-06 04:00:00+00:00,194.48,458.13,221.750,166.780,185.000,1401.270,242.76,46.23,176.730,168.20,30.42,493.760,424.52,130.070,648.52,703.16,1209.980,123.50,209.44,196.240
2024-06-07 04:00:00+00:00,196.89,465.43,221.730,167.870,184.300,1406.640,241.85,45.84,174.460,170.01,30.74,492.960,423.85,130.940,641.47,698.81,1208.880,125.92,206.62,195.610
2024-06-10 04:00:00+00:00,193.12,459.94,228.160,160.340,187.060,1440.470,241.84,45.85,175.010,170.38,30.91,502.600,427.87,134.820,644.50,709.15,121.790,124.50,209.35,197.620
2024-06-11 04:00:00+00:00,207.15,462.69,229.970,158.960,187.230,1461.030,240.99,45.77,176.620,169.32,30.92,507.470,432.68,135.070,648.55,712.04,120.910,123.88,208.52,197.440
2024-06-12 04:00:00+00:00,213.07,459.87,237.650,160.240,186.890,1495.510,235.80,45.62,177.790,169.00,30.76,508.840,441.06,140.750,650.06,721.50,125.200,140.38,215.39,198.980
2024-06-13 04:00:00+00:00,214.24,458.74,237.550,159.900,183.830,1678.990,229.03,45.52,175.160,169.12,30.46,504.100,441.58,143.140,653.26,709.76,129.610,139.85,217.81,196.280

In [49]:
from src.pairs.selection import select_pairs
formation_returns=formation_data.pct_change().dropna()
corr_matrix=formation_returns.corr()
candidate_pairs=[]
correlation_threshold=0.6
for i in range(len(corr_matrix.columns)):
    for j in range(i+1,len(corr_matrix.columns)):
        stock1=corr_matrix.columns[i]
        stock2=corr_matrix.columns[j]
        correlation=corr_matrix.iloc[i,j]
        if correlation>=correlation_threshold:
            candidate_pairs.append(
                (stock1,stock2,correlation)
            )
print(len(candidate_pairs))
selected_pairs=select_pairs(formation_data,candidate_pairs)
selected_pairs

33

[('AMD',
  'MSFT',
  np.float64(0.04959216212157262),
  np.float64(0.011520421568257217),
  np.float64(133.3845452264579),
  np.float64(1.553961517257702))]

In [50]:
from src.pairs.spread import calculate_spread

formation_spreads = []

for pair in selected_pairs:

    spread = calculate_spread(
        formation_data,
        pair,
        pair[4],   # alpha
        pair[5]    # beta
    )

    formation_spreads.append(
        (pair[0], pair[1], pair[2], pair[3], pair[4], pair[5], spread)
    )
formation_spreads

[('AMD',
  'MSFT',
  np.float64(0.04959216212157262),
  np.float64(0.011520421568257217),
  np.float64(133.3845452264579),
  np.float64(1.553961517257702),
  timestamp
  2021-01-04 05:00:00+00:00   -59.125193
  2021-01-05 05:00:00+00:00   -59.645555
  2021-01-06 05:00:00+00:00   -61.503889
  2021-01-07 05:00:00+00:00   -62.969523
  2021-01-08 05:00:00+00:00   -60.738226
  2021-01-11 05:00:00+00:00   -67.017303
  2021-01-12 05:00:00+00:00   -66.632546
  2021-01-13 05:00:00+00:00   -59.667133
  2021-01-14 05:00:00+00:00   -61.448711
  2021-01-15 05:00:00+00:00   -57.809491
  2021-01-19 05:00:00+00:00   -55.946403
  2021-01-20 05:00:00+00:00   -46.958630
  2021-01-21 05:00:00+00:00   -50.648643
  2021-01-22 05:00:00+00:00   -51.626634
  2021-01-25 05:00:00+00:00   -50.128943
  2021-01-26 05:00:00+00:00   -48.230241
  2021-01-27 05:00:00+00:00   -38.538486
  2021-01-28 05:00:00+00:00   -30.457257
  2021-01-29 05:00:00+00:00   -34.505810
  2021-02-01 05:00:00+00:00   -29.954812
  2021-02-02 05:00:00+00:00   -31.959566
  2021-02-03 05:00:00+00:00   -26.962223
  2021-02-04 05:00:00+00:00   -27.874525
  2021-02-05 05:00:00+00:00   -27.777763
  2021-02-08 05:00:00+00:00   -33.055405
  2021-02-09 05:00:00+00:00   -30.885187
  2021-02-10 05:00:00+00:00   -34.072891
  2021-02-11 05:00:00+00:00   -32.884619
  2021-02-12 05:00:00+00:00   -34.109517
  2021-02-16 05:00:00+00:00   -31.809866
  2021-02-17 05:00:00+00:00   -28.947844
  2021-02-18 05:00:00+00:00   -27.337694
  2021-02-19 05:00:00+00:00   -31.618418
  2021-02-22 05:00:00+00:00   -31.536240
  2021-02-23 05:00:00+00:00   -31.797244
  2021-02-24 05:00:00+00:00   -33.935960
  2021-02-25 05:00:00+00:00   -32.472053
  2021-02-26 05:00:00+00:00   -32.329833
  2021-03-01 05:00:00+00:00   -30.691281
  2021-03-02 05:00:00+00:00   -30.249328
  2021-03-03 05:00:00+00:00   -31.477874
  2021-03-04 05:00:00+00:00   -27.475053
  2021-03-05 05:00:00+00:00   -23.801604
  2021-03-08 05:00:00+00:00   -20.925539
  2021-03-09 05:00:00+00:00   -21.637143
  2021-03-10 05:00:00+00:00   -21.427642
  2021-03-11 05:00:00+00:00   -22.482839
  2021-03-12 05:00:00+00:00   -23.583126
  2021-03-15 04:00:00+00:00   -26.776370
  2021-03-16 04:00:00+00:00   -24.264861
  2021-03-17 04:00:00+00:00   -24.748385
  2021-03-18 04:00:00+00:00   -24.060019
  2021-03-19 04:00:00+00:00   -25.890743
  2021-03-22 04:00:00+00:00   -22.177655
  2021-03-23 04:00:00+00:00   -17.604049
  2021-03-24 04:00:00+00:00   -16.771522
  2021-03-25 04:00:00+00:00   -19.487492
  2021-03-26 04:00:00+00:00   -17.196706
  2021-03-29 04:00:00+00:00   -18.017137
  2021-03-30 04:00:00+00:00   -19.635621
  2021-03-31 04:00:00+00:00   -19.600524
  2021-04-01 04:00:00+00:00   -17.045285
  2021-04-05 04:00:00+00:00   -10.853632
  2021-04-06 04:00:00+00:00   -12.079171
  2021-04-07 04:00:00+00:00   -11.220182
  2021-04-08 04:00:00+00:00    -9.657238
  2021-04-09 04:00:00+00:00    -6.140400
  2021-04-12 04:00:00+00:00     0.415159
  2021-04-13 04:00:00+00:00     0.493281
  2021-04-14 04:00:00+00:00     0.141778
  2021-04-15 04:00:00+00:00    -2.878891
  2021-04-16 04:00:00+00:00    -0.302484
  2021-04-19 04:00:00+00:00    -0.686364
  2021-04-20 04:00:00+00:00     1.692925
  2021-04-21 04:00:00+00:00     0.376655
  2021-04-22 04:00:00+00:00     0.929257
  2021-04-23 04:00:00+00:00    -0.840400
  2021-04-26 04:00:00+00:00    -4.558398
  2021-04-27 04:00:00+00:00    -3.827606
  2021-04-28 04:00:00+00:00    -9.388392
  2021-04-29 04:00:00+00:00   -11.267456
  2021-04-30 04:00:00+00:00    -8.038884
  2021-05-03 04:00:00+00:00    -3.588222
  2021-05-04 04:00:00+00:00    -7.751460
  2021-05-05 04:00:00+00:00    -7.859370
  2021-05-06 04:00:00+00:00    -4.692608
  2021-05-07 04:00:00+00:00    -3.392252
  2021-05-10 04:00:00+00:00    -4.290081
  2021-05-11 04:00:00+00:00    -6.545409
  2021-05-12 04:00:00+00:00   -10.372233
  2021-05-13 04:00:00+00:00    -3.933593
  2021-05-14 04:00:00+00:00    -1.144535
  2021-05-17 04:00:00+00:00    -4.207772
  2021-05-18 04:00:00+00:00    -5.981441
  2021-05-19 04:00:00+00:00    -8.723032
  2021-05-20 04:00:00+00:00    -8.206781
  2021-05-21 04:00:00+00:00    -8.133756
  2021-05-24 04:00:00+00:00    -2.943325
  2021-05-25 04:00:00+00:00    -2.655989
  2021-05-26 04:00:00+00:00    -3.631890
  2021-05-27 04:00:00+00:00    -5.936207
  2021-05-28 04:00:00+00:00    -8.145784
  2021-06-01 04:00:00+00:00   -11.560175
  2021-06-02 04:00:00+00:00   -13.462771
  2021-06-03 04:00:00+00:00   -12.426576
  2021-06-04 04:00:00+00:00    -9.366726
  2021-06-07 04:00:00+00:00    -5.989315
  2021-06-08 04:00:00+00:00    -6.514492
  2021-06-09 04:00:00+00:00    -4.049308
  2021-06-10 04:00:00+00:00    -2.885647
  2021-06-11 04:00:00+00:00    -1.847156
  2021-06-14 04:00:00+00:00    -0.220107
  2021-06-15 04:00:00+00:00    -0.071829
  2021-06-16 04:00:00+00:00    -0.492402
  2021-06-17 04:00:00+00:00    -3.887531
  2021-06-18 04:00:00+00:00    -5.497388
  2021-06-21 04:00:00+00:00     0.903773
  2021-06-22 04:00:00+00:00     2.245351
  2021-06-23 04:00:00+00:00     1.637400
  2021-06-24 04:00:00+00:00    -0.490632
  2021-06-25 04:00:00+00:00    -1.414730
  2021-06-28 04:00:00+00:00     0.016486
  2021-06-29 04:00:00+00:00    -1.095180
  2021-06-30 04:00:00+00:00    -8.448151
  2021-07-01 04:00:00+00:00    -6.784694
  2021-07-02 04:00:00+00:00    -2.894701
  2021-07-06 04:00:00+00:00    -2.527290
  2021-07-07 04:00:00+00:00     5.849779
  2021-07-08 04:00:00+00:00     4.582948
  2021-07-09 04:00:00+00:00     3.300353
  2021-07-12 04:00:00+00:00     2.820209
  2021-07-13 04:00:00+00:00     7.334888
  2021-07-14 04:00:00+00:00    10.745182
  2021-07-15 04:00:00+00:00    12.559580
  2021-07-16 04:00:00+00:00    13.895700
  2021-07-19 04:00:00+00:00     9.083467
  2021-07-20 04:00:00+00:00    10.569867
  2021-07-21 04:00:00+00:00     9.075756
  2021-07-22 04:00:00+00:00    11.018625
  2021-07-23 04:00:00+00:00    13.087901
  2021-07-26 04:00:00+00:00    12.980708
  2021-07-27 04:00:00+00:00    11.698338
  2021-07-28 04:00:00+00:00     0.656003
  2021-07-29 04:00:00+00:00    -6.864883
  2021-07-30 04:00:00+00:00   -13.489719
  2021-08-02 04:00:00+00:00   -17.371385
  2021-08-03 04:00:00+00:00   -21.178454
  2021-08-04 04:00:00+00:00   -31.438555
  2021-08-05 04:00:00+00:00   -18.452122
  2021-08-06 04:00:00+00:00   -15.031248
  2021-08-09 04:00:00+00:00   -12.229725
  2021-08-10 04:00:00+00:00   -12.410368
  2021-08-11 04:00:00+00:00   -13.765121
  2021-08-12 04:00:00+00:00    -9.071447
  2021-08-13 04:00:00+00:00   -12.324991
  2021-08-16 04:00:00+00:00    -5.804329
  2021-08-17 04:00:00+00:00    -7.448646
  2021-08-18 04:00:00+00:00    -3.396325
  2021-08-19 04:00:00+00:00     2.239645
  2021-08-20 04:00:00+00:00     8.353382
  2021-08-23 04:00:00+00:00     2.241061
  2021-08-24 04:00:00+00:00     1.951497
  2021-08-25 04:00:00+00:00     0.331422
  2021-08-26 04:00:00+00:00    -0.987997
  2021-08-27 04:00:00+00:00    -6.775858
  2021-08-30 04:00:00+00:00    -2.781541
  2021-08-31 04:00:00+00:00    -3.559164
  2021-09-01 04:00:00+00:00    -2.474773
  2021-09-02 04:00:00+00:00    -1.927143
  2021-09-03 04:00:00+00:00    -3.055995
  2021-09-07 04:00:00+00:00    -2.819445
  2021-09-08 04:00:00+00:00     1.841360
  2021-09-09 04:00:00+00:00    -1.087560
  2021-09-10 04:00:00+00:00    -1.151297
  2021-09-13 04:00:00+00:00     0.750288
  2021-09-14 04:00:00+00:00     2.105104
  2021-09-15 04:00:00+00:00     7.337119
  2021-09-16 04:00:00+00:00     6.773662
  2021-09-17 04:00:00+00:00     5.059932
  2021-09-20 04:00:00+00:00     3.110663
  2021-09-21 04:00:00+00:00     1.637132
  2021-09-22 04:00:00+00:00     2.992952
  2021-09-23 04:00:00+00:00     1.222440
  2021-09-24 04:00:00+00:00     1.556326
  2021-09-27 04:00:00+00:00    -7.291023
  2021-09-28 04:00:00+00:00    -7.622718
  2021-09-29 04:00:00+00:00    -5.324583
  2021-09-30 04:00:00+00:00   -11.367185
  2021-10-01 04:00:00+00:00    -3.487903
  2021-10-04 04:00:00+00:00    -6.199044
  2021-10-05 04:00:00+00:00    -2.833367
  2021-10-06 04:00:00+00:00    -1.327117
  2021-10-07 04:00:00+00:00    -3.953749
  2021-10-08 04:00:00+00:00    -1.793742
  2021-10-11 04:00:00+00:00    -1.823237
  2021-10-12 04:00:00+00:00    -3.732663
  2021-10-13 04:00:00+00:00    -6.704984
  2021-10-14 04:00:00+00:00    -4.662696
  2021-10-15 04:00:00+00:00    -3.404711
  2021-10-18 04:00:00+00:00    -7.022285
  2021-10-19 04:00:00+00:00    -5.926889
  2021-10-20 04:00:00+00:00    -6.840126
  2021-10-21 04:00:00+00:00    -8.058773
  2021-10-22 04:00:00+00:00   -10.420214
  2021-10-25 04:00:00+00:00   -15.397276
  2021-10-26 04:00:00+00:00   -14.303035
  2021-10-27 04:00:00+00:00    -0.232960
  2021-10-28 04:00:00+00:00     2.687477
  2021-10-29 04:00:00+00:00    11.402662
  2021-11-01 04:00:00+00:00     1.382854
  2021-11-02 04:00:00+00:00     1.413346
  2021-11-03 04:00:00+00:00    -2.223142
  2021-11-04 04:00:00+00:00   -10.614254
  2021-11-05 04:00:00+00:00    -9.191658
  2021-11-08 05:00:00+00:00   -29.737407
  2021-11-09 05:00:00+00:00   -28.850494
  2021-11-10 05:00:00+00:00   -19.937143
  2021-11-11 05:00:00+00:00   -27.848466
  2021-11-12 05:00:00+00:00   -26.479914
  2021-11-15 05:00:00+00:00   -24.954368
  2021-11-16 05:00:00+00:00   -30.775979
  2021-11-17 05:00:00+00:00   -29.441081
  2021-11-18 05:00:00+00:00   -33.009660
  2021-11-19 05:00:00+00:00   -31.775705
  2021-11-22 05:00:00+00:00   -30.564756
  2021-11-23 05:00:00+00:00   -28.674456
  2021-11-24 05:00:00+00:00   -40.689673
  2021-11-26 05:00:00+00:00   -44.273328
  2021-11-29 05:00:00+00:00   -48.356454
  2021-11-30 05:00:00+00:00   -48.895431
  2021-12-01 05:00:00+00:00   -35.015747
  2021-12-02 05:00:00+00:00   -38.045467
  2021-12-03 05:00:00+00:00   -34.160543
  2021-12-06 05:00:00+00:00   -23.288434
  2021-12-07 05:00:00+00:00   -23.555871
  2021-12-08 05:00:00+00:00   -24.111916
  2021-12-09 05:00:00+00:00   -14.886631
  2021-12-10 05:00:00+00:00    -6.145913
  2021-12-13 05:00:00+00:00    -1.904596
  2021-12-14 05:00:00+00:00   -15.761727
  2021-12-15 05:00:00+00:00   -26.389908
  2021-12-16 05:00:00+00:00   -23.925770
  2021-12-17 05:00:00+00:00   -23.642744
  2021-12-20 05:00:00+00:00   -24.502519
  2021-12-21 05:00:00+00:00   -30.253494
  2021-12-22 05:00:00+00:00   -23.768528
  2021-12-23 05:00:00+00:00   -25.790481
  2021-12-27 05:00:00+00:00   -30.804045
  2021-12-28 05:00:00+00:00   -30.123752
  2021-12-29 05:00:00+00:00   -21.824880
  2021-12-30 05:00:00+00:00   -19.622059
  2021-12-31 05:00:00+00:00   -20.679608
  2022-01-03 05:00:00+00:00   -32.101724
  2022-01-04 05:00:00+00:00   -28.797668
  2022-01-05 05:00:00+00:00   -28.576406
  2022-01-06 05:00:00+00:00   -31.200723
  2022-01-07 05:00:00+00:00   -24.467466
  2022-01-10 05:00:00+00:00   -24.237466
  2022-01-11 05:00:00+00:00   -31.779001
  2022-01-12 05:00:00+00:00   -28.737635
  2022-01-13 05:00:00+00:00   -34.857397
  2022-01-14 05:00:00+00:00   -35.890798
  2022-01-18 05:00:00+00:00   -35.748688
  2022-01-19 05:00:00+00:00   -29.381189
  2022-01-20 05:00:00+00:00   -21.196915
  2022-01-21 05:00:00+00:00   -21.980713
  2022-01-24 05:00:00+00:00   -18.097681
  2022-01-25 05:00:00+00:00   -17.586289
  2022-01-26 05:00:00+00:00    -8.713625
  2022-01-27 05:00:00+00:00     7.019003
  2022-01-28 05:00:00+00:00    11.336545
  2022-01-31 05:00:00+00:00     0.055351
  2022-02-01 05:00:00+00:00    -6.096171
  2022-02-02 05:00:00+00:00   -10.688861
  2022-02-03 05:00:00+00:00   -18.734244
  2022-02-04 05:00:00+00:00   -19.514189
  2022-02-07 05:00:00+00:00   -24.612966
  2022-02-08 05:00:00+00:00   -28.089031
  2022-02-09 05:00:00+00:00   -28.618333
  2022-02-10 05:00:00+00:00   -26.446285
  2022-02-11 05:00:00+00:00   -14.221910
  2022-02-14 05:00:00+00:00   -15.955728
  2022-02-15 05:00:00+00:00   -21.674251
  2022-02-16 05:00:00+00:00   -16.770276
  2022-02-17 05:00:00+00:00   -17.273201
  2022-02-18 05:00:00+00:00   -22.341985
  2022-02-22 05:00:00+00:00   -25.380195
  2022-02-23 05:00:00+00:00   -23.615131
  2022-02-24 05:00:00+00:00   -19.846602
  2022-02-25 05:00:00+00:00   -24.197127
  2022-02-28 05:00:00+00:00   -26.260159
  2022-03-01 05:00:00+00:00   -15.321985
  2022-03-02 05:00:00+00:00   -16.997113
  2022-03-03 05:00:00+00:00   -11.477156
  2022-03-04 05:00:00+00:00   -11.989513
  2022-03-07 05:00:00+00:00   -14.454883
  2022-03-08 05:00:00+00:00   -21.524104
  2022-03-09 05:00:00+00:00   -17.451972
  2022-03-10 05:00:00+00:00   -13.229288
  2022-03-11 05:00:00+00:00   -15.377192
  2022-03-14 04:00:00+00:00   -15.837110
  2022-03-15 04:00:00+00:00   -16.129158
  2022-03-16 04:00:00+00:00   -18.275085
  2022-03-17 04:00:00+00:00   -11.726507
  2022-03-18 04:00:00+00:00    -9.267019
  2022-03-21 04:00:00+00:00   -14.359764
  2022-03-22 04:00:00+00:00    -7.688248
  2022-03-23 04:00:00+00:00   -10.921841
  2022-03-24 04:00:00+00:00   -16.583527
  2022-03-25 04:00:00+00:00   -15.667120
  2022-03-28 04:00:00+00:00    -9.532878
  2022-03-29 04:00:00+00:00    -9.469223
  2022-03-30 04:00:00+00:00    -4.787837
  2022-03-31 04:00:00+00:00     5.015302
  2022-04-01 04:00:00+00:00     7.912358
  2022-04-04 04:00:00+00:00     9.826088
  2022-04-05 04:00:00+00:00    11.501286
  2022-04-06 04:00:00+00:00     5.016264
  2022-04-07 04:00:00+00:00     6.808566
  2022-04-08 04:00:00+00:00     6.635342
  2022-04-11 04:00:00+00:00     0.566222
  2022-04-12 04:00:00+00:00     0.893714
  2022-04-13 04:00:00+00:00     2.351256
  2022-04-14 04:00:00+00:00     1.833796
  2022-04-18 04:00:00+00:00     1.234008
  2022-04-19 04:00:00+00:00     1.289965
  2022-04-20 04:00:00+00:00     6.871993
  2022-04-21 04:00:00+00:00     7.802012
  2022-04-22 04:00:00+00:00     3.679287
  2022-04-25 04:00:00+00:00     6.406685
  2022-04-26 04:00:00+00:00     4.500092
  2022-04-27 04:00:00+00:00    17.888582
  2022-04-28 04:00:00+00:00    16.948344
  2022-04-29 04:00:00+00:00    11.240666
  2022-05-02 04:00:00+00:00    11.477552
  2022-05-03 04:00:00+00:00     6.782942
  2022-05-04 04:00:00+00:00     2.100601
  2022-05-05 04:00:00+00:00    -1.904913
  2022-05-06 04:00:00+00:00    -6.809236
  2022-05-09 04:00:00+00:00    -3.004662
  2022-05-10 04:00:00+00:00    -1.767551
  2022-05-11 04:00:00+00:00    -9.458842
  2022-05-12 04:00:00+00:00   -13.322435
  2022-05-13 04:00:00+00:00   -20.077365
  2022-05-16 04:00:00+00:00   -18.329879
  2022-05-17 04:00:00+00:00   -25.798982
  2022-05-18 04:00:00+00:00   -28.919960
  2022-05-19 04:00:00+00:00   -30.466005
  2022-05-20 04:00:00+00:00   -26.119947
  2022-05-23 04:00:00+00:00   -20.469667
  2022-05-24 04:00:00+00:00   -15.423677
  2022-05-25 04:00:00+00:00   -14.839080
  2022-05-26 04:00:00+00:00   -20.938245
  2022-05-27 04:00:00+00:00   -19.052650
  2022-05-31 04:00:00+00:00   -19.801065
  2022-06-01 04:00:00+00:00   -18.256530
  2022-06-02 04:00:00+00:00   -27.549226
  2022-06-03 04:00:00+00:00   -28.550655
  2022-06-06 04:00:00+00:00   -28.810580
  2022-06-07 04:00:00+00:00   -24.485614
  2022-06-08 04:00:00+00:00   -21.323224
  2022-06-09 04:00:00+00:00   -22.125943
  2022-06-10 04:00:00+00:00   -27.741176
  2022-06-13 04:00:00+00:00   -26.303658
  2022-06-14 04:00:00+00:00   -24.073658
  2022-06-15 04:00:00+00:00   -20.393309
  2022-06-16 04:00:00+00:00   -15.917088
  2022-06-17 04:00:00+00:00   -12.491186
  2022-06-21 04:00:00+00:00    -9.850981
  2022-06-22 04:00:00+00:00   -10.398822
  2022-06-23 04:00:00+00:00    -2.617593
  2022-06-24 04:00:00+00:00    -1.003514
  2022-06-27 04:00:00+00:00    -2.383870
  2022-06-28 04:00:00+00:00    -2.433557
  2022-06-29 04:00:00+00:00     5.681996
  2022-06-30 04:00:00+00:00     4.614018
  2022-07-01 04:00:00+00:00    11.715110
  2022-07-05 04:00:00+00:00    12.607549
  2022-07-06 04:00:00+00:00    15.734454
  2022-07-07 04:00:00+00:00    11.786306
  2022-07-08 04:00:00+00:00    10.968608
  2022-07-11 04:00:00+00:00    11.548116
  2022-07-12 04:00:00+00:00     1.624953
  2022-07-13 04:00:00+00:00    -1.127642
  2022-07-14 04:00:00+00:00    -1.445920
  2022-07-15 04:00:00+00:00    -2.706364
  2022-07-18 04:00:00+00:00    -5.673632
  2022-07-19 04:00:00+00:00    -7.308760
  2022-07-20 04:00:00+00:00   -10.085324
  2022-07-21 04:00:00+00:00   -10.094900
  2022-07-22 04:00:00+00:00    -9.928555
  2022-07-25 04:00:00+00:00   -10.588336
  2022-07-26 04:00:00+00:00   -13.959765
  2022-07-27 04:00:00+00:00    -4.221369
  2022-07-28 04:00:00+00:00     0.573802
  2022-07-29 04:00:00+00:00     0.552710
  2022-08-01 04:00:00+00:00    -5.766941
  2022-08-02 04:00:00+00:00   -12.857384
  2022-08-03 04:00:00+00:00    -3.342630
  2022-08-04 04:00:00+00:00   -11.206686
  2022-08-05 04:00:00+00:00    -9.460348
  2022-08-08 04:00:00+00:00    -8.569474
  2022-08-09 04:00:00+00:00     0.449971
  2022-08-10 04:00:00+00:00     1.855566
  2022-08-11 04:00:00+00:00     1.160751
  2022-08-12 04:00:00+00:00     1.839515
  2022-08-15 04:00:00+00:00     3.119802
  2022-08-16 04:00:00+00:00     3.618511
  2022-08-17 04:00:00+00:00     5.227656
  2022-08-18 04:00:00+00:00     0.705560
  2022-08-19 04:00:00+00:00     3.662847
  2022-08-22 04:00:00+00:00     0.095668
  2022-08-23 04:00:00+00:00    -0.670446
  2022-08-24 04:00:00+00:00    -1.693397
  2022-08-25 04:00:00+00:00    -5.548525
  2022-08-26 04:00:00+00:00    -6.984756
  2022-08-29 04:00:00+00:00    -5.664600
  2022-08-30 04:00:00+00:00    -5.515960
  2022-08-31 04:00:00+00:00    -3.799259
  2022-09-01 04:00:00+00:00    -0.922197
  2022-09-02 04:00:00+00:00    -2.014417
  2022-09-06 04:00:00+00:00    -2.462396
  2022-09-07 04:00:00+00:00     0.994578
  2022-09-08 04:00:00+00:00    -3.501480
  2022-09-09 04:00:00+00:00    -1.710557
  2022-09-12 04:00:00+00:00     1.738152
  2022-09-13 04:00:00+00:00    -1.096201
  2022-09-14 04:00:00+00:00    -1.518865
  2022-09-15 04:00:00+00:00    -7.131235
  2022-09-16 04:00:00+00:00    -7.538141
  2022-09-19 04:00:00+00:00    -8.162171
  2022-09-20 04:00:00+00:00    -7.870149
  2022-09-21 04:00:00+00:00   -10.173599
  2022-09-22 04:00:00+00:00    -0.404871
  2022-09-23 04:00:00+00:00    -1.071770
  2022-09-26 04:00:00+00:00     1.037806
  2022-09-27 04:00:00+00:00    -1.354140
  2022-09-28 04:00:00+00:00     1.456645
  2022-09-29 04:00:00+00:00     4.444363
  2022-09-30 04:00:00+00:00     1.056453
  2022-10-03 04:00:00+00:00     4.623059
  2022-10-04 04:00:00+00:00     9.981468
  2022-10-05 04:00:00+00:00    10.239309
  2022-10-06 04:00:00+00:00     7.969166
  2022-10-07 04:00:00+00:00    10.041944
  2022-10-10 04:00:00+00:00     6.030939
  2022-10-11 04:00:00+00:00     2.470653
  2022-10-12 04:00:00+00:00     2.468781
  2022-10-13 04:00:00+00:00     9.264963
  2022-10-14 04:00:00+00:00     8.246847
  2022-10-17 04:00:00+00:00    14.077845
  2022-10-18 04:00:00+00:00    15.110004
  2022-10-19 04:00:00+00:00    14.162237
  2022-10-20 04:00:00+00:00    12.993098
  2022-10-21 04:00:00+00:00    17.331438
  2022-10-24 04:00:00+00:00    22.647914
  2022-10-25 04:00:00+00:00    21.753440
  2022-10-26 04:00:00+00:00     5.117333
  2022-10-27 04:00:00+00:00     2.303310
  2022-10-28 04:00:00+00:00     6.124301
  2022-10-31 04:00:00+00:00     5.414526
  2022-11-01 04:00:00+00:00     2.076111
  2022-11-02 04:00:00+00:00    -4.393309
  2022-11-03 04:00:00+00:00   -12.543172
  2022-11-04 04:00:00+00:00    -8.635412
  2022-11-07 05:00:00+00:00    -3.538438
  2022-11-08 05:00:00+00:00    -3.734988
  2022-11-09 05:00:00+00:00    -1.987919
  2022-11-10 05:00:00+00:00     3.195710
  2022-11-11 05:00:00+00:00     1.265260
  2022-11-14 05:00:00+00:00    -6.097336
  2022-11-15 05:00:00+00:00   -10.090586
  2022-11-16 05:00:00+00:00    -4.627548
  2022-11-17 05:00:00+00:00    -6.542301
  2022-11-18 05:00:00+00:00    -6.489494
  2022-11-21 05:00:00+00:00    -3.934597
  2022-11-22 05:00:00+00:00    -5.290149
  2022-11-23 05:00:00+00:00    -4.527205
  2022-11-25 05:00:00+00:00    -2.659214
  2022-11-28 05:00:00+00:00    -5.358989
  2022-11-29 05:00:00+00:00    -7.099781
  2022-11-30 05:00:00+00:00     1.121422
  2022-12-01 05:00:00+00:00     0.904516

In [51]:
#calculation z scor for formation period
from src.strategy.zscore import calculate_zscore
from src.strategy.signals import calculate_thresholds

formation_zscores = []

for pair in formation_spreads:

    zscore = calculate_zscore(pair[6])

    lower_threshold, upper_threshold = calculate_thresholds(zscore)

    formation_zscores.append(
        (
            pair[0],
            pair[1],
            pair[2],
            pair[3],
            pair[4],
            pair[5],
            pair[6],
            zscore,
            lower_threshold,
            upper_threshold
        )
    )
formation_zscores

[('AMD',
  'MSFT',
  np.float64(0.04959216212157262),
  np.float64(0.011520421568257217),
  np.float64(133.3845452264579),
  np.float64(1.553961517257702),
  timestamp
  2021-01-04 05:00:00+00:00   -59.125193
  2021-01-05 05:00:00+00:00   -59.645555
  2021-01-06 05:00:00+00:00   -61.503889
  2021-01-07 05:00:00+00:00   -62.969523
  2021-01-08 05:00:00+00:00   -60.738226
  2021-01-11 05:00:00+00:00   -67.017303
  2021-01-12 05:00:00+00:00   -66.632546
  2021-01-13 05:00:00+00:00   -59.667133
  2021-01-14 05:00:00+00:00   -61.448711
  2021-01-15 05:00:00+00:00   -57.809491
  2021-01-19 05:00:00+00:00   -55.946403
  2021-01-20 05:00:00+00:00   -46.958630
  2021-01-21 05:00:00+00:00   -50.648643
  2021-01-22 05:00:00+00:00   -51.626634
  2021-01-25 05:00:00+00:00   -50.128943
  2021-01-26 05:00:00+00:00   -48.230241
  2021-01-27 05:00:00+00:00   -38.538486
  2021-01-28 05:00:00+00:00   -30.457257
  2021-01-29 05:00:00+00:00   -34.505810
  2021-02-01 05:00:00+00:00   -29.954812
  2021-02-02 05:00:00+00:00   -31.959566
  2021-02-03 05:00:00+00:00   -26.962223
  2021-02-04 05:00:00+00:00   -27.874525
  2021-02-05 05:00:00+00:00   -27.777763
  2021-02-08 05:00:00+00:00   -33.055405
  2021-02-09 05:00:00+00:00   -30.885187
  2021-02-10 05:00:00+00:00   -34.072891
  2021-02-11 05:00:00+00:00   -32.884619
  2021-02-12 05:00:00+00:00   -34.109517
  2021-02-16 05:00:00+00:00   -31.809866
  2021-02-17 05:00:00+00:00   -28.947844
  2021-02-18 05:00:00+00:00   -27.337694
  2021-02-19 05:00:00+00:00   -31.618418
  2021-02-22 05:00:00+00:00   -31.536240
  2021-02-23 05:00:00+00:00   -31.797244
  2021-02-24 05:00:00+00:00   -33.935960
  2021-02-25 05:00:00+00:00   -32.472053
  2021-02-26 05:00:00+00:00   -32.329833
  2021-03-01 05:00:00+00:00   -30.691281
  2021-03-02 05:00:00+00:00   -30.249328
  2021-03-03 05:00:00+00:00   -31.477874
  2021-03-04 05:00:00+00:00   -27.475053
  2021-03-05 05:00:00+00:00   -23.801604
  2021-03-08 05:00:00+00:00   -20.925539
  2021-03-09 05:00:00+00:00   -21.637143
  2021-03-10 05:00:00+00:00   -21.427642
  2021-03-11 05:00:00+00:00   -22.482839
  2021-03-12 05:00:00+00:00   -23.583126
  2021-03-15 04:00:00+00:00   -26.776370
  2021-03-16 04:00:00+00:00   -24.264861
  2021-03-17 04:00:00+00:00   -24.748385
  2021-03-18 04:00:00+00:00   -24.060019
  2021-03-19 04:00:00+00:00   -25.890743
  2021-03-22 04:00:00+00:00   -22.177655
  2021-03-23 04:00:00+00:00   -17.604049
  2021-03-24 04:00:00+00:00   -16.771522
  2021-03-25 04:00:00+00:00   -19.487492
  2021-03-26 04:00:00+00:00   -17.196706
  2021-03-29 04:00:00+00:00   -18.017137
  2021-03-30 04:00:00+00:00   -19.635621
  2021-03-31 04:00:00+00:00   -19.600524
  2021-04-01 04:00:00+00:00   -17.045285
  2021-04-05 04:00:00+00:00   -10.853632
  2021-04-06 04:00:00+00:00   -12.079171
  2021-04-07 04:00:00+00:00   -11.220182
  2021-04-08 04:00:00+00:00    -9.657238
  2021-04-09 04:00:00+00:00    -6.140400
  2021-04-12 04:00:00+00:00     0.415159
  2021-04-13 04:00:00+00:00     0.493281
  2021-04-14 04:00:00+00:00     0.141778
  2021-04-15 04:00:00+00:00    -2.878891
  2021-04-16 04:00:00+00:00    -0.302484
  2021-04-19 04:00:00+00:00    -0.686364
  2021-04-20 04:00:00+00:00     1.692925
  2021-04-21 04:00:00+00:00     0.376655
  2021-04-22 04:00:00+00:00     0.929257
  2021-04-23 04:00:00+00:00    -0.840400
  2021-04-26 04:00:00+00:00    -4.558398
  2021-04-27 04:00:00+00:00    -3.827606
  2021-04-28 04:00:00+00:00    -9.388392
  2021-04-29 04:00:00+00:00   -11.267456
  2021-04-30 04:00:00+00:00    -8.038884
  2021-05-03 04:00:00+00:00    -3.588222
  2021-05-04 04:00:00+00:00    -7.751460
  2021-05-05 04:00:00+00:00    -7.859370
  2021-05-06 04:00:00+00:00    -4.692608
  2021-05-07 04:00:00+00:00    -3.392252
  2021-05-10 04:00:00+00:00    -4.290081
  2021-05-11 04:00:00+00:00    -6.545409
  2021-05-12 04:00:00+00:00   -10.372233
  2021-05-13 04:00:00+00:00    -3.933593
  2021-05-14 04:00:00+00:00    -1.144535
  2021-05-17 04:00:00+00:00    -4.207772
  2021-05-18 04:00:00+00:00    -5.981441
  2021-05-19 04:00:00+00:00    -8.723032
  2021-05-20 04:00:00+00:00    -8.206781
  2021-05-21 04:00:00+00:00    -8.133756
  2021-05-24 04:00:00+00:00    -2.943325
  2021-05-25 04:00:00+00:00    -2.655989
  2021-05-26 04:00:00+00:00    -3.631890
  2021-05-27 04:00:00+00:00    -5.936207
  2021-05-28 04:00:00+00:00    -8.145784
  2021-06-01 04:00:00+00:00   -11.560175
  2021-06-02 04:00:00+00:00   -13.462771
  2021-06-03 04:00:00+00:00   -12.426576
  2021-06-04 04:00:00+00:00    -9.366726
  2021-06-07 04:00:00+00:00    -5.989315
  2021-06-08 04:00:00+00:00    -6.514492
  2021-06-09 04:00:00+00:00    -4.049308
  2021-06-10 04:00:00+00:00    -2.885647
  2021-06-11 04:00:00+00:00    -1.847156
  2021-06-14 04:00:00+00:00    -0.220107
  2021-06-15 04:00:00+00:00    -0.071829
  2021-06-16 04:00:00+00:00    -0.492402
  2021-06-17 04:00:00+00:00    -3.887531
  2021-06-18 04:00:00+00:00    -5.497388
  2021-06-21 04:00:00+00:00     0.903773
  2021-06-22 04:00:00+00:00     2.245351
  2021-06-23 04:00:00+00:00     1.637400
  2021-06-24 04:00:00+00:00    -0.490632
  2021-06-25 04:00:00+00:00    -1.414730
  2021-06-28 04:00:00+00:00     0.016486
  2021-06-29 04:00:00+00:00    -1.095180
  2021-06-30 04:00:00+00:00    -8.448151
  2021-07-01 04:00:00+00:00    -6.784694
  2021-07-02 04:00:00+00:00    -2.894701
  2021-07-06 04:00:00+00:00    -2.527290
  2021-07-07 04:00:00+00:00     5.849779
  2021-07-08 04:00:00+00:00     4.582948
  2021-07-09 04:00:00+00:00     3.300353
  2021-07-12 04:00:00+00:00     2.820209
  2021-07-13 04:00:00+00:00     7.334888
  2021-07-14 04:00:00+00:00    10.745182
  2021-07-15 04:00:00+00:00    12.559580
  2021-07-16 04:00:00+00:00    13.895700
  2021-07-19 04:00:00+00:00     9.083467
  2021-07-20 04:00:00+00:00    10.569867
  2021-07-21 04:00:00+00:00     9.075756
  2021-07-22 04:00:00+00:00    11.018625
  2021-07-23 04:00:00+00:00    13.087901
  2021-07-26 04:00:00+00:00    12.980708
  2021-07-27 04:00:00+00:00    11.698338
  2021-07-28 04:00:00+00:00     0.656003
  2021-07-29 04:00:00+00:00    -6.864883
  2021-07-30 04:00:00+00:00   -13.489719
  2021-08-02 04:00:00+00:00   -17.371385
  2021-08-03 04:00:00+00:00   -21.178454
  2021-08-04 04:00:00+00:00   -31.438555
  2021-08-05 04:00:00+00:00   -18.452122
  2021-08-06 04:00:00+00:00   -15.031248
  2021-08-09 04:00:00+00:00   -12.229725
  2021-08-10 04:00:00+00:00   -12.410368
  2021-08-11 04:00:00+00:00   -13.765121
  2021-08-12 04:00:00+00:00    -9.071447
  2021-08-13 04:00:00+00:00   -12.324991
  2021-08-16 04:00:00+00:00    -5.804329
  2021-08-17 04:00:00+00:00    -7.448646
  2021-08-18 04:00:00+00:00    -3.396325
  2021-08-19 04:00:00+00:00     2.239645
  2021-08-20 04:00:00+00:00     8.353382
  2021-08-23 04:00:00+00:00     2.241061
  2021-08-24 04:00:00+00:00     1.951497
  2021-08-25 04:00:00+00:00     0.331422
  2021-08-26 04:00:00+00:00    -0.987997
  2021-08-27 04:00:00+00:00    -6.775858
  2021-08-30 04:00:00+00:00    -2.781541
  2021-08-31 04:00:00+00:00    -3.559164
  2021-09-01 04:00:00+00:00    -2.474773
  2021-09-02 04:00:00+00:00    -1.927143
  2021-09-03 04:00:00+00:00    -3.055995
  2021-09-07 04:00:00+00:00    -2.819445
  2021-09-08 04:00:00+00:00     1.841360
  2021-09-09 04:00:00+00:00    -1.087560
  2021-09-10 04:00:00+00:00    -1.151297
  2021-09-13 04:00:00+00:00     0.750288
  2021-09-14 04:00:00+00:00     2.105104
  2021-09-15 04:00:00+00:00     7.337119
  2021-09-16 04:00:00+00:00     6.773662
  2021-09-17 04:00:00+00:00     5.059932
  2021-09-20 04:00:00+00:00     3.110663
  2021-09-21 04:00:00+00:00     1.637132
  2021-09-22 04:00:00+00:00     2.992952
  2021-09-23 04:00:00+00:00     1.222440
  2021-09-24 04:00:00+00:00     1.556326
  2021-09-27 04:00:00+00:00    -7.291023
  2021-09-28 04:00:00+00:00    -7.622718
  2021-09-29 04:00:00+00:00    -5.324583
  2021-09-30 04:00:00+00:00   -11.367185
  2021-10-01 04:00:00+00:00    -3.487903
  2021-10-04 04:00:00+00:00    -6.199044
  2021-10-05 04:00:00+00:00    -2.833367
  2021-10-06 04:00:00+00:00    -1.327117
  2021-10-07 04:00:00+00:00    -3.953749
  2021-10-08 04:00:00+00:00    -1.793742
  2021-10-11 04:00:00+00:00    -1.823237
  2021-10-12 04:00:00+00:00    -3.732663
  2021-10-13 04:00:00+00:00    -6.704984
  2021-10-14 04:00:00+00:00    -4.662696
  2021-10-15 04:00:00+00:00    -3.404711
  2021-10-18 04:00:00+00:00    -7.022285
  2021-10-19 04:00:00+00:00    -5.926889
  2021-10-20 04:00:00+00:00    -6.840126
  2021-10-21 04:00:00+00:00    -8.058773
  2021-10-22 04:00:00+00:00   -10.420214
  2021-10-25 04:00:00+00:00   -15.397276
  2021-10-26 04:00:00+00:00   -14.303035
  2021-10-27 04:00:00+00:00    -0.232960
  2021-10-28 04:00:00+00:00     2.687477
  2021-10-29 04:00:00+00:00    11.402662
  2021-11-01 04:00:00+00:00     1.382854
  2021-11-02 04:00:00+00:00     1.413346
  2021-11-03 04:00:00+00:00    -2.223142
  2021-11-04 04:00:00+00:00   -10.614254
  2021-11-05 04:00:00+00:00    -9.191658
  2021-11-08 05:00:00+00:00   -29.737407
  2021-11-09 05:00:00+00:00   -28.850494
  2021-11-10 05:00:00+00:00   -19.937143
  2021-11-11 05:00:00+00:00   -27.848466
  2021-11-12 05:00:00+00:00   -26.479914
  2021-11-15 05:00:00+00:00   -24.954368
  2021-11-16 05:00:00+00:00   -30.775979
  2021-11-17 05:00:00+00:00   -29.441081
  2021-11-18 05:00:00+00:00   -33.009660
  2021-11-19 05:00:00+00:00   -31.775705
  2021-11-22 05:00:00+00:00   -30.564756
  2021-11-23 05:00:00+00:00   -28.674456
  2021-11-24 05:00:00+00:00   -40.689673
  2021-11-26 05:00:00+00:00   -44.273328
  2021-11-29 05:00:00+00:00   -48.356454
  2021-11-30 05:00:00+00:00   -48.895431
  2021-12-01 05:00:00+00:00   -35.015747
  2021-12-02 05:00:00+00:00   -38.045467
  2021-12-03 05:00:00+00:00   -34.160543
  2021-12-06 05:00:00+00:00   -23.288434
  2021-12-07 05:00:00+00:00   -23.555871
  2021-12-08 05:00:00+00:00   -24.111916
  2021-12-09 05:00:00+00:00   -14.886631
  2021-12-10 05:00:00+00:00    -6.145913
  2021-12-13 05:00:00+00:00    -1.904596
  2021-12-14 05:00:00+00:00   -15.761727
  2021-12-15 05:00:00+00:00   -26.389908
  2021-12-16 05:00:00+00:00   -23.925770
  2021-12-17 05:00:00+00:00   -23.642744
  2021-12-20 05:00:00+00:00   -24.502519
  2021-12-21 05:00:00+00:00   -30.253494
  2021-12-22 05:00:00+00:00   -23.768528
  2021-12-23 05:00:00+00:00   -25.790481
  2021-12-27 05:00:00+00:00   -30.804045
  2021-12-28 05:00:00+00:00   -30.123752
  2021-12-29 05:00:00+00:00   -21.824880
  2021-12-30 05:00:00+00:00   -19.622059
  2021-12-31 05:00:00+00:00   -20.679608
  2022-01-03 05:00:00+00:00   -32.101724
  2022-01-04 05:00:00+00:00   -28.797668
  2022-01-05 05:00:00+00:00   -28.576406
  2022-01-06 05:00:00+00:00   -31.200723
  2022-01-07 05:00:00+00:00   -24.467466
  2022-01-10 05:00:00+00:00   -24.237466
  2022-01-11 05:00:00+00:00   -31.779001
  2022-01-12 05:00:00+00:00   -28.737635
  2022-01-13 05:00:00+00:00   -34.857397
  2022-01-14 05:00:00+00:00   -35.890798
  2022-01-18 05:00:00+00:00   -35.748688
  2022-01-19 05:00:00+00:00   -29.381189
  2022-01-20 05:00:00+00:00   -21.196915
  2022-01-21 05:00:00+00:00   -21.980713
  2022-01-24 05:00:00+00:00   -18.097681
  2022-01-25 05:00:00+00:00   -17.586289
  2022-01-26 05:00:00+00:00    -8.713625
  2022-01-27 05:00:00+00:00     7.019003
  2022-01-28 05:00:00+00:00    11.336545
  2022-01-31 05:00:00+00:00     0.055351
  2022-02-01 05:00:00+00:00    -6.096171
  2022-02-02 05:00:00+00:00   -10.688861
  2022-02-03 05:00:00+00:00   -18.734244
  2022-02-04 05:00:00+00:00   -19.514189
  2022-02-07 05:00:00+00:00   -24.612966
  2022-02-08 05:00:00+00:00   -28.089031
  2022-02-09 05:00:00+00:00   -28.618333
  2022-02-10 05:00:00+00:00   -26.446285
  2022-02-11 05:00:00+00:00   -14.221910
  2022-02-14 05:00:00+00:00   -15.955728
  2022-02-15 05:00:00+00:00   -21.674251
  2022-02-16 05:00:00+00:00   -16.770276
  2022-02-17 05:00:00+00:00   -17.273201
  2022-02-18 05:00:00+00:00   -22.341985
  2022-02-22 05:00:00+00:00   -25.380195
  2022-02-23 05:00:00+00:00   -23.615131
  2022-02-24 05:00:00+00:00   -19.846602
  2022-02-25 05:00:00+00:00   -24.197127
  2022-02-28 05:00:00+00:00   -26.260159
  2022-03-01 05:00:00+00:00   -15.321985
  2022-03-02 05:00:00+00:00   -16.997113
  2022-03-03 05:00:00+00:00   -11.477156
  2022-03-04 05:00:00+00:00   -11.989513
  2022-03-07 05:00:00+00:00   -14.454883
  2022-03-08 05:00:00+00:00   -21.524104
  2022-03-09 05:00:00+00:00   -17.451972
  2022-03-10 05:00:00+00:00   -13.229288
  2022-03-11 05:00:00+00:00   -15.377192
  2022-03-14 04:00:00+00:00   -15.837110
  2022-03-15 04:00:00+00:00   -16.129158
  2022-03-16 04:00:00+00:00   -18.275085
  2022-03-17 04:00:00+00:00   -11.726507
  2022-03-18 04:00:00+00:00    -9.267019
  2022-03-21 04:00:00+00:00   -14.359764
  2022-03-22 04:00:00+00:00    -7.688248
  2022-03-23 04:00:00+00:00   -10.921841
  2022-03-24 04:00:00+00:00   -16.583527
  2022-03-25 04:00:00+00:00   -15.667120
  2022-03-28 04:00:00+00:00    -9.532878
  2022-03-29 04:00:00+00:00    -9.469223
  2022-03-30 04:00:00+00:00    -4.787837
  2022-03-31 04:00:00+00:00     5.015302
  2022-04-01 04:00:00+00:00     7.912358
  2022-04-04 04:00:00+00:00     9.826088
  2022-04-05 04:00:00+00:00    11.501286
  2022-04-06 04:00:00+00:00     5.016264
  2022-04-07 04:00:00+00:00     6.808566
  2022-04-08 04:00:00+00:00     6.635342
  2022-04-11 04:00:00+00:00     0.566222
  2022-04-12 04:00:00+00:00     0.893714
  2022-04-13 04:00:00+00:00     2.351256
  2022-04-14 04:00:00+00:00     1.833796
  2022-04-18 04:00:00+00:00     1.234008
  2022-04-19 04:00:00+00:00     1.289965
  2022-04-20 04:00:00+00:00     6.871993
  2022-04-21 04:00:00+00:00     7.802012
  2022-04-22 04:00:00+00:00     3.679287
  2022-04-25 04:00:00+00:00     6.406685
  2022-04-26 04:00:00+00:00     4.500092
  2022-04-27 04:00:00+00:00    17.888582
  2022-04-28 04:00:00+00:00    16.948344
  2022-04-29 04:00:00+00:00    11.240666
  2022-05-02 04:00:00+00:00    11.477552
  2022-05-03 04:00:00+00:00     6.782942
  2022-05-04 04:00:00+00:00     2.100601
  2022-05-05 04:00:00+00:00    -1.904913
  2022-05-06 04:00:00+00:00    -6.809236
  2022-05-09 04:00:00+00:00    -3.004662
  2022-05-10 04:00:00+00:00    -1.767551
  2022-05-11 04:00:00+00:00    -9.458842
  2022-05-12 04:00:00+00:00   -13.322435
  2022-05-13 04:00:00+00:00   -20.077365
  2022-05-16 04:00:00+00:00   -18.329879
  2022-05-17 04:00:00+00:00   -25.798982
  2022-05-18 04:00:00+00:00   -28.919960
  2022-05-19 04:00:00+00:00   -30.466005
  2022-05-20 04:00:00+00:00   -26.119947
  2022-05-23 04:00:00+00:00   -20.469667
  2022-05-24 04:00:00+00:00   -15.423677
  2022-05-25 04:00:00+00:00   -14.839080
  2022-05-26 04:00:00+00:00   -20.938245
  2022-05-27 04:00:00+00:00   -19.052650
  2022-05-31 04:00:00+00:00   -19.801065
  2022-06-01 04:00:00+00:00   -18.256530
  2022-06-02 04:00:00+00:00   -27.549226
  2022-06-03 04:00:00+00:00   -28.550655
  2022-06-06 04:00:00+00:00   -28.810580
  2022-06-07 04:00:00+00:00   -24.485614
  2022-06-08 04:00:00+00:00   -21.323224
  2022-06-09 04:00:00+00:00   -22.125943
  2022-06-10 04:00:00+00:00   -27.741176
  2022-06-13 04:00:00+00:00   -26.303658
  2022-06-14 04:00:00+00:00   -24.073658
  2022-06-15 04:00:00+00:00   -20.393309
  2022-06-16 04:00:00+00:00   -15.917088
  2022-06-17 04:00:00+00:00   -12.491186
  2022-06-21 04:00:00+00:00    -9.850981
  2022-06-22 04:00:00+00:00   -10.398822
  2022-06-23 04:00:00+00:00    -2.617593
  2022-06-24 04:00:00+00:00    -1.003514
  2022-06-27 04:00:00+00:00    -2.383870
  2022-06-28 04:00:00+00:00    -2.433557
  2022-06-29 04:00:00+00:00     5.681996
  2022-06-30 04:00:00+00:00     4.614018
  2022-07-01 04:00:00+00:00    11.715110
  2022-07-05 04:00:00+00:00    12.607549
  2022-07-06 04:00:00+00:00    15.734454
  2022-07-07 04:00:00+00:00    11.786306
  2022-07-08 04:00:00+00:00    10.968608
  2022-07-11 04:00:00+00:00    11.548116
  2022-07-12 04:00:00+00:00     1.624953
  2022-07-13 04:00:00+00:00    -1.127642
  2022-07-14 04:00:00+00:00    -1.445920
  2022-07-15 04:00:00+00:00    -2.706364
  2022-07-18 04:00:00+00:00    -5.673632
  2022-07-19 04:00:00+00:00    -7.308760
  2022-07-20 04:00:00+00:00   -10.085324
  2022-07-21 04:00:00+00:00   -10.094900
  2022-07-22 04:00:00+00:00    -9.928555
  2022-07-25 04:00:00+00:00   -10.588336
  2022-07-26 04:00:00+00:00   -13.959765
  2022-07-27 04:00:00+00:00    -4.221369
  2022-07-28 04:00:00+00:00     0.573802
  2022-07-29 04:00:00+00:00     0.552710
  2022-08-01 04:00:00+00:00    -5.766941
  2022-08-02 04:00:00+00:00   -12.857384
  2022-08-03 04:00:00+00:00    -3.342630
  2022-08-04 04:00:00+00:00   -11.206686
  2022-08-05 04:00:00+00:00    -9.460348
  2022-08-08 04:00:00+00:00    -8.569474
  2022-08-09 04:00:00+00:00     0.449971
  2022-08-10 04:00:00+00:00     1.855566
  2022-08-11 04:00:00+00:00     1.160751
  2022-08-12 04:00:00+00:00     1.839515
  2022-08-15 04:00:00+00:00     3.119802
  2022-08-16 04:00:00+00:00     3.618511
  2022-08-17 04:00:00+00:00     5.227656
  2022-08-18 04:00:00+00:00     0.705560
  2022-08-19 04:00:00+00:00     3.662847
  2022-08-22 04:00:00+00:00     0.095668
  2022-08-23 04:00:00+00:00    -0.670446
  2022-08-24 04:00:00+00:00    -1.693397
  2022-08-25 04:00:00+00:00    -5.548525
  2022-08-26 04:00:00+00:00    -6.984756
  2022-08-29 04:00:00+00:00    -5.664600
  2022-08-30 04:00:00+00:00    -5.515960
  2022-08-31 04:00:00+00:00    -3.799259
  2022-09-01 04:00:00+00:00    -0.922197
  2022-09-02 04:00:00+00:00    -2.014417
  2022-09-06 04:00:00+00:00    -2.462396
  2022-09-07 04:00:00+00:00     0.994578
  2022-09-08 04:00:00+00:00    -3.501480
  2022-09-09 04:00:00+00:00    -1.710557
  2022-09-12 04:00:00+00:00     1.738152
  2022-09-13 04:00:00+00:00    -1.096201
  2022-09-14 04:00:00+00:00    -1.518865
  2022-09-15 04:00:00+00:00    -7.131235
  2022-09-16 04:00:00+00:00    -7.538141
  2022-09-19 04:00:00+00:00    -8.162171
  2022-09-20 04:00:00+00:00    -7.870149
  2022-09-21 04:00:00+00:00   -10.173599
  2022-09-22 04:00:00+00:00    -0.404871
  2022-09-23 04:00:00+00:00    -1.071770
  2022-09-26 04:00:00+00:00     1.037806
  2022-09-27 04:00:00+00:00    -1.354140
  2022-09-28 04:00:00+00:00     1.456645
  2022-09-29 04:00:00+00:00     4.444363
  2022-09-30 04:00:00+00:00     1.056453
  2022-10-03 04:00:00+00:00     4.623059
  2022-10-04 04:00:00+00:00     9.981468
  2022-10-05 04:00:00+00:00    10.239309
  2022-10-06 04:00:00+00:00     7.969166
  2022-10-07 04:00:00+00:00    10.041944
  2022-10-10 04:00:00+00:00     6.030939
  2022-10-11 04:00:00+00:00     2.470653
  2022-10-12 04:00:00+00:00     2.468781
  2022-10-13 04:00:00+00:00     9.264963
  2022-10-14 04:00:00+00:00     8.246847
  2022-10-17 04:00:00+00:00    14.077845
  2022-10-18 04:00:00+00:00    15.110004
  2022-10-19 04:00:00+00:00    14.162237
  2022-10-20 04:00:00+00:00    12.993098
  2022-10-21 04:00:00+00:00    17.331438
  2022-10-24 04:00:00+00:00    22.647914
  2022-10-25 04:00:00+00:00    21.753440
  2022-10-26 04:00:00+00:00     5.117333
  2022-10-27 04:00:00+00:00     2.303310
  2022-10-28 04:00:00+00:00     6.124301
  2022-10-31 04:00:00+00:00     5.414526
  2022-11-01 04:00:00+00:00     2.076111
  2022-11-02 04:00:00+00:00    -4.393309
  2022-11-03 04:00:00+00:00   -12.543172
  2022-11-04 04:00:00+00:00    -8.635412
  2022-11-07 05:00:00+00:00    -3.538438
  2022-11-08 05:00:00+00:00    -3.734988
  2022-11-09 05:00:00+00:00    -1.987919
  2022-11-10 05:00:00+00:00     3.195710
  2022-11-11 05:00:00+00:00     1.265260
  2022-11-14 05:00:00+00:00    -6.097336
  2022-11-15 05:00:00+00:00   -10.090586
  2022-11-16 05:00:00+00:00    -4.627548
  2022-11-17 05:00:00+00:00    -6.542301
  2022-11-18 05:00:00+00:00    -6.489494
  2022-11-21 05:00:00+00:00    -3.934597
  2022-11-22 05:00:00+00:00    -5.290149
  2022-11-23 05:00:00+00:00    -4.527205
  2022-11-25 05:00:00+00:00    -2.659214
  2022-11-28 05:00:00+00:00    -5.358989
  2022-11-29 05:00:00+00:00    -7.099781
  2022-11-30 05:00:00+00:00     1.121422
  2022-12-01 05:00:00+00:00     0.904516

In [52]:
#to calculate trading period spread using formation period alpha beta
from src.pairs.spread import calculate_spread

trading_spreads = []

for pair in formation_zscores:

    spread = calculate_spread(
        trading_data,
        pair,
        pair[4],   # alpha from formation
        pair[5]    # beta from formation
    )

    trading_spreads.append(
        (
            pair[0],
            pair[1],
            pair[2],
            pair[3],
            pair[4],
            pair[5],
            pair[6],
            pair[7],
            pair[8],
            pair[9],
            spread
        )
    )
trading_spreads

[('AMD',
  'MSFT',
  np.float64(0.04959216212157262),
  np.float64(0.011520421568257217),
  np.float64(133.3845452264579),
  np.float64(1.553961517257702),
  timestamp
  2021-01-04 05:00:00+00:00   -59.125193
  2021-01-05 05:00:00+00:00   -59.645555
  2021-01-06 05:00:00+00:00   -61.503889
  2021-01-07 05:00:00+00:00   -62.969523
  2021-01-08 05:00:00+00:00   -60.738226
  2021-01-11 05:00:00+00:00   -67.017303
  2021-01-12 05:00:00+00:00   -66.632546
  2021-01-13 05:00:00+00:00   -59.667133
  2021-01-14 05:00:00+00:00   -61.448711
  2021-01-15 05:00:00+00:00   -57.809491
  2021-01-19 05:00:00+00:00   -55.946403
  2021-01-20 05:00:00+00:00   -46.958630
  2021-01-21 05:00:00+00:00   -50.648643
  2021-01-22 05:00:00+00:00   -51.626634
  2021-01-25 05:00:00+00:00   -50.128943
  2021-01-26 05:00:00+00:00   -48.230241
  2021-01-27 05:00:00+00:00   -38.538486
  2021-01-28 05:00:00+00:00   -30.457257
  2021-01-29 05:00:00+00:00   -34.505810
  2021-02-01 05:00:00+00:00   -29.954812
  2021-02-02 05:00:00+00:00   -31.959566
  2021-02-03 05:00:00+00:00   -26.962223
  2021-02-04 05:00:00+00:00   -27.874525
  2021-02-05 05:00:00+00:00   -27.777763
  2021-02-08 05:00:00+00:00   -33.055405
  2021-02-09 05:00:00+00:00   -30.885187
  2021-02-10 05:00:00+00:00   -34.072891
  2021-02-11 05:00:00+00:00   -32.884619
  2021-02-12 05:00:00+00:00   -34.109517
  2021-02-16 05:00:00+00:00   -31.809866
  2021-02-17 05:00:00+00:00   -28.947844
  2021-02-18 05:00:00+00:00   -27.337694
  2021-02-19 05:00:00+00:00   -31.618418
  2021-02-22 05:00:00+00:00   -31.536240
  2021-02-23 05:00:00+00:00   -31.797244
  2021-02-24 05:00:00+00:00   -33.935960
  2021-02-25 05:00:00+00:00   -32.472053
  2021-02-26 05:00:00+00:00   -32.329833
  2021-03-01 05:00:00+00:00   -30.691281
  2021-03-02 05:00:00+00:00   -30.249328
  2021-03-03 05:00:00+00:00   -31.477874
  2021-03-04 05:00:00+00:00   -27.475053
  2021-03-05 05:00:00+00:00   -23.801604
  2021-03-08 05:00:00+00:00   -20.925539
  2021-03-09 05:00:00+00:00   -21.637143
  2021-03-10 05:00:00+00:00   -21.427642
  2021-03-11 05:00:00+00:00   -22.482839
  2021-03-12 05:00:00+00:00   -23.583126
  2021-03-15 04:00:00+00:00   -26.776370
  2021-03-16 04:00:00+00:00   -24.264861
  2021-03-17 04:00:00+00:00   -24.748385
  2021-03-18 04:00:00+00:00   -24.060019
  2021-03-19 04:00:00+00:00   -25.890743
  2021-03-22 04:00:00+00:00   -22.177655
  2021-03-23 04:00:00+00:00   -17.604049
  2021-03-24 04:00:00+00:00   -16.771522
  2021-03-25 04:00:00+00:00   -19.487492
  2021-03-26 04:00:00+00:00   -17.196706
  2021-03-29 04:00:00+00:00   -18.017137
  2021-03-30 04:00:00+00:00   -19.635621
  2021-03-31 04:00:00+00:00   -19.600524
  2021-04-01 04:00:00+00:00   -17.045285
  2021-04-05 04:00:00+00:00   -10.853632
  2021-04-06 04:00:00+00:00   -12.079171
  2021-04-07 04:00:00+00:00   -11.220182
  2021-04-08 04:00:00+00:00    -9.657238
  2021-04-09 04:00:00+00:00    -6.140400
  2021-04-12 04:00:00+00:00     0.415159
  2021-04-13 04:00:00+00:00     0.493281
  2021-04-14 04:00:00+00:00     0.141778
  2021-04-15 04:00:00+00:00    -2.878891
  2021-04-16 04:00:00+00:00    -0.302484
  2021-04-19 04:00:00+00:00    -0.686364
  2021-04-20 04:00:00+00:00     1.692925
  2021-04-21 04:00:00+00:00     0.376655
  2021-04-22 04:00:00+00:00     0.929257
  2021-04-23 04:00:00+00:00    -0.840400
  2021-04-26 04:00:00+00:00    -4.558398
  2021-04-27 04:00:00+00:00    -3.827606
  2021-04-28 04:00:00+00:00    -9.388392
  2021-04-29 04:00:00+00:00   -11.267456
  2021-04-30 04:00:00+00:00    -8.038884
  2021-05-03 04:00:00+00:00    -3.588222
  2021-05-04 04:00:00+00:00    -7.751460
  2021-05-05 04:00:00+00:00    -7.859370
  2021-05-06 04:00:00+00:00    -4.692608
  2021-05-07 04:00:00+00:00    -3.392252
  2021-05-10 04:00:00+00:00    -4.290081
  2021-05-11 04:00:00+00:00    -6.545409
  2021-05-12 04:00:00+00:00   -10.372233
  2021-05-13 04:00:00+00:00    -3.933593
  2021-05-14 04:00:00+00:00    -1.144535
  2021-05-17 04:00:00+00:00    -4.207772
  2021-05-18 04:00:00+00:00    -5.981441
  2021-05-19 04:00:00+00:00    -8.723032
  2021-05-20 04:00:00+00:00    -8.206781
  2021-05-21 04:00:00+00:00    -8.133756
  2021-05-24 04:00:00+00:00    -2.943325
  2021-05-25 04:00:00+00:00    -2.655989
  2021-05-26 04:00:00+00:00    -3.631890
  2021-05-27 04:00:00+00:00    -5.936207
  2021-05-28 04:00:00+00:00    -8.145784
  2021-06-01 04:00:00+00:00   -11.560175
  2021-06-02 04:00:00+00:00   -13.462771
  2021-06-03 04:00:00+00:00   -12.426576
  2021-06-04 04:00:00+00:00    -9.366726
  2021-06-07 04:00:00+00:00    -5.989315
  2021-06-08 04:00:00+00:00    -6.514492
  2021-06-09 04:00:00+00:00    -4.049308
  2021-06-10 04:00:00+00:00    -2.885647
  2021-06-11 04:00:00+00:00    -1.847156
  2021-06-14 04:00:00+00:00    -0.220107
  2021-06-15 04:00:00+00:00    -0.071829
  2021-06-16 04:00:00+00:00    -0.492402
  2021-06-17 04:00:00+00:00    -3.887531
  2021-06-18 04:00:00+00:00    -5.497388
  2021-06-21 04:00:00+00:00     0.903773
  2021-06-22 04:00:00+00:00     2.245351
  2021-06-23 04:00:00+00:00     1.637400
  2021-06-24 04:00:00+00:00    -0.490632
  2021-06-25 04:00:00+00:00    -1.414730
  2021-06-28 04:00:00+00:00     0.016486
  2021-06-29 04:00:00+00:00    -1.095180
  2021-06-30 04:00:00+00:00    -8.448151
  2021-07-01 04:00:00+00:00    -6.784694
  2021-07-02 04:00:00+00:00    -2.894701
  2021-07-06 04:00:00+00:00    -2.527290
  2021-07-07 04:00:00+00:00     5.849779
  2021-07-08 04:00:00+00:00     4.582948
  2021-07-09 04:00:00+00:00     3.300353
  2021-07-12 04:00:00+00:00     2.820209
  2021-07-13 04:00:00+00:00     7.334888
  2021-07-14 04:00:00+00:00    10.745182
  2021-07-15 04:00:00+00:00    12.559580
  2021-07-16 04:00:00+00:00    13.895700
  2021-07-19 04:00:00+00:00     9.083467
  2021-07-20 04:00:00+00:00    10.569867
  2021-07-21 04:00:00+00:00     9.075756
  2021-07-22 04:00:00+00:00    11.018625
  2021-07-23 04:00:00+00:00    13.087901
  2021-07-26 04:00:00+00:00    12.980708
  2021-07-27 04:00:00+00:00    11.698338
  2021-07-28 04:00:00+00:00     0.656003
  2021-07-29 04:00:00+00:00    -6.864883
  2021-07-30 04:00:00+00:00   -13.489719
  2021-08-02 04:00:00+00:00   -17.371385
  2021-08-03 04:00:00+00:00   -21.178454
  2021-08-04 04:00:00+00:00   -31.438555
  2021-08-05 04:00:00+00:00   -18.452122
  2021-08-06 04:00:00+00:00   -15.031248
  2021-08-09 04:00:00+00:00   -12.229725
  2021-08-10 04:00:00+00:00   -12.410368
  2021-08-11 04:00:00+00:00   -13.765121
  2021-08-12 04:00:00+00:00    -9.071447
  2021-08-13 04:00:00+00:00   -12.324991
  2021-08-16 04:00:00+00:00    -5.804329
  2021-08-17 04:00:00+00:00    -7.448646
  2021-08-18 04:00:00+00:00    -3.396325
  2021-08-19 04:00:00+00:00     2.239645
  2021-08-20 04:00:00+00:00     8.353382
  2021-08-23 04:00:00+00:00     2.241061
  2021-08-24 04:00:00+00:00     1.951497
  2021-08-25 04:00:00+00:00     0.331422
  2021-08-26 04:00:00+00:00    -0.987997
  2021-08-27 04:00:00+00:00    -6.775858
  2021-08-30 04:00:00+00:00    -2.781541
  2021-08-31 04:00:00+00:00    -3.559164
  2021-09-01 04:00:00+00:00    -2.474773
  2021-09-02 04:00:00+00:00    -1.927143
  2021-09-03 04:00:00+00:00    -3.055995
  2021-09-07 04:00:00+00:00    -2.819445
  2021-09-08 04:00:00+00:00     1.841360
  2021-09-09 04:00:00+00:00    -1.087560
  2021-09-10 04:00:00+00:00    -1.151297
  2021-09-13 04:00:00+00:00     0.750288
  2021-09-14 04:00:00+00:00     2.105104
  2021-09-15 04:00:00+00:00     7.337119
  2021-09-16 04:00:00+00:00     6.773662
  2021-09-17 04:00:00+00:00     5.059932
  2021-09-20 04:00:00+00:00     3.110663
  2021-09-21 04:00:00+00:00     1.637132
  2021-09-22 04:00:00+00:00     2.992952
  2021-09-23 04:00:00+00:00     1.222440
  2021-09-24 04:00:00+00:00     1.556326
  2021-09-27 04:00:00+00:00    -7.291023
  2021-09-28 04:00:00+00:00    -7.622718
  2021-09-29 04:00:00+00:00    -5.324583
  2021-09-30 04:00:00+00:00   -11.367185
  2021-10-01 04:00:00+00:00    -3.487903
  2021-10-04 04:00:00+00:00    -6.199044
  2021-10-05 04:00:00+00:00    -2.833367
  2021-10-06 04:00:00+00:00    -1.327117
  2021-10-07 04:00:00+00:00    -3.953749
  2021-10-08 04:00:00+00:00    -1.793742
  2021-10-11 04:00:00+00:00    -1.823237
  2021-10-12 04:00:00+00:00    -3.732663
  2021-10-13 04:00:00+00:00    -6.704984
  2021-10-14 04:00:00+00:00    -4.662696
  2021-10-15 04:00:00+00:00    -3.404711
  2021-10-18 04:00:00+00:00    -7.022285
  2021-10-19 04:00:00+00:00    -5.926889
  2021-10-20 04:00:00+00:00    -6.840126
  2021-10-21 04:00:00+00:00    -8.058773
  2021-10-22 04:00:00+00:00   -10.420214
  2021-10-25 04:00:00+00:00   -15.397276
  2021-10-26 04:00:00+00:00   -14.303035
  2021-10-27 04:00:00+00:00    -0.232960
  2021-10-28 04:00:00+00:00     2.687477
  2021-10-29 04:00:00+00:00    11.402662
  2021-11-01 04:00:00+00:00     1.382854
  2021-11-02 04:00:00+00:00     1.413346
  2021-11-03 04:00:00+00:00    -2.223142
  2021-11-04 04:00:00+00:00   -10.614254
  2021-11-05 04:00:00+00:00    -9.191658
  2021-11-08 05:00:00+00:00   -29.737407
  2021-11-09 05:00:00+00:00   -28.850494
  2021-11-10 05:00:00+00:00   -19.937143
  2021-11-11 05:00:00+00:00   -27.848466
  2021-11-12 05:00:00+00:00   -26.479914
  2021-11-15 05:00:00+00:00   -24.954368
  2021-11-16 05:00:00+00:00   -30.775979
  2021-11-17 05:00:00+00:00   -29.441081
  2021-11-18 05:00:00+00:00   -33.009660
  2021-11-19 05:00:00+00:00   -31.775705
  2021-11-22 05:00:00+00:00   -30.564756
  2021-11-23 05:00:00+00:00   -28.674456
  2021-11-24 05:00:00+00:00   -40.689673
  2021-11-26 05:00:00+00:00   -44.273328
  2021-11-29 05:00:00+00:00   -48.356454
  2021-11-30 05:00:00+00:00   -48.895431
  2021-12-01 05:00:00+00:00   -35.015747
  2021-12-02 05:00:00+00:00   -38.045467
  2021-12-03 05:00:00+00:00   -34.160543
  2021-12-06 05:00:00+00:00   -23.288434
  2021-12-07 05:00:00+00:00   -23.555871
  2021-12-08 05:00:00+00:00   -24.111916
  2021-12-09 05:00:00+00:00   -14.886631
  2021-12-10 05:00:00+00:00    -6.145913
  2021-12-13 05:00:00+00:00    -1.904596
  2021-12-14 05:00:00+00:00   -15.761727
  2021-12-15 05:00:00+00:00   -26.389908
  2021-12-16 05:00:00+00:00   -23.925770
  2021-12-17 05:00:00+00:00   -23.642744
  2021-12-20 05:00:00+00:00   -24.502519
  2021-12-21 05:00:00+00:00   -30.253494
  2021-12-22 05:00:00+00:00   -23.768528
  2021-12-23 05:00:00+00:00   -25.790481
  2021-12-27 05:00:00+00:00   -30.804045
  2021-12-28 05:00:00+00:00   -30.123752
  2021-12-29 05:00:00+00:00   -21.824880
  2021-12-30 05:00:00+00:00   -19.622059
  2021-12-31 05:00:00+00:00   -20.679608
  2022-01-03 05:00:00+00:00   -32.101724
  2022-01-04 05:00:00+00:00   -28.797668
  2022-01-05 05:00:00+00:00   -28.576406
  2022-01-06 05:00:00+00:00   -31.200723
  2022-01-07 05:00:00+00:00   -24.467466
  2022-01-10 05:00:00+00:00   -24.237466
  2022-01-11 05:00:00+00:00   -31.779001
  2022-01-12 05:00:00+00:00   -28.737635
  2022-01-13 05:00:00+00:00   -34.857397
  2022-01-14 05:00:00+00:00   -35.890798
  2022-01-18 05:00:00+00:00   -35.748688
  2022-01-19 05:00:00+00:00   -29.381189
  2022-01-20 05:00:00+00:00   -21.196915
  2022-01-21 05:00:00+00:00   -21.980713
  2022-01-24 05:00:00+00:00   -18.097681
  2022-01-25 05:00:00+00:00   -17.586289
  2022-01-26 05:00:00+00:00    -8.713625
  2022-01-27 05:00:00+00:00     7.019003
  2022-01-28 05:00:00+00:00    11.336545
  2022-01-31 05:00:00+00:00     0.055351
  2022-02-01 05:00:00+00:00    -6.096171
  2022-02-02 05:00:00+00:00   -10.688861
  2022-02-03 05:00:00+00:00   -18.734244
  2022-02-04 05:00:00+00:00   -19.514189
  2022-02-07 05:00:00+00:00   -24.612966
  2022-02-08 05:00:00+00:00   -28.089031
  2022-02-09 05:00:00+00:00   -28.618333
  2022-02-10 05:00:00+00:00   -26.446285
  2022-02-11 05:00:00+00:00   -14.221910
  2022-02-14 05:00:00+00:00   -15.955728
  2022-02-15 05:00:00+00:00   -21.674251
  2022-02-16 05:00:00+00:00   -16.770276
  2022-02-17 05:00:00+00:00   -17.273201
  2022-02-18 05:00:00+00:00   -22.341985
  2022-02-22 05:00:00+00:00   -25.380195
  2022-02-23 05:00:00+00:00   -23.615131
  2022-02-24 05:00:00+00:00   -19.846602
  2022-02-25 05:00:00+00:00   -24.197127
  2022-02-28 05:00:00+00:00   -26.260159
  2022-03-01 05:00:00+00:00   -15.321985
  2022-03-02 05:00:00+00:00   -16.997113
  2022-03-03 05:00:00+00:00   -11.477156
  2022-03-04 05:00:00+00:00   -11.989513
  2022-03-07 05:00:00+00:00   -14.454883
  2022-03-08 05:00:00+00:00   -21.524104
  2022-03-09 05:00:00+00:00   -17.451972
  2022-03-10 05:00:00+00:00   -13.229288
  2022-03-11 05:00:00+00:00   -15.377192
  2022-03-14 04:00:00+00:00   -15.837110
  2022-03-15 04:00:00+00:00   -16.129158
  2022-03-16 04:00:00+00:00   -18.275085
  2022-03-17 04:00:00+00:00   -11.726507
  2022-03-18 04:00:00+00:00    -9.267019
  2022-03-21 04:00:00+00:00   -14.359764
  2022-03-22 04:00:00+00:00    -7.688248
  2022-03-23 04:00:00+00:00   -10.921841
  2022-03-24 04:00:00+00:00   -16.583527
  2022-03-25 04:00:00+00:00   -15.667120
  2022-03-28 04:00:00+00:00    -9.532878
  2022-03-29 04:00:00+00:00    -9.469223
  2022-03-30 04:00:00+00:00    -4.787837
  2022-03-31 04:00:00+00:00     5.015302
  2022-04-01 04:00:00+00:00     7.912358
  2022-04-04 04:00:00+00:00     9.826088
  2022-04-05 04:00:00+00:00    11.501286
  2022-04-06 04:00:00+00:00     5.016264
  2022-04-07 04:00:00+00:00     6.808566
  2022-04-08 04:00:00+00:00     6.635342
  2022-04-11 04:00:00+00:00     0.566222
  2022-04-12 04:00:00+00:00     0.893714
  2022-04-13 04:00:00+00:00     2.351256
  2022-04-14 04:00:00+00:00     1.833796
  2022-04-18 04:00:00+00:00     1.234008
  2022-04-19 04:00:00+00:00     1.289965
  2022-04-20 04:00:00+00:00     6.871993
  2022-04-21 04:00:00+00:00     7.802012
  2022-04-22 04:00:00+00:00     3.679287
  2022-04-25 04:00:00+00:00     6.406685
  2022-04-26 04:00:00+00:00     4.500092
  2022-04-27 04:00:00+00:00    17.888582
  2022-04-28 04:00:00+00:00    16.948344
  2022-04-29 04:00:00+00:00    11.240666
  2022-05-02 04:00:00+00:00    11.477552
  2022-05-03 04:00:00+00:00     6.782942
  2022-05-04 04:00:00+00:00     2.100601
  2022-05-05 04:00:00+00:00    -1.904913
  2022-05-06 04:00:00+00:00    -6.809236
  2022-05-09 04:00:00+00:00    -3.004662
  2022-05-10 04:00:00+00:00    -1.767551
  2022-05-11 04:00:00+00:00    -9.458842
  2022-05-12 04:00:00+00:00   -13.322435
  2022-05-13 04:00:00+00:00   -20.077365
  2022-05-16 04:00:00+00:00   -18.329879
  2022-05-17 04:00:00+00:00   -25.798982
  2022-05-18 04:00:00+00:00   -28.919960
  2022-05-19 04:00:00+00:00   -30.466005
  2022-05-20 04:00:00+00:00   -26.119947
  2022-05-23 04:00:00+00:00   -20.469667
  2022-05-24 04:00:00+00:00   -15.423677
  2022-05-25 04:00:00+00:00   -14.839080
  2022-05-26 04:00:00+00:00   -20.938245
  2022-05-27 04:00:00+00:00   -19.052650
  2022-05-31 04:00:00+00:00   -19.801065
  2022-06-01 04:00:00+00:00   -18.256530
  2022-06-02 04:00:00+00:00   -27.549226
  2022-06-03 04:00:00+00:00   -28.550655
  2022-06-06 04:00:00+00:00   -28.810580
  2022-06-07 04:00:00+00:00   -24.485614
  2022-06-08 04:00:00+00:00   -21.323224
  2022-06-09 04:00:00+00:00   -22.125943
  2022-06-10 04:00:00+00:00   -27.741176
  2022-06-13 04:00:00+00:00   -26.303658
  2022-06-14 04:00:00+00:00   -24.073658
  2022-06-15 04:00:00+00:00   -20.393309
  2022-06-16 04:00:00+00:00   -15.917088
  2022-06-17 04:00:00+00:00   -12.491186
  2022-06-21 04:00:00+00:00    -9.850981
  2022-06-22 04:00:00+00:00   -10.398822
  2022-06-23 04:00:00+00:00    -2.617593
  2022-06-24 04:00:00+00:00    -1.003514
  2022-06-27 04:00:00+00:00    -2.383870
  2022-06-28 04:00:00+00:00    -2.433557
  2022-06-29 04:00:00+00:00     5.681996
  2022-06-30 04:00:00+00:00     4.614018
  2022-07-01 04:00:00+00:00    11.715110
  2022-07-05 04:00:00+00:00    12.607549
  2022-07-06 04:00:00+00:00    15.734454
  2022-07-07 04:00:00+00:00    11.786306
  2022-07-08 04:00:00+00:00    10.968608
  2022-07-11 04:00:00+00:00    11.548116
  2022-07-12 04:00:00+00:00     1.624953
  2022-07-13 04:00:00+00:00    -1.127642
  2022-07-14 04:00:00+00:00    -1.445920
  2022-07-15 04:00:00+00:00    -2.706364
  2022-07-18 04:00:00+00:00    -5.673632
  2022-07-19 04:00:00+00:00    -7.308760
  2022-07-20 04:00:00+00:00   -10.085324
  2022-07-21 04:00:00+00:00   -10.094900
  2022-07-22 04:00:00+00:00    -9.928555
  2022-07-25 04:00:00+00:00   -10.588336
  2022-07-26 04:00:00+00:00   -13.959765
  2022-07-27 04:00:00+00:00    -4.221369
  2022-07-28 04:00:00+00:00     0.573802
  2022-07-29 04:00:00+00:00     0.552710
  2022-08-01 04:00:00+00:00    -5.766941
  2022-08-02 04:00:00+00:00   -12.857384
  2022-08-03 04:00:00+00:00    -3.342630
  2022-08-04 04:00:00+00:00   -11.206686
  2022-08-05 04:00:00+00:00    -9.460348
  2022-08-08 04:00:00+00:00    -8.569474
  2022-08-09 04:00:00+00:00     0.449971
  2022-08-10 04:00:00+00:00     1.855566
  2022-08-11 04:00:00+00:00     1.160751
  2022-08-12 04:00:00+00:00     1.839515
  2022-08-15 04:00:00+00:00     3.119802
  2022-08-16 04:00:00+00:00     3.618511
  2022-08-17 04:00:00+00:00     5.227656
  2022-08-18 04:00:00+00:00     0.705560
  2022-08-19 04:00:00+00:00     3.662847
  2022-08-22 04:00:00+00:00     0.095668
  2022-08-23 04:00:00+00:00    -0.670446
  2022-08-24 04:00:00+00:00    -1.693397
  2022-08-25 04:00:00+00:00    -5.548525
  2022-08-26 04:00:00+00:00    -6.984756
  2022-08-29 04:00:00+00:00    -5.664600
  2022-08-30 04:00:00+00:00    -5.515960
  2022-08-31 04:00:00+00:00    -3.799259
  2022-09-01 04:00:00+00:00    -0.922197
  2022-09-02 04:00:00+00:00    -2.014417
  2022-09-06 04:00:00+00:00    -2.462396
  2022-09-07 04:00:00+00:00     0.994578
  2022-09-08 04:00:00+00:00    -3.501480
  2022-09-09 04:00:00+00:00    -1.710557
  2022-09-12 04:00:00+00:00     1.738152
  2022-09-13 04:00:00+00:00    -1.096201
  2022-09-14 04:00:00+00:00    -1.518865
  2022-09-15 04:00:00+00:00    -7.131235
  2022-09-16 04:00:00+00:00    -7.538141
  2022-09-19 04:00:00+00:00    -8.162171
  2022-09-20 04:00:00+00:00    -7.870149
  2022-09-21 04:00:00+00:00   -10.173599
  2022-09-22 04:00:00+00:00    -0.404871
  2022-09-23 04:00:00+00:00    -1.071770
  2022-09-26 04:00:00+00:00     1.037806
  2022-09-27 04:00:00+00:00    -1.354140
  2022-09-28 04:00:00+00:00     1.456645
  2022-09-29 04:00:00+00:00     4.444363
  2022-09-30 04:00:00+00:00     1.056453
  2022-10-03 04:00:00+00:00     4.623059
  2022-10-04 04:00:00+00:00     9.981468
  2022-10-05 04:00:00+00:00    10.239309
  2022-10-06 04:00:00+00:00     7.969166
  2022-10-07 04:00:00+00:00    10.041944
  2022-10-10 04:00:00+00:00     6.030939
  2022-10-11 04:00:00+00:00     2.470653
  2022-10-12 04:00:00+00:00     2.468781
  2022-10-13 04:00:00+00:00     9.264963
  2022-10-14 04:00:00+00:00     8.246847
  2022-10-17 04:00:00+00:00    14.077845
  2022-10-18 04:00:00+00:00    15.110004
  2022-10-19 04:00:00+00:00    14.162237
  2022-10-20 04:00:00+00:00    12.993098
  2022-10-21 04:00:00+00:00    17.331438
  2022-10-24 04:00:00+00:00    22.647914
  2022-10-25 04:00:00+00:00    21.753440
  2022-10-26 04:00:00+00:00     5.117333
  2022-10-27 04:00:00+00:00     2.303310
  2022-10-28 04:00:00+00:00     6.124301
  2022-10-31 04:00:00+00:00     5.414526
  2022-11-01 04:00:00+00:00     2.076111
  2022-11-02 04:00:00+00:00    -4.393309
  2022-11-03 04:00:00+00:00   -12.543172
  2022-11-04 04:00:00+00:00    -8.635412
  2022-11-07 05:00:00+00:00    -3.538438
  2022-11-08 05:00:00+00:00    -3.734988
  2022-11-09 05:00:00+00:00    -1.987919
  2022-11-10 05:00:00+00:00     3.195710
  2022-11-11 05:00:00+00:00     1.265260
  2022-11-14 05:00:00+00:00    -6.097336
  2022-11-15 05:00:00+00:00   -10.090586
  2022-11-16 05:00:00+00:00    -4.627548
  2022-11-17 05:00:00+00:00    -6.542301
  2022-11-18 05:00:00+00:00    -6.489494
  2022-11-21 05:00:00+00:00    -3.934597
  2022-11-22 05:00:00+00:00    -5.290149
  2022-11-23 05:00:00+00:00    -4.527205
  2022-11-25 05:00:00+00:00    -2.659214
  2022-11-28 05:00:00+00:00    -5.358989
  2022-11-29 05:00:00+00:00    -7.099781
  2022-11-30 05:00:00+00:00     1.121422
  2022-12-01 05:00:00+00:00     0.904516

In [53]:
#to calculate z score for trading period(including past available formation data)
from src.strategy.zscore import calculate_zscore

formation_spread = formation_spreads[0][6]
trading_spread = trading_spreads[0][10]

trading_zscore = calculate_zscore(
    trading_spread,
    formation_spread
)

trading_zscore

timestamp
2024-01-02 05:00:00+00:00    0.992365
2024-01-03 05:00:00+00:00    1.206050
2024-01-04 05:00:00+00:00    1.036833
2024-01-05 05:00:00+00:00    0.847931
2024-01-08 05:00:00+00:00    0.628688
2024-01-09 05:00:00+00:00    0.462826
2024-01-10 05:00:00+00:00    0.825785
2024-01-11 05:00:00+00:00    0.944591
2024-01-12 05:00:00+00:00    1.217545
2024-01-16 05:00:00+00:00    0.447231
2024-01-17 05:00:00+00:00    0.311233
2024-01-18 05:00:00+00:00    0.334143
2024-01-19 05:00:00+00:00   -0.257636
2024-01-22 05:00:00+00:00    0.068149
2024-01-23 05:00:00+00:00    0.158858
2024-01-24 05:00:00+00:00   -0.366995
2024-01-25 05:00:00+00:00   -0.405469
2024-01-26 05:00:00+00:00   -0.231808
2024-01-29 05:00:00+00:00   -0.011171
2024-01-30 05:00:00+00:00    0.342481
2024-01-31 05:00:00+00:00    0.151718
2024-02-01 05:00:00+00:00    0.235859
2024-02-02 05:00:00+00:00    0.067631
2024-02-05 05:00:00+00:00    0.056733
2024-02-06 05:00:00+00:00    0.496152
2024-02-07 05:00:00+00:00    0.668081
2024-02-08 05:00:00+00:00    0.782124
2024-02-09 05:00:00+00:00    0.852743
2024-02-12 05:00:00+00:00    0.652172
2024-02-13 05:00:00+00:00    0.272282
2024-02-14 05:00:00+00:00   -0.088883
2024-02-15 05:00:00+00:00   -0.084982
2024-02-16 05:00:00+00:00    0.005516
2024-02-20 05:00:00+00:00    0.525598
2024-02-21 05:00:00+00:00    0.596369
2024-02-22 05:00:00+00:00   -0.215478
2024-02-23 05:00:00+00:00    0.102790
2024-02-26 05:00:00+00:00    0.011279
2024-02-27 05:00:00+00:00   -0.132416
2024-02-28 05:00:00+00:00   -0.017908
2024-02-29 05:00:00+00:00   -0.881727
2024-03-01 05:00:00+00:00   -1.512943
2024-03-04 05:00:00+00:00   -1.729043
2024-03-05 05:00:00+00:00   -2.267345
2024-03-06 05:00:00+00:00   -2.672390
2024-03-07 05:00:00+00:00   -2.392503
2024-03-08 05:00:00+00:00   -2.234451
2024-03-11 04:00:00+00:00   -1.673087
2024-03-12 04:00:00+00:00   -1.490658
2024-03-13 04:00:00+00:00   -0.939304
2024-03-14 04:00:00+00:00    0.056248
2024-03-15 04:00:00+00:00   -0.618906
2024-03-18 04:00:00+00:00   -0.549238
2024-03-19 04:00:00+00:00    0.280642
2024-03-20 04:00:00+00:00    0.570681
2024-03-21 04:00:00+00:00    0.830179
2024-03-22 04:00:00+00:00    0.733025
2024-03-25 04:00:00+00:00    0.538784
2024-03-26 04:00:00+00:00    0.537049
2024-03-27 04:00:00+00:00    0.406149
2024-03-28 04:00:00+00:00    0.310706
2024-04-01 04:00:00+00:00    0.284364
2024-04-02 04:00:00+00:00    0.468514
2024-04-03 04:00:00+00:00    0.278028
2024-04-04 04:00:00+00:00    1.211548
2024-04-05 04:00:00+00:00    1.232659
2024-04-08 04:00:00+00:00    1.225253
2024-04-09 04:00:00+00:00    1.237958
2024-04-10 04:00:00+00:00    1.355133
2024-04-11 04:00:00+00:00    1.327908
2024-04-12 04:00:00+00:00    1.559860
2024-04-15 04:00:00+00:00    1.391590
2024-04-16 04:00:00+00:00    1.211605
2024-04-17 04:00:00+00:00    1.747182
2024-04-18 04:00:00+00:00    1.328214
2024-04-19 04:00:00+00:00    1.684211
2024-04-22 04:00:00+00:00    1.623364
2024-04-23 04:00:00+00:00    1.663305
2024-04-24 04:00:00+00:00    1.763259
2024-04-25 04:00:00+00:00    1.169750
2024-04-26 04:00:00+00:00    1.240764
2024-04-29 04:00:00+00:00    0.862047
2024-04-30 04:00:00+00:00    0.409488
2024-05-01 04:00:00+00:00    1.642214
2024-05-02 04:00:00+00:00    1.636939
2024-05-03 04:00:00+00:00    1.719169
2024-05-06 04:00:00+00:00    1.662921
2024-05-07 04:00:00+00:00    1.565468
2024-05-08 04:00:00+00:00    1.671797
2024-05-09 04:00:00+00:00    1.832313
2024-05-10 04:00:00+00:00    1.967592
2024-05-13 04:00:00+00:00    2.010437
2024-05-14 04:00:00+00:00    1.951298
2024-05-15 04:00:00+00:00    1.786765
2024-05-16 04:00:00+00:00    1.487648
2024-05-17 04:00:00+00:00    1.323567
2024-05-20 04:00:00+00:00    1.420202
2024-05-21 04:00:00+00:00    1.695163
2024-05-22 04:00:00+00:00    1.697633
2024-05-23 04:00:00+00:00    1.886836
2024-05-24 04:00:00+00:00    1.615895
2024-05-28 04:00:00+00:00    1.261565
2024-05-29 04:00:00+00:00    1.650181
2024-05-30 04:00:00+00:00    0.901661
2024-05-31 04:00:00+00:00    0.910651
2024-06-03 04:00:00+00:00    1.067262
2024-06-04 04:00:00+00:00    1.420098
2024-06-05 04:00:00+00:00    1.344758
2024-06-06 04:00:00+00:00    1.323397
2024-06-07 04:00:00+00:00    1.217857
2024-06-10 04:00:00+00:00    1.903806
2024-06-11 04:00:00+00:00    2.202471
2024-06-12 04:00:00+00:00    2.473562
2024-06-13 04:00:00+00:00    2.508991
2024-06-14 04:00:00+00:00    2.559543
2024-06-17 04:00:00+00:00    2.881451
2024-06-18 04:00:00+00:00    3.030748
2024-06-20 04:00:00+00:00    2.510181
2024-06-21 04:00:00+00:00    2.710273
2024-06-24 04:00:00+00:00    2.672408
2024-06-25 04:00:00+00:00    2.798975
2024-06-26 04:00:00+00:00    3.013702
2024-06-27 04:00:00+00:00    2.899445
2024-06-28 04:00:00+00:00    2.459034
2024-07-01 04:00:00+00:00    3.150144
2024-07-02 04:00:00+00:00    2.809570
2024-07-03 04:00:00+00:00    2.883373
2024-07-05 04:00:00+00:00    2.635932
2024-07-08 04:00:00+00:00    2.136986
2024-07-09 04:00:00+00:00    1.957077
2024-07-10 04:00:00+00:00    1.790237
2024-07-11 04:00:00+00:00    1.442537
2024-07-12 04:00:00+00:00    1.414026
2024-07-15 04:00:00+00:00    1.541172
2024-07-16 04:00:00+00:00    1.501688
2024-07-17 04:00:00+00:00    2.401320
2024-07-18 04:00:00+00:00    2.495281
2024-07-19 04:00:00+00:00    2.616855
2024-07-22 04:00:00+00:00    2.571618
2024-07-23 04:00:00+00:00    2.754481
2024-07-24 04:00:00+00:00    2.685603
2024-07-25 04:00:00+00:00    2.645581
2024-07-26 04:00:00+00:00    2.804040
2024-07-29 04:00:00+00:00    2.862957
2024-07-30 04:00:00+00:00    2.778260
2024-07-31 04:00:00+00:00    2.215495
2024-08-01 04:00:00+00:00    2.888306
2024-08-02 04:00:00+00:00    2.538630
2024-08-05 04:00:00+00:00    1.867306
2024-08-06 04:00:00+00:00    2.317203
2024-08-07 04:00:00+00:00    2.354380
2024-08-08 04:00:00+00:00    2.050264
2024-08-09 04:00:00+00:00    2.296461
2024-08-12 04:00:00+00:00    2.169082
2024-08-13 04:00:00+00:00    2.178640
2024-08-14 04:00:00+00:00    2.304017
2024-08-15 04:00:00+00:00    2.062058
2024-08-16 04:00:00+00:00    1.886742
2024-08-19 04:00:00+00:00    1.599817
2024-08-20 04:00:00+00:00    1.655120
2024-08-21 04:00:00+00:00    1.542944
2024-08-22 04:00:00+00:00    1.574590
2024-08-23 04:00:00+00:00    1.424656
2024-08-26 04:00:00+00:00    1.591906
2024-08-27 04:00:00+00:00    1.572007
2024-08-28 04:00:00+00:00    1.690434
2024-08-29 04:00:00+00:00    1.833934
2024-08-30 04:00:00+00:00    1.801122
2024-09-03 04:00:00+00:00    2.189319
2024-09-04 04:00:00+00:00    1.931177
2024-09-05 04:00:00+00:00    1.990870
2024-09-06 04:00:00+00:00    2.031502
2024-09-09 04:00:00+00:00    1.954962
2024-09-10 04:00:00+00:00    1.994660
2024-09-11 04:00:00+00:00    1.911721
2024-09-12 04:00:00+00:00    2.002289
2024-09-13 04:00:00+00:00    2.041658
2024-09-16 04:00:00+00:00    2.077338
2024-09-17 04:00:00+00:00    2.286355
2024-09-18 04:00:00+00:00    2.263555
2024-09-19 04:00:00+00:00    2.061355
2024-09-20 04:00:00+00:00    1.974387
2024-09-23 04:00:00+00:00    1.858184
2024-09-24 04:00:00+00:00    1.603418
2024-09-25 04:00:00+00:00    1.496701
2024-09-26 04:00:00+00:00    1.151205
2024-09-27 04:00:00+00:00    1.208376
2024-09-30 04:00:00+00:00    1.306292
2024-10-01 04:00:00+00:00    1.198259
2024-10-02 04:00:00+00:00    1.063864
2024-10-03 04:00:00+00:00    0.865221
2024-10-04 04:00:00+00:00    0.385937
2024-10-07 04:00:00+00:00    0.141411
2024-10-08 04:00:00+00:00    0.227109
2024-10-09 04:00:00+00:00    0.430474
2024-10-10 04:00:00+00:00    0.762700
2024-10-11 04:00:00+00:00    0.566963
2024-10-14 04:00:00+00:00    0.821054
2024-10-15 04:00:00+00:00    1.300872
2024-10-16 04:00:00+00:00    1.231562
2024-10-17 04:00:00+00:00    1.245201
2024-10-18 04:00:00+00:00    1.312729
2024-10-21 04:00:00+00:00    1.223101
2024-10-22 04:00:00+00:00    1.761773
2024-10-23 04:00:00+00:00    1.718354
2024-10-24 04:00:00+00:00    1.689290
2024-10-25 04:00:00+00:00    1.652242
2024-10-28 04:00:00+00:00    1.381122
2024-10-29 04:00:00+00:00    1.214685
2024-10-30 04:00:00+00:00    2.241108
2024-10-31 04:00:00+00:00    1.533048
2024-11-01 04:00:00+00:00    1.803228
2024-11-04 05:00:00+00:00    1.794767
2024-11-05 05:00:00+00:00    1.846496
2024-11-06 05:00:00+00:00    1.965363
2024-11-07 05:00:00+00:00    1.884516
2024-11-08 05:00:00+00:00    1.880678
2024-11-11 05:00:00+00:00    1.745611
2024-11-12 05:00:00+00:00    2.133881
2024-11-13 05:00:00+00:00    2.450098
2024-11-14 05:00:00+00:00    2.528190
2024-11-15 05:00:00+00:00    2.310856
2024-11-18 05:00:00+00:00    2.105572
2024-11-19 05:00:00+00:00    2.146919
2024-11-20 05:00:00+00:00    2.158021
2024-11-21 05:00:00+00:00    2.064241
2024-11-22 05:00:00+00:00    2.158414
2024-11-25 05:00:00+00:00    2.062068
2024-11-26 05:00:00+00:00    2.572231
2024-11-27 05:00:00+00:00    2.466537
2024-11-29 05:00:00+00:00    2.422911
2024-12-02 05:00:00+00:00    2.411973
2024-12-03 05:00:00+00:00    2.415775
2024-12-04 05:00:00+00:00    2.516162
2024-12-05 05:00:00+00:00    2.832078
2024-12-06 05:00:00+00:00    3.002574
2024-12-09 05:00:00+00:00    3.489555
2024-12-10 05:00:00+00:00    3.541650
2024-12-11 05:00:00+00:00    3.583451
2024-12-12 05:00:00+00:00    3.554248
2024-12-13 05:00:00+00:00    3.647016
2024-12-16 05:00:00+00:00    3.778358
2024-12-17 05:00:00+00:00    3.932869
2024-12-18 05:00:00+00:00    3.519209
2024-12-19 05:00:00+00:00    3.613994
2024-12-20 05:00:00+00:00    3.557735
2024-12-23 05:00:00+00:00    3.215476
2024-12-24 05:00:00+00:00    3.244701
2024-12-26 05:00:00+00:00    3.248548
2024-12-27 05:00:00+00:00    2.978961
2024-12-30 05:00:00+00:00    2.918547
2024-12-31 05:00:00+00:00    2.880271
2025-01-02 05:00:00+00:00    2.781826
2025-01-03 05:00:00+00:00    2.687294
2025-01-06 05:00:00+00:00    2.613139
2025-01-07 05:00:00+00:00    2.538887
2025-01-08 05:00:00+00:00    2.867391
2025-01-10 05:00:00+00:00    2.961217
2025-01-13 05:00:00+00:00    2.829721
2025-01-14 05:00:00+00:00    2.829389
2025-01-15 05:00:00+00:00    2.960582
2025-01-16 05:00:00+00:00    2.965962
2025-01-17 05:00:00+00:00    2.944236
2025-01-21 05:00:00+00:00    2.874889
2025-01-22 05:00:00+00:00    3.333625
2025-01-23 05:00:00+00:00    3.363060
2025-01-24 05:00:00+00:00    3.272016
2025-01-27 05:00:00+00:00    3.333809
2025-01-28 05:00:00+00:00    3.732639
2025-01-29 05:00:00+00:00    3.413037
2025-01-30 05:00:00+00:00    2.511423
2025-01-31 05:00:00+00:00    2.638369
dtype: float64

In [54]:
#WE GENERATE ENTRY EXIT SIGNALS NOW
#ENTER ON THRESHOLD
#EXIT FOR 1)MEAN REVERSION
#         2)MAX HOLDING PERIOD
#         3)STOP-LOSS

In [55]:
from src.strategy.half_life import calculate_half_life
half_life=calculate_half_life(formation_spread)
max_holding_period=2*half_life

In [56]:
#will need a for loop in future rn just working with one pair
import pandas as pd
entry=pd.Series("NO_EVENT",index=trading_zscore.index)
entry[trading_zscore<formation_zscores[0][8]]="LONG_ENTRY"
entry[trading_zscore>formation_zscores[0][9]]="SHORT_ENTRY"
entry
"""
NEED TO FIX REPEATED EVENTS DAY AFTER DAY COZ OF JUST THRESHOLD CONDITION.NEED TO IMPLEMENT CONDITION TO CHECK IF ALREADY ENTERED AND EXITED
"""

'\nNEED TO FIX REPEATED EVENTS DAY AFTER DAY COZ OF JUST THRESHOLD CONDITION.NEED TO IMPLEMENT CONDITION TO CHECK IF ALREADY ENTERED AND EXITED\n'

In [57]:
#EXIT-CONDITIONS1)MEAN REVERSION
#               2)MAX HOLDING PERIOD
#               3)STOP LOSS

In [58]:
#CANT MAKE ENTRY AND EXIT SEPARATELY

In [59]:
#position=0(currently flat)
#position=1(currently long spread)
#position=-1(currently short spread)

In [60]:
position=0
position_df=pd.DataFrame(trading_zscore.copy())
position_df=position_df.rename(columns={0:"zscore"})
position_df["position"]=0
position_df["event"]="NO_EVENT"
entry_day=None
for i in range(len(position_df)):
        if position==0:
            if position_df.iloc[i,0]<formation_zscores[0][8]:#long entry check
                position=1
                entry_day=i
                position_df.loc[position_df.index[i],"event"]="LONG_ENTRY"
            elif position_df.iloc[i,0]>formation_zscores[0][9]:#short entry check
                position=-1
                entry_day=i
                position_df.loc[position_df.index[i],"event"]="SHORT_ENTRY"
                
        
        elif position==1:
            #check mean reversion on long position
            if position_df.iloc[i,0]>=formation_zscores[0][7].quantile(0.5):
                position=0#exit
                entry_day=None
                position_df.loc[position_df.index[i],"event"]="LONG_MEAN_EXIT"
            #check stop loss
            elif position_df.iloc[i,0]<=formation_zscores[0][8]-1:
                position=2#exit-long stop loss
                entry_day=None
                position_df.loc[position_df.index[i],"event"]="LONG_STOPLOSS"
                
            #check max holding days
            elif i-entry_day>=max_holding_period:
                position=0
                entry_day=None
                position_df.loc[position_df.index[i],"event"]="LONG_MAX_HOLDING"
                
        
        elif position==-1:
            #check mean reversion on short position
            if position_df.iloc[i,0]<=formation_zscores[0][7].quantile(0.5):
                position=0#exit
                entry_day=None
                position_df.loc[position_df.index[i],"event"]="SHORT_MEAN_EXIT"
            #check stop loss
            elif position_df.iloc[i,0]>=formation_zscores[0][9]+1:
                position=-2#exit-short stop loss
                entry_day=None
                position_df.loc[position_df.index[i],"event"]="SHORT_STOPLOSS"
            elif i-entry_day>=max_holding_period:
                position=0
                entry_day=None
                position_df.loc[position_df.index[i],"event"]="SHORT_MAX_HOLDING"
print(f"upper threshold:{formation_zscores[0][9]}\nlower threshold:{formation_zscores[0][8]}")
position_df

upper threshold:2.4840177332105604
lower threshold:-0.7962765530142031

                             zscore  position          event
timestamp
2024-01-02 05:00:00+00:00  0.992365         0       NO_EVENT
2024-01-03 05:00:00+00:00  1.206050         0       NO_EVENT
2024-01-04 05:00:00+00:00  1.036833         0       NO_EVENT
2024-01-05 05:00:00+00:00  0.847931         0       NO_EVENT
2024-01-08 05:00:00+00:00  0.628688         0       NO_EVENT
2024-01-09 05:00:00+00:00  0.462826         0       NO_EVENT
2024-01-10 05:00:00+00:00  0.825785         0       NO_EVENT
2024-01-11 05:00:00+00:00  0.944591         0       NO_EVENT
2024-01-12 05:00:00+00:00  1.217545         0       NO_EVENT
2024-01-16 05:00:00+00:00  0.447231         0       NO_EVENT
2024-01-17 05:00:00+00:00  0.311233         0       NO_EVENT
2024-01-18 05:00:00+00:00  0.334143         0       NO_EVENT
2024-01-19 05:00:00+00:00 -0.257636         0       NO_EVENT
2024-01-22 05:00:00+00:00  0.068149         0       NO_EVENT
2024-01-23 05:00:00+00:00  0.158858         0       NO_EVENT
2024-01-24 05:00:00+00:00 -0.366995         0       NO_EVENT
2024-01-25 05:00:00+00:00 -0.405469         0       NO_EVENT
2024-01-26 05:00:00+00:00 -0.231808         0       NO_EVENT
2024-01-29 05:00:00+00:00 -0.011171         0       NO_EVENT
2024-01-30 05:00:00+00:00  0.342481         0       NO_EVENT
2024-01-31 05:00:00+00:00  0.151718         0       NO_EVENT
2024-02-01 05:00:00+00:00  0.235859         0       NO_EVENT
2024-02-02 05:00:00+00:00  0.067631         0       NO_EVENT
2024-02-05 05:00:00+00:00  0.056733         0       NO_EVENT
2024-02-06 05:00:00+00:00  0.496152         0       NO_EVENT
2024-02-07 05:00:00+00:00  0.668081         0       NO_EVENT
2024-02-08 05:00:00+00:00  0.782124         0       NO_EVENT
2024-02-09 05:00:00+00:00  0.852743         0       NO_EVENT
2024-02-12 05:00:00+00:00  0.652172         0       NO_EVENT
2024-02-13 05:00:00+00:00  0.272282         0       NO_EVENT
2024-02-14 05:00:00+00:00 -0.088883         0       NO_EVENT
2024-02-15 05:00:00+00:00 -0.084982         0       NO_EVENT
2024-02-16 05:00:00+00:00  0.005516         0       NO_EVENT
2024-02-20 05:00:00+00:00  0.525598         0       NO_EVENT
2024-02-21 05:00:00+00:00  0.596369         0       NO_EVENT
2024-02-22 05:00:00+00:00 -0.215478         0       NO_EVENT
2024-02-23 05:00:00+00:00  0.102790         0       NO_EVENT
2024-02-26 05:00:00+00:00  0.011279         0       NO_EVENT
2024-02-27 05:00:00+00:00 -0.132416         0       NO_EVENT
2024-02-28 05:00:00+00:00 -0.017908         0       NO_EVENT
2024-02-29 05:00:00+00:00 -0.881727         0     LONG_ENTRY
2024-03-01 05:00:00+00:00 -1.512943         0       NO_EVENT
2024-03-04 05:00:00+00:00 -1.729043         0       NO_EVENT
2024-03-05 05:00:00+00:00 -2.267345         0  LONG_STOPLOSS
2024-03-06 05:00:00+00:00 -2.672390         0       NO_EVENT
2024-03-07 05:00:00+00:00 -2.392503         0       NO_EVENT
2024-03-08 05:00:00+00:00 -2.234451         0       NO_EVENT
2024-03-11 04:00:00+00:00 -1.673087         0       NO_EVENT
2024-03-12 04:00:00+00:00 -1.490658         0       NO_EVENT
2024-03-13 04:00:00+00:00 -0.939304         0       NO_EVENT
2024-03-14 04:00:00+00:00  0.056248         0       NO_EVENT
2024-03-15 04:00:00+00:00 -0.618906         0       NO_EVENT
2024-03-18 04:00:00+00:00 -0.549238         0       NO_EVENT
2024-03-19 04:00:00+00:00  0.280642         0       NO_EVENT
2024-03-20 04:00:00+00:00  0.570681         0       NO_EVENT
2024-03-21 04:00:00+00:00  0.830179         0       NO_EVENT
2024-03-22 04:00:00+00:00  0.733025         0       NO_EVENT
2024-03-25 04:00:00+00:00  0.538784         0       NO_EVENT
2024-03-26 04:00:00+00:00  0.537049         0       NO_EVENT
2024-03-27 04:00:00+00:00  0.406149         0       NO_EVENT
2024-03-28 04:00:00+00:00  0.310706         0       NO_EVENT
2024-04-01 04:00:00+00:00  0.284364         0       NO_EVENT
2024-04-02 04:00:00+00:00  0.468514         0       NO_EVENT
2024-04-03 04:00:00+00:00  0.278028         0       NO_EVENT
2024-04-04 04:00:00+00:00  1.211548         0       NO_EVENT
2024-04-05 04:00:00+00:00  1.232659         0       NO_EVENT
2024-04-08 04:00:00+00:00  1.225253         0       NO_EVENT
2024-04-09 04:00:00+00:00  1.237958         0       NO_EVENT
2024-04-10 04:00:00+00:00  1.355133         0       NO_EVENT
2024-04-11 04:00:00+00:00  1.327908         0       NO_EVENT
2024-04-12 04:00:00+00:00  1.559860         0       NO_EVENT
2024-04-15 04:00:00+00:00  1.391590         0       NO_EVENT
2024-04-16 04:00:00+00:00  1.211605         0       NO_EVENT
2024-04-17 04:00:00+00:00  1.747182         0       NO_EVENT
2024-04-18 04:00:00+00:00  1.328214         0       NO_EVENT
2024-04-19 04:00:00+00:00  1.684211         0       NO_EVENT
2024-04-22 04:00:00+00:00  1.623364         0       NO_EVENT
2024-04-23 04:00:00+00:00  1.663305         0       NO_EVENT
2024-04-24 04:00:00+00:00  1.763259         0       NO_EVENT
2024-04-25 04:00:00+00:00  1.169750         0       NO_EVENT
2024-04-26 04:00:00+00:00  1.240764         0       NO_EVENT
2024-04-29 04:00:00+00:00  0.862047         0       NO_EVENT
2024-04-30 04:00:00+00:00  0.409488         0       NO_EVENT
2024-05-01 04:00:00+00:00  1.642214         0       NO_EVENT
2024-05-02 04:00:00+00:00  1.636939         0       NO_EVENT
2024-05-03 04:00:00+00:00  1.719169         0       NO_EVENT
2024-05-06 04:00:00+00:00  1.662921         0       NO_EVENT
2024-05-07 04:00:00+00:00  1.565468         0       NO_EVENT
2024-05-08 04:00:00+00:00  1.671797         0       NO_EVENT
2024-05-09 04:00:00+00:00  1.832313         0       NO_EVENT
2024-05-10 04:00:00+00:00  1.967592         0       NO_EVENT
2024-05-13 04:00:00+00:00  2.010437         0       NO_EVENT
2024-05-14 04:00:00+00:00  1.951298         0       NO_EVENT
2024-05-15 04:00:00+00:00  1.786765         0       NO_EVENT
2024-05-16 04:00:00+00:00  1.487648         0       NO_EVENT
2024-05-17 04:00:00+00:00  1.323567         0       NO_EVENT
2024-05-20 04:00:00+00:00  1.420202         0       NO_EVENT
2024-05-21 04:00:00+00:00  1.695163         0       NO_EVENT
2024-05-22 04:00:00+00:00  1.697633         0       NO_EVENT
2024-05-23 04:00:00+00:00  1.886836         0       NO_EVENT
2024-05-24 04:00:00+00:00  1.615895         0       NO_EVENT
2024-05-28 04:00:00+00:00  1.261565         0       NO_EVENT
2024-05-29 04:00:00+00:00  1.650181         0       NO_EVENT
2024-05-30 04:00:00+00:00  0.901661         0       NO_EVENT
2024-05-31 04:00:00+00:00  0.910651         0       NO_EVENT
2024-06-03 04:00:00+00:00  1.067262         0       NO_EVENT
2024-06-04 04:00:00+00:00  1.420098         0       NO_EVENT
2024-06-05 04:00:00+00:00  1.344758         0       NO_EVENT
2024-06-06 04:00:00+00:00  1.323397         0       NO_EVENT
2024-06-07 04:00:00+00:00  1.217857         0       NO_EVENT
2024-06-10 04:00:00+00:00  1.903806         0       NO_EVENT
2024-06-11 04:00:00+00:00  2.202471         0       NO_EVENT
2024-06-12 04:00:00+00:00  2.473562         0       NO_EVENT
2024-06-13 04:00:00+00:00  2.508991         0       NO_EVENT
2024-06-14 04:00:00+00:00  2.559543         0       NO_EVENT
2024-06-17 04:00:00+00:00  2.881451         0       NO_EVENT
2024-06-18 04:00:00+00:00  3.030748         0       NO_EVENT
2024-06-20 04:00:00+00:00  2.510181         0       NO_EVENT
2024-06-21 04:00:00+00:00  2.710273         0       NO_EVENT
2024-06-24 04:00:00+00:00  2.672408         0       NO_EVENT
2024-06-25 04:00:00+00:00  2.798975         0       NO_EVENT
2024-06-26 04:00:00+00:00  3.013702         0       NO_EVENT
2024-06-27 04:00:00+00:00  2.899445         0       NO_EVENT
2024-06-28 04:00:00+00:00  2.459034         0       NO_EVENT
2024-07-01 04:00:00+00:00  3.150144         0       NO_EVENT
2024-07-02 04:00:00+00:00  2.809570         0       NO_EVENT
2024-07-03 04:00:00+00:00  2.883373         0       NO_EVENT
2024-07-05 04:00:00+00:00  2.635932         0       NO_EVENT
2024-07-08 04:00:00+00:00  2.136986         0       NO_EVENT
2024-07-09 04:00:00+00:00  1.957077         0       NO_EVENT
2024-07-10 04:00:00+00:00  1.790237         0       NO_EVENT
2024-07-11 04:00:00+00:00  1.442537         0       NO_EVENT
2024-07-12 04:00:00+00:00  1.414026         0       NO_EVENT
2024-07-15 04:00:00+00:00  1.541172         0       NO_EVENT
2024-07-16 04:00:00+00:00  1.501688         0       NO_EVENT
2024-07-17 04:00:00+00:00  2.401320         0       NO_EVENT
2024-07-18 04:00:00+00:00  2.495281         0       NO_EVENT
2024-07-19 04:00:00+00:00  2.616855         0       NO_EVENT
2024-07-22 04:00:00+00:00  2.571618         0       NO_EVENT
2024-07-23 04:00:00+00:00  2.754481         0       NO_EVENT
2024-07-24 04:00:00+00:00  2.685603         0       NO_EVENT
2024-07-25 04:00:00+00:00  2.645581         0       NO_EVENT
2024-07-26 04:00:00+00:00  2.804040         0       NO_EVENT
2024-07-29 04:00:00+00:00  2.862957         0       NO_EVENT
2024-07-30 04:00:00+00:00  2.778260         0       NO_EVENT
2024-07-31 04:00:00+00:00  2.215495         0       NO_EVENT
2024-08-01 04:00:00+00:00  2.888306         0       NO_EVENT
2024-08-02 04:00:00+00:00  2.538630         0       NO_EVENT
2024-08-05 04:00:00+00:00  1.867306         0       NO_EVENT
2024-08-06 04:00:00+00:00  2.317203         0       NO_EVENT
2024-08-07 04:00:00+00:00  2.354380         0       NO_EVENT
2024-08-08 04:00:00+00:00  2.050264         0       NO_EVENT
2024-08-09 04:00:00+00:00  2.296461         0       NO_EVENT
2024-08-12 04:00:00+00:00  2.169082         0       NO_EVENT
2024-08-13 04:00:00+00:00  2.178640         0       NO_EVENT
2024-08-14 04:00:00+00:00  2.304017         0       NO_EVENT
2024-08-15 04:00:00+00:00  2.062058         0       NO_EVENT
2024-08-16 04:00:00+00:00  1.886742         0       NO_EVENT
2024-08-19 04:00:00+00:00  1.599817         0       NO_EVENT
2024-08-20 04:00:00+00:00  1.655120         0       NO_EVENT
2024-08-21 04:00:00+00:00  1.542944         0       NO_EVENT
2024-08-22 04:00:00+00:00  1.574590         0       NO_EVENT
2024-08-23 04:00:00+00:00  1.424656         0       NO_EVENT
2024-08-26 04:00:00+00:00  1.591906         0       NO_EVENT
2024-08-27 04:00:00+00:00  1.572007         0       NO_EVENT
2024-08-28 04:00:00+00:00  1.690434         0       NO_EVENT
2024-08-29 04:00:00+00:00  1.833934         0       NO_EVENT
2024-08-30 04:00:00+00:00  1.801122         0       NO_EVENT
2024-09-03 04:00:00+00:00  2.189319         0       NO_EVENT
2024-09-04 04:00:00+00:00  1.931177         0       NO_EVENT
2024-09-05 04:00:00+00:00  1.990870         0       NO_EVENT
2024-09-06 04:00:00+00:00  2.031502         0       NO_EVENT
2024-09-09 04:00:00+00:00  1.954962         0       NO_EVENT
2024-09-10 04:00:00+00:00  1.994660         0       NO_EVENT
2024-09-11 04:00:00+00:00  1.911721         0       NO_EVENT
2024-09-12 04:00:00+00:00  2.002289         0       NO_EVENT
2024-09-13 04:00:00+00:00  2.041658         0       NO_EVENT
2024-09-16 04:00:00+00:00  2.077338         0       NO_EVENT
2024-09-17 04:00:00+00:00  2.286355         0       NO_EVENT
2024-09-18 04:00:00+00:00  2.263555         0       NO_EVENT
2024-09-19 04:00:00+00:00  2.061355         0       NO_EVENT
2024-09-20 04:00:00+00:00  1.974387         0       NO_EVENT
2024-09-23 04:00:00+00:00  1.858184         0       NO_EVENT
2024-09-24 04:00:00+00:00  1.603418         0       NO_EVENT
2024-09-25 04:00:00+00:00  1.496701         0       NO_EVENT
2024-09-26 04:00:00+00:00  1.151205         0       NO_EVENT
2024-09-27 04:00:00+00:00  1.208376         0       NO_EVENT
2024-09-30 04:00:00+00:00  1.306292         0       NO_EVENT
2024-10-01 04:00:00+00:00  1.198259         0       NO_EVENT
2024-10-02 04:00:00+00:00  1.063864         0       NO_EVENT
2024-10-03 04:00:00+00:00  0.865221         0       NO_EVENT
2024-10-04 04:00:00+00:00  0.385937         0       NO_EVENT
2024-10-07 04:00:00+00:00  0.141411         0       NO_EVENT
2024-10-08 04:00:00+00:00  0.227109         0       NO_EVENT
2024-10-09 04:00:00+00:00  0.430474         0       NO_EVENT
2024-10-10 04:00:00+00:00  0.762700         0       NO_EVENT
2024-10-11 04:00:00+00:00  0.566963         0       NO_EVENT
2024-10-14 04:00:00+00:00  0.821054         0       NO_EVENT
2024-10-15 04:00:00+00:00  1.300872         0       NO_EVENT
2024-10-16 04:00:00+00:00  1.231562         0       NO_EVENT
2024-10-17 04:00:00+00:00  1.245201         0       NO_EVENT
2024-10-18 04:00:00+00:00  1.312729         0       NO_EVENT
2024-10-21 04:00:00+00:00  1.223101         0       NO_EVENT
2024-10-22 04:00:00+00:00  1.761773         0       NO_EVENT
2024-10-23 04:00:00+00:00  1.718354         0       NO_EVENT
2024-10-24 04:00:00+00:00  1.689290         0       NO_EVENT
2024-10-25 04:00:00+00:00  1.652242         0       NO_EVENT
2024-10-28 04:00:00+00:00  1.381122         0       NO_EVENT
2024-10-29 04:00:00+00:00  1.214685         0       NO_EVENT
2024-10-30 04:00:00+00:00  2.241108         0       NO_EVENT
2024-10-31 04:00:00+00:00  1.533048         0       NO_EVENT
2024-11-01 04:00:00+00:00  1.803228         0       NO_EVENT
2024-11-04 05:00:00+00:00  1.794767         0       NO_EVENT
2024-11-05 05:00:00+00:00  1.846496         0       NO_EVENT
2024-11-06 05:00:00+00:00  1.965363         0       NO_EVENT
2024-11-07 05:00:00+00:00  1.884516         0       NO_EVENT
2024-11-08 05:00:00+00:00  1.880678         0       NO_EVENT
2024-11-11 05:00:00+00:00  1.745611         0       NO_EVENT
2024-11-12 05:00:00+00:00  2.133881         0       NO_EVENT
2024-11-13 05:00:00+00:00  2.450098         0       NO_EVENT
2024-11-14 05:00:00+00:00  2.528190         0       NO_EVENT
2024-11-15 05:00:00+00:00  2.310856         0       NO_EVENT
2024-11-18 05:00:00+00:00  2.105572         0       NO_EVENT
2024-11-19 05:00:00+00:00  2.146919         0       NO_EVENT
2024-11-20 05:00:00+00:00  2.158021         0       NO_EVENT
2024-11-21 05:00:00+00:00  2.064241         0       NO_EVENT
2024-11-22 05:00:00+00:00  2.158414         0       NO_EVENT
2024-11-25 05:00:00+00:00  2.062068         0       NO_EVENT
2024-11-26 05:00:00+00:00  2.572231         0       NO_EVENT
2024-11-27 05:00:00+00:00  2.466537         0       NO_EVENT
2024-11-29 05:00:00+00:00  2.422911         0       NO_EVENT
2024-12-02 05:00:00+00:00  2.411973         0       NO_EVENT
2024-12-03 05:00:00+00:00  2.415775         0       NO_EVENT
2024-12-04 05:00:00+00:00  2.516162         0       NO_EVENT
2024-12-05 05:00:00+00:00  2.832078         0       NO_EVENT
2024-12-06 05:00:00+00:00  3.002574         0       NO_EVENT
2024-12-09 05:00:00+00:00  3.489555         0       NO_EVENT
2024-12-10 05:00:00+00:00  3.541650         0       NO_EVENT
2024-12-11 05:00:00+00:00  3.583451         0       NO_EVENT
2024-12-12 05:00:00+00:00  3.554248         0       NO_EVENT
2024-12-13 05:00:00+00:00  3.647016         0       NO_EVENT
2024-12-16 05:00:00+00:00  3.778358         0       NO_EVENT
2024-12-17 05:00:00+00:00  3.932869         0       NO_EVENT
2024-12-18 05:00:00+00:00  3.519209         0       NO_EVENT
2024-12-19 05:00:00+00:00  3.613994         0       NO_EVENT
2024-12-20 05:00:00+00:00  3.557735         0       NO_EVENT
2024-12-23 05:00:00+00:00  3.215476         0       NO_EVENT
2024-12-24 05:00:00+00:00  3.244701         0       NO_EVENT
2024-12-26 05:00:00+00:00  3.248548         0       NO_EVENT
2024-12-27 05:00:00+00:00  2.978961         0       NO_EVENT
2024-12-30 05:00:00+00:00  2.918547         0       NO_EVENT
2024-12-31 05:00:00+00:00  2.880271         0       NO_EVENT
2025-01-02 05:00:00+00:00  2.781826         0       NO_EVENT
2025-01-03 05:00:00+00:00  2.687294         0       NO_EVENT
2025-01-06 05:00:00+00:00  2.613139         0       NO_EVENT
2025-01-07 05:00:00+00:00  2.538887         0       NO_EVENT
2025-01-08 05:00:00+00:00  2.867391         0       NO_EVENT
2025-01-10 05:00:00+00:00  2.961217         0       NO_EVENT
2025-01-13 05:00:00+00:00  2.829721         0       NO_EVENT
2025-01-14 05:00:00+00:00  2.829389         0       NO_EVENT
2025-01-15 05:00:00+00:00  2.960582         0       NO_EVENT
2025-01-16 05:00:00+00:00  2.965962         0       NO_EVENT
2025-01-17 05:00:00+00:00  2.944236         0       NO_EVENT
2025-01-21 05:00:00+00:00  2.874889         0       NO_EVENT
2025-01-22 05:00:00+00:00  3.333625         0       NO_EVENT
2025-01-23 05:00:00+00:00  3.363060         0       NO_EVENT
2025-01-24 05:00:00+00:00  3.272016         0       NO_EVENT
2025-01-27 05:00:00+00:00  3.333809         0       NO_EVENT
2025-01-28 05:00:00+00:00  3.732639         0       NO_EVENT
2025-01-29 05:00:00+00:00  3.413037         0       NO_EVENT
2025-01-30 05:00:00+00:00  2.511423         0       NO_EVENT
2025-01-31 05:00:00+00:00  2.638369         0       NO_EVENT

In [61]:
position = 0

position_df = pd.DataFrame(trading_zscore.copy())
position_df = position_df.rename(columns={0: "zscore"})

position_df["position"] = 0
position_df["event"] = "NO_EVENT"

entry_day = None

# Formation-period thresholds
lower_threshold = formation_zscores[0][8]
upper_threshold = formation_zscores[0][9]
formation_median = formation_zscores[0][7].quantile(0.5)

for i in range(len(position_df)):

    current_zscore = position_df.iloc[i, 0]

    # -------------------------
    # FLAT: look for new entry
    # -------------------------
    if position == 0:

        if current_zscore < lower_threshold:
            position = 1
            entry_day = i

            position_df.loc[position_df.index[i], "event"] = "LONG_ENTRY"

        elif current_zscore > upper_threshold:
            position = -1
            entry_day = i

            position_df.loc[position_df.index[i], "event"] = "SHORT_ENTRY"


    # -------------------------
    # LONG POSITION
    # -------------------------
    elif position == 1:

        # Mean reversion
        if current_zscore >= formation_median:
            position = 0
            entry_day = None

            position_df.loc[
                position_df.index[i], "event"
            ] = "LONG_MEAN_EXIT"

        # Stop loss
        elif current_zscore <= lower_threshold - 1:
            position = 2
            entry_day = None

            position_df.loc[
                position_df.index[i], "event"
            ] = "LONG_STOPLOSS"

        # Maximum holding period
        elif i - entry_day >= max_holding_period:
            position = 0
            entry_day = None

            position_df.loc[
                position_df.index[i], "event"
            ] = "LONG_MAX_HOLDING"


    # -------------------------
    # SHORT POSITION
    # -------------------------
    elif position == -1:

        # Mean reversion
        if current_zscore <= formation_median:
            position = 0
            entry_day = None

            position_df.loc[
                position_df.index[i], "event"
            ] = "SHORT_MEAN_EXIT"

        # Stop loss
        elif current_zscore >= upper_threshold + 1:
            position = -2
            entry_day = None

            position_df.loc[
                position_df.index[i], "event"
            ] = "SHORT_STOPLOSS"

        # Maximum holding period
        elif i - entry_day >= max_holding_period:
            position = 0
            entry_day = None

            position_df.loc[
                position_df.index[i], "event"
            ] = "SHORT_MAX_HOLDING"


    # -------------------------
    # COOLDOWN AFTER LONG STOP
    # -------------------------
    elif position == 2:

        # Wait until z-score comes back
        # inside the long-entry region
        if current_zscore > lower_threshold:
            position = 0

            position_df.loc[
                position_df.index[i], "event"
            ] = "LONG_REENTRY_UNLOCK"


    # -------------------------
    # COOLDOWN AFTER SHORT STOP
    # -------------------------
    elif position == -2:

        # Wait until z-score comes back
        # inside the short-entry region
        if current_zscore < upper_threshold:
            position = 0

            position_df.loc[
                position_df.index[i], "event"
            ] = "SHORT_REENTRY_UNLOCK"


    # Store current state
    position_df.loc[
        position_df.index[i], "position"
    ] = position


print(
    f"Upper threshold: {upper_threshold}\n"
    f"Lower threshold: {lower_threshold}\n"
    f"Formation median: {formation_median}"
)

pd.set_option("display.max_rows", None)

position_df

Upper threshold: 2.4840177332105604
Lower threshold: -0.7962765530142031
Formation median: 0.8957413403422575

                             zscore  position                event
timestamp
2024-01-02 05:00:00+00:00  0.992365         0             NO_EVENT
2024-01-03 05:00:00+00:00  1.206050         0             NO_EVENT
2024-01-04 05:00:00+00:00  1.036833         0             NO_EVENT
2024-01-05 05:00:00+00:00  0.847931         0             NO_EVENT
2024-01-08 05:00:00+00:00  0.628688         0             NO_EVENT
2024-01-09 05:00:00+00:00  0.462826         0             NO_EVENT
2024-01-10 05:00:00+00:00  0.825785         0             NO_EVENT
2024-01-11 05:00:00+00:00  0.944591         0             NO_EVENT
2024-01-12 05:00:00+00:00  1.217545         0             NO_EVENT
2024-01-16 05:00:00+00:00  0.447231         0             NO_EVENT
2024-01-17 05:00:00+00:00  0.311233         0             NO_EVENT
2024-01-18 05:00:00+00:00  0.334143         0             NO_EVENT
2024-01-19 05:00:00+00:00 -0.257636         0             NO_EVENT
2024-01-22 05:00:00+00:00  0.068149         0             NO_EVENT
2024-01-23 05:00:00+00:00  0.158858         0             NO_EVENT
2024-01-24 05:00:00+00:00 -0.366995         0             NO_EVENT
2024-01-25 05:00:00+00:00 -0.405469         0             NO_EVENT
2024-01-26 05:00:00+00:00 -0.231808         0             NO_EVENT
2024-01-29 05:00:00+00:00 -0.011171         0             NO_EVENT
2024-01-30 05:00:00+00:00  0.342481         0             NO_EVENT
2024-01-31 05:00:00+00:00  0.151718         0             NO_EVENT
2024-02-01 05:00:00+00:00  0.235859         0             NO_EVENT
2024-02-02 05:00:00+00:00  0.067631         0             NO_EVENT
2024-02-05 05:00:00+00:00  0.056733         0             NO_EVENT
2024-02-06 05:00:00+00:00  0.496152         0             NO_EVENT
2024-02-07 05:00:00+00:00  0.668081         0             NO_EVENT
2024-02-08 05:00:00+00:00  0.782124         0             NO_EVENT
2024-02-09 05:00:00+00:00  0.852743         0             NO_EVENT
2024-02-12 05:00:00+00:00  0.652172         0             NO_EVENT
2024-02-13 05:00:00+00:00  0.272282         0             NO_EVENT
2024-02-14 05:00:00+00:00 -0.088883         0             NO_EVENT
2024-02-15 05:00:00+00:00 -0.084982         0             NO_EVENT
2024-02-16 05:00:00+00:00  0.005516         0             NO_EVENT
2024-02-20 05:00:00+00:00  0.525598         0             NO_EVENT
2024-02-21 05:00:00+00:00  0.596369         0             NO_EVENT
2024-02-22 05:00:00+00:00 -0.215478         0             NO_EVENT
2024-02-23 05:00:00+00:00  0.102790         0             NO_EVENT
2024-02-26 05:00:00+00:00  0.011279         0             NO_EVENT
2024-02-27 05:00:00+00:00 -0.132416         0             NO_EVENT
2024-02-28 05:00:00+00:00 -0.017908         0             NO_EVENT
2024-02-29 05:00:00+00:00 -0.881727         1           LONG_ENTRY
2024-03-01 05:00:00+00:00 -1.512943         1             NO_EVENT
2024-03-04 05:00:00+00:00 -1.729043         1             NO_EVENT
2024-03-05 05:00:00+00:00 -2.267345         2        LONG_STOPLOSS
2024-03-06 05:00:00+00:00 -2.672390         2             NO_EVENT
2024-03-07 05:00:00+00:00 -2.392503         2             NO_EVENT
2024-03-08 05:00:00+00:00 -2.234451         2             NO_EVENT
2024-03-11 04:00:00+00:00 -1.673087         2             NO_EVENT
2024-03-12 04:00:00+00:00 -1.490658         2             NO_EVENT
2024-03-13 04:00:00+00:00 -0.939304         2             NO_EVENT
2024-03-14 04:00:00+00:00  0.056248         0  LONG_REENTRY_UNLOCK
2024-03-15 04:00:00+00:00 -0.618906         0             NO_EVENT
2024-03-18 04:00:00+00:00 -0.549238         0             NO_EVENT
2024-03-19 04:00:00+00:00  0.280642         0             NO_EVENT
2024-03-20 04:00:00+00:00  0.570681         0             NO_EVENT
2024-03-21 04:00:00+00:00  0.830179         0             NO_EVENT
2024-03-22 04:00:00+00:00  0.733025         0             NO_EVENT
2024-03-25 04:00:00+00:00  0.538784         0             NO_EVENT
2024-03-26 04:00:00+00:00  0.537049         0             NO_EVENT
2024-03-27 04:00:00+00:00  0.406149         0             NO_EVENT
2024-03-28 04:00:00+00:00  0.310706         0             NO_EVENT
2024-04-01 04:00:00+00:00  0.284364         0             NO_EVENT
2024-04-02 04:00:00+00:00  0.468514         0             NO_EVENT
2024-04-03 04:00:00+00:00  0.278028         0             NO_EVENT
2024-04-04 04:00:00+00:00  1.211548         0             NO_EVENT
2024-04-05 04:00:00+00:00  1.232659         0             NO_EVENT
2024-04-08 04:00:00+00:00  1.225253         0             NO_EVENT
2024-04-09 04:00:00+00:00  1.237958         0             NO_EVENT
2024-04-10 04:00:00+00:00  1.355133         0             NO_EVENT
2024-04-11 04:00:00+00:00  1.327908         0             NO_EVENT
2024-04-12 04:00:00+00:00  1.559860         0             NO_EVENT
2024-04-15 04:00:00+00:00  1.391590         0             NO_EVENT
2024-04-16 04:00:00+00:00  1.211605         0             NO_EVENT
2024-04-17 04:00:00+00:00  1.747182         0             NO_EVENT
2024-04-18 04:00:00+00:00  1.328214         0             NO_EVENT
2024-04-19 04:00:00+00:00  1.684211         0             NO_EVENT
2024-04-22 04:00:00+00:00  1.623364         0             NO_EVENT
2024-04-23 04:00:00+00:00  1.663305         0             NO_EVENT
2024-04-24 04:00:00+00:00  1.763259         0             NO_EVENT
2024-04-25 04:00:00+00:00  1.169750         0             NO_EVENT
2024-04-26 04:00:00+00:00  1.240764         0             NO_EVENT
2024-04-29 04:00:00+00:00  0.862047         0             NO_EVENT
2024-04-30 04:00:00+00:00  0.409488         0             NO_EVENT
2024-05-01 04:00:00+00:00  1.642214         0             NO_EVENT
2024-05-02 04:00:00+00:00  1.636939         0             NO_EVENT
2024-05-03 04:00:00+00:00  1.719169         0             NO_EVENT
2024-05-06 04:00:00+00:00  1.662921         0             NO_EVENT
2024-05-07 04:00:00+00:00  1.565468         0             NO_EVENT
2024-05-08 04:00:00+00:00  1.671797         0             NO_EVENT
2024-05-09 04:00:00+00:00  1.832313         0             NO_EVENT
2024-05-10 04:00:00+00:00  1.967592         0             NO_EVENT
2024-05-13 04:00:00+00:00  2.010437         0             NO_EVENT
2024-05-14 04:00:00+00:00  1.951298         0             NO_EVENT
2024-05-15 04:00:00+00:00  1.786765         0             NO_EVENT
2024-05-16 04:00:00+00:00  1.487648         0             NO_EVENT
2024-05-17 04:00:00+00:00  1.323567         0             NO_EVENT
2024-05-20 04:00:00+00:00  1.420202         0             NO_EVENT
2024-05-21 04:00:00+00:00  1.695163         0             NO_EVENT
2024-05-22 04:00:00+00:00  1.697633         0             NO_EVENT
2024-05-23 04:00:00+00:00  1.886836         0             NO_EVENT
2024-05-24 04:00:00+00:00  1.615895         0             NO_EVENT
2024-05-28 04:00:00+00:00  1.261565         0             NO_EVENT
2024-05-29 04:00:00+00:00  1.650181         0             NO_EVENT
2024-05-30 04:00:00+00:00  0.901661         0             NO_EVENT
2024-05-31 04:00:00+00:00  0.910651         0             NO_EVENT
2024-06-03 04:00:00+00:00  1.067262         0             NO_EVENT
2024-06-04 04:00:00+00:00  1.420098         0             NO_EVENT
2024-06-05 04:00:00+00:00  1.344758         0             NO_EVENT
2024-06-06 04:00:00+00:00  1.323397         0             NO_EVENT
2024-06-07 04:00:00+00:00  1.217857         0             NO_EVENT
2024-06-10 04:00:00+00:00  1.903806         0             NO_EVENT
2024-06-11 04:00:00+00:00  2.202471         0             NO_EVENT
2024-06-12 04:00:00+00:00  2.473562         0             NO_EVENT
2024-06-13 04:00:00+00:00  2.508991        -1          SHORT_ENTRY
2024-06-14 04:00:00+00:00  2.559543        -1             NO_EVENT
2024-06-17 04:00:00+00:00  2.881451        -1             NO_EVENT
2024-06-18 04:00:00+00:00  3.030748        -1             NO_EVENT
2024-06-20 04:00:00+00:00  2.510181        -1             NO_EVENT
2024-06-21 04:00:00+00:00  2.710273        -1             NO_EVENT
2024-06-24 04:00:00+00:00  2.672408        -1             NO_EVENT
2024-06-25 04:00:00+00:00  2.798975        -1             NO_EVENT
2024-06-26 04:00:00+00:00  3.013702        -1             NO_EVENT
2024-06-27 04:00:00+00:00  2.899445        -1             NO_EVENT
2024-06-28 04:00:00+00:00  2.459034        -1             NO_EVENT
2024-07-01 04:00:00+00:00  3.150144        -1             NO_EVENT
2024-07-02 04:00:00+00:00  2.809570        -1             NO_EVENT
2024-07-03 04:00:00+00:00  2.883373        -1             NO_EVENT
2024-07-05 04:00:00+00:00  2.635932        -1             NO_EVENT
2024-07-08 04:00:00+00:00  2.136986        -1             NO_EVENT
2024-07-09 04:00:00+00:00  1.957077        -1             NO_EVENT
2024-07-10 04:00:00+00:00  1.790237        -1             NO_EVENT
2024-07-11 04:00:00+00:00  1.442537        -1             NO_EVENT
2024-07-12 04:00:00+00:00  1.414026        -1             NO_EVENT
2024-07-15 04:00:00+00:00  1.541172        -1             NO_EVENT
2024-07-16 04:00:00+00:00  1.501688        -1             NO_EVENT
2024-07-17 04:00:00+00:00  2.401320        -1             NO_EVENT
2024-07-18 04:00:00+00:00  2.495281        -1             NO_EVENT
2024-07-19 04:00:00+00:00  2.616855        -1             NO_EVENT
2024-07-22 04:00:00+00:00  2.571618        -1             NO_EVENT
2024-07-23 04:00:00+00:00  2.754481        -1             NO_EVENT
2024-07-24 04:00:00+00:00  2.685603        -1             NO_EVENT
2024-07-25 04:00:00+00:00  2.645581        -1             NO_EVENT
2024-07-26 04:00:00+00:00  2.804040        -1             NO_EVENT
2024-07-29 04:00:00+00:00  2.862957        -1             NO_EVENT
2024-07-30 04:00:00+00:00  2.778260        -1             NO_EVENT
2024-07-31 04:00:00+00:00  2.215495        -1             NO_EVENT
2024-08-01 04:00:00+00:00  2.888306        -1             NO_EVENT
2024-08-02 04:00:00+00:00  2.538630        -1             NO_EVENT
2024-08-05 04:00:00+00:00  1.867306        -1             NO_EVENT
2024-08-06 04:00:00+00:00  2.317203        -1             NO_EVENT
2024-08-07 04:00:00+00:00  2.354380        -1             NO_EVENT
2024-08-08 04:00:00+00:00  2.050264        -1             NO_EVENT
2024-08-09 04:00:00+00:00  2.296461        -1             NO_EVENT
2024-08-12 04:00:00+00:00  2.169082        -1             NO_EVENT
2024-08-13 04:00:00+00:00  2.178640        -1             NO_EVENT
2024-08-14 04:00:00+00:00  2.304017        -1             NO_EVENT
2024-08-15 04:00:00+00:00  2.062058        -1             NO_EVENT
2024-08-16 04:00:00+00:00  1.886742        -1             NO_EVENT
2024-08-19 04:00:00+00:00  1.599817        -1             NO_EVENT
2024-08-20 04:00:00+00:00  1.655120        -1             NO_EVENT
2024-08-21 04:00:00+00:00  1.542944        -1             NO_EVENT
2024-08-22 04:00:00+00:00  1.574590        -1             NO_EVENT
2024-08-23 04:00:00+00:00  1.424656        -1             NO_EVENT
2024-08-26 04:00:00+00:00  1.591906        -1             NO_EVENT
2024-08-27 04:00:00+00:00  1.572007        -1             NO_EVENT
2024-08-28 04:00:00+00:00  1.690434        -1             NO_EVENT
2024-08-29 04:00:00+00:00  1.833934        -1             NO_EVENT
2024-08-30 04:00:00+00:00  1.801122        -1             NO_EVENT
2024-09-03 04:00:00+00:00  2.189319        -1             NO_EVENT
2024-09-04 04:00:00+00:00  1.931177        -1             NO_EVENT
2024-09-05 04:00:00+00:00  1.990870         0    SHORT_MAX_HOLDING
2024-09-06 04:00:00+00:00  2.031502         0             NO_EVENT
2024-09-09 04:00:00+00:00  1.954962         0             NO_EVENT
2024-09-10 04:00:00+00:00  1.994660         0             NO_EVENT
2024-09-11 04:00:00+00:00  1.911721         0             NO_EVENT
2024-09-12 04:00:00+00:00  2.002289         0             NO_EVENT
2024-09-13 04:00:00+00:00  2.041658         0             NO_EVENT
2024-09-16 04:00:00+00:00  2.077338         0             NO_EVENT
2024-09-17 04:00:00+00:00  2.286355         0             NO_EVENT
2024-09-18 04:00:00+00:00  2.263555         0             NO_EVENT
2024-09-19 04:00:00+00:00  2.061355         0             NO_EVENT
2024-09-20 04:00:00+00:00  1.974387         0             NO_EVENT
2024-09-23 04:00:00+00:00  1.858184         0             NO_EVENT
2024-09-24 04:00:00+00:00  1.603418         0             NO_EVENT
2024-09-25 04:00:00+00:00  1.496701         0             NO_EVENT
2024-09-26 04:00:00+00:00  1.151205         0             NO_EVENT
2024-09-27 04:00:00+00:00  1.208376         0             NO_EVENT
2024-09-30 04:00:00+00:00  1.306292         0             NO_EVENT
2024-10-01 04:00:00+00:00  1.198259         0             NO_EVENT
2024-10-02 04:00:00+00:00  1.063864         0             NO_EVENT
2024-10-03 04:00:00+00:00  0.865221         0             NO_EVENT
2024-10-04 04:00:00+00:00  0.385937         0             NO_EVENT
2024-10-07 04:00:00+00:00  0.141411         0             NO_EVENT
2024-10-08 04:00:00+00:00  0.227109         0             NO_EVENT
2024-10-09 04:00:00+00:00  0.430474         0             NO_EVENT
2024-10-10 04:00:00+00:00  0.762700         0             NO_EVENT
2024-10-11 04:00:00+00:00  0.566963         0             NO_EVENT
2024-10-14 04:00:00+00:00  0.821054         0             NO_EVENT
2024-10-15 04:00:00+00:00  1.300872         0             NO_EVENT
2024-10-16 04:00:00+00:00  1.231562         0             NO_EVENT
2024-10-17 04:00:00+00:00  1.245201         0             NO_EVENT
2024-10-18 04:00:00+00:00  1.312729         0             NO_EVENT
2024-10-21 04:00:00+00:00  1.223101         0             NO_EVENT
2024-10-22 04:00:00+00:00  1.761773         0             NO_EVENT
2024-10-23 04:00:00+00:00  1.718354         0             NO_EVENT
2024-10-24 04:00:00+00:00  1.689290         0             NO_EVENT
2024-10-25 04:00:00+00:00  1.652242         0             NO_EVENT
2024-10-28 04:00:00+00:00  1.381122         0             NO_EVENT
2024-10-29 04:00:00+00:00  1.214685         0             NO_EVENT
2024-10-30 04:00:00+00:00  2.241108         0             NO_EVENT
2024-10-31 04:00:00+00:00  1.533048         0             NO_EVENT
2024-11-01 04:00:00+00:00  1.803228         0             NO_EVENT
2024-11-04 05:00:00+00:00  1.794767         0             NO_EVENT
2024-11-05 05:00:00+00:00  1.846496         0             NO_EVENT
2024-11-06 05:00:00+00:00  1.965363         0             NO_EVENT
2024-11-07 05:00:00+00:00  1.884516         0             NO_EVENT
2024-11-08 05:00:00+00:00  1.880678         0             NO_EVENT
2024-11-11 05:00:00+00:00  1.745611         0             NO_EVENT
2024-11-12 05:00:00+00:00  2.133881         0             NO_EVENT
2024-11-13 05:00:00+00:00  2.450098         0             NO_EVENT
2024-11-14 05:00:00+00:00  2.528190        -1          SHORT_ENTRY
2024-11-15 05:00:00+00:00  2.310856        -1             NO_EVENT
2024-11-18 05:00:00+00:00  2.105572        -1             NO_EVENT
2024-11-19 05:00:00+00:00  2.146919        -1             NO_EVENT
2024-11-20 05:00:00+00:00  2.158021        -1             NO_EVENT
2024-11-21 05:00:00+00:00  2.064241        -1             NO_EVENT
2024-11-22 05:00:00+00:00  2.158414        -1             NO_EVENT
2024-11-25 05:00:00+00:00  2.062068        -1             NO_EVENT
2024-11-26 05:00:00+00:00  2.572231        -1             NO_EVENT
2024-11-27 05:00:00+00:00  2.466537        -1             NO_EVENT
2024-11-29 05:00:00+00:00  2.422911        -1             NO_EVENT
2024-12-02 05:00:00+00:00  2.411973        -1             NO_EVENT
2024-12-03 05:00:00+00:00  2.415775        -1             NO_EVENT
2024-12-04 05:00:00+00:00  2.516162        -1             NO_EVENT
2024-12-05 05:00:00+00:00  2.832078        -1             NO_EVENT
2024-12-06 05:00:00+00:00  3.002574        -1             NO_EVENT
2024-12-09 05:00:00+00:00  3.489555        -2       SHORT_STOPLOSS
2024-12-10 05:00:00+00:00  3.541650        -2             NO_EVENT
2024-12-11 05:00:00+00:00  3.583451        -2             NO_EVENT
2024-12-12 05:00:00+00:00  3.554248        -2             NO_EVENT
2024-12-13 05:00:00+00:00  3.647016        -2             NO_EVENT
2024-12-16 05:00:00+00:00  3.778358        -2             NO_EVENT
2024-12-17 05:00:00+00:00  3.932869        -2             NO_EVENT
2024-12-18 05:00:00+00:00  3.519209        -2             NO_EVENT
2024-12-19 05:00:00+00:00  3.613994        -2             NO_EVENT
2024-12-20 05:00:00+00:00  3.557735        -2             NO_EVENT
2024-12-23 05:00:00+00:00  3.215476        -2             NO_EVENT
2024-12-24 05:00:00+00:00  3.244701        -2             NO_EVENT
2024-12-26 05:00:00+00:00  3.248548        -2             NO_EVENT
2024-12-27 05:00:00+00:00  2.978961        -2             NO_EVENT
2024-12-30 05:00:00+00:00  2.918547        -2             NO_EVENT
2024-12-31 05:00:00+00:00  2.880271        -2             NO_EVENT
2025-01-02 05:00:00+00:00  2.781826        -2             NO_EVENT
2025-01-03 05:00:00+00:00  2.687294        -2             NO_EVENT
2025-01-06 05:00:00+00:00  2.613139        -2             NO_EVENT
2025-01-07 05:00:00+00:00  2.538887        -2             NO_EVENT
2025-01-08 05:00:00+00:00  2.867391        -2             NO_EVENT
2025-01-10 05:00:00+00:00  2.961217        -2             NO_EVENT
2025-01-13 05:00:00+00:00  2.829721        -2             NO_EVENT
2025-01-14 05:00:00+00:00  2.829389        -2             NO_EVENT
2025-01-15 05:00:00+00:00  2.960582        -2             NO_EVENT
2025-01-16 05:00:00+00:00  2.965962        -2             NO_EVENT
2025-01-17 05:00:00+00:00  2.944236        -2             NO_EVENT
2025-01-21 05:00:00+00:00  2.874889        -2             NO_EVENT
2025-01-22 05:00:00+00:00  3.333625        -2             NO_EVENT
2025-01-23 05:00:00+00:00  3.363060        -2             NO_EVENT
2025-01-24 05:00:00+00:00  3.272016        -2             NO_EVENT
2025-01-27 05:00:00+00:00  3.333809        -2             NO_EVENT
2025-01-28 05:00:00+00:00  3.732639        -2             NO_EVENT
2025-01-29 05:00:00+00:00  3.413037        -2             NO_EVENT
2025-01-30 05:00:00+00:00  2.511423        -2             NO_EVENT
2025-01-31 05:00:00+00:00  2.638369        -2             NO_EVENT

In [62]:
#work for construct_trades()-pair each entry with the next corresponding exit
import numpy as np
trades=[]
entry_day = None
entry_zscore = None
direction = None
for date,row in position_df.iterrows():
    event=row["event"]
    #ENTRY
    if event=="LONG_ENTRY":
        entry_day=date
        entry_zscore=row["zscore"]
        direction="LONG"
    elif event=="SHORT_ENTRY":
        entry_day=date
        entry_zscore=row["zscore"]
        direction="SHORT"
    #EXIT
    elif event in [
    "LONG_MEAN_EXIT",
    "LONG_STOPLOSS",
    "LONG_MAX_HOLDING",
    "SHORT_MEAN_EXIT",
    "SHORT_STOPLOSS",
    "SHORT_MAX_HOLDING"
]:

        if direction == "LONG" and event.startswith("LONG_"):
            pass

        elif direction == "SHORT" and event.startswith("SHORT_"):
            pass

        else:
            continue

        trade = {
            "trade_id": len(trades) + 1,
            "direction": direction,
            "entry_date": entry_day,
            "exit_date": date,
            "entry_zscore": entry_zscore,
            "exit_zscore": row["zscore"],
            "exit_reason": event,
            "holding_period": (date - entry_day).days
        }

        trades.append(trade)

        entry_day = None
        entry_zscore = None
        direction = None
            
trade_df=pd.DataFrame(trades)
trade_df

,trade_id,direction,entry_date,exit_date,entry_zscore,exit_zscore,exit_reason,holding_period
0,1,LONG,2024-02-29 05:00:00+00:00,2024-03-05 05:00:00+00:00,-0.881727,-2.267345,LONG_STOPLOSS,5
1,2,SHORT,2024-06-13 04:00:00+00:00,2024-09-05 04:00:00+00:00,2.508991,1.990870,SHORT_MAX_HOLDING,84
2,3,SHORT,2024-11-14 05:00:00+00:00,2024-12-09 05:00:00+00:00,2.528190,3.489555,SHORT_STOPLOSS,25

In [63]:
import pandas as pd


def construct_trades(position_df):
    """
    Pair each entry signal with the next corresponding exit signal
    and construct a trade-level DataFrame.

    Holding period is measured in trading days.
    """

    trades = []

    entry_day = None
    entry_zscore = None
    direction = None

    for date, row in position_df.iterrows():

        event = row["event"]

        # ENTRY
        if event == "LONG_ENTRY":

            entry_day = date
            entry_zscore = row["zscore"]
            direction = "LONG"

        elif event == "SHORT_ENTRY":

            entry_day = date
            entry_zscore = row["zscore"]
            direction = "SHORT"

        # EXIT
        elif event in [
            "LONG_MEAN_EXIT",
            "LONG_STOPLOSS",
            "LONG_MAX_HOLDING",
            "SHORT_MEAN_EXIT",
            "SHORT_STOPLOSS",
            "SHORT_MAX_HOLDING"
        ]:

            # Make sure the exit matches the open position
            if direction == "LONG" and event.startswith("LONG_"):
                pass

            elif direction == "SHORT" and event.startswith("SHORT_"):
                pass

            else:
                continue

            # Calculate holding period in trading days
            holding_period = position_df.loc[entry_day:date].shape[0] - 1

            trade = {
                "trade_id": len(trades) + 1,
                "direction": direction,
                "entry_date": entry_day,
                "exit_date": date,
                "entry_zscore": entry_zscore,
                "exit_zscore": row["zscore"],
                "exit_reason": event,
                "holding_period": holding_period
            }

            trades.append(trade)

            # Reset after completing the trade
            entry_day = None
            entry_zscore = None
            direction = None

    trade_df = pd.DataFrame(trades)

    return trade_df
trade_df=construct_trades(position_df)
trade_df

,trade_id,direction,entry_date,exit_date,entry_zscore,exit_zscore,exit_reason,holding_period
0,1,LONG,2024-02-29 05:00:00+00:00,2024-03-05 05:00:00+00:00,-0.881727,-2.267345,LONG_STOPLOSS,3
1,2,SHORT,2024-06-13 04:00:00+00:00,2024-09-05 04:00:00+00:00,2.508991,1.990870,SHORT_MAX_HOLDING,57
2,3,SHORT,2024-11-14 05:00:00+00:00,2024-12-09 05:00:00+00:00,2.528190,3.489555,SHORT_STOPLOSS,16

PL DF 
| Column | Meaning |
|---|---|
| `trade_id` | Trade number |
| `direction` | LONG/SHORT spread |
| `entry_date` | Entry date |
| `exit_date` | Exit date |
| `entry_zscore` | Entry z-score |
| `exit_zscore` | Exit z-score |
| `exit_reason` | Mean exit / stop loss / max holding |
| `holding_period` | Trading days |
concat
| `entry_price_A` | A price at entry |
| `exit_price_A` | A price at exit |
| `entry_price_B` | B price at entry |
| `exit_price_B` | B price at exit |
| `shares_A` | Number of A shares |
| `shares_B` | Number of B shares |
| `pnl_A` | P&L from A leg |
| `pnl_B` | P&L from B leg |
| `total_pnl` | Combined pair P&L |
| `trade_return` | Return from the trade |

In [78]:
from math import floor
initial_capital=100000
pandl_all=[]
for _,row in trade_df.iterrows():
    entry_date=row["entry_date"]
    exit_date=row["exit_date"]
    direction=row["direction"]
    entry_price_A=trading_data.loc[entry_date,"AMD"]
    entry_price_B=trading_data.loc[entry_date,"MSFT"]
    exit_price_A=trading_data.loc[exit_date,"AMD"]
    exit_price_B=trading_data.loc[exit_date,"MSFT"]
    shares_A=floor(initial_capital/(2*entry_price_A))
    shares_B=floor(initial_capital/(2*entry_price_B))
    if direction=="LONG":
        pnl_A=shares_A*(exit_price_A-entry_price_A)
        pnl_B=shares_B*(entry_price_B-exit_price_B)
    elif direction=="SHORT":
        pnl_A=shares_A*(entry_price_A-exit_price_A)
        pnl_B=shares_B*(exit_price_B-entry_price_B)
    total_pnl=pnl_A+pnl_B
    trade_return=total_pnl/initial_capital
    pandl_all.append(
        {
        "entry_price_A":entry_price_A,
        "exit_price_A":exit_price_A,
        "entry_price_B":entry_price_B,
        "exit_price_B":exit_price_B,
        "shares_A":shares_A,
        "shares_B":shares_B,
        "pnl_A":pnl_A,
        "pnl_B":pnl_B,
        "total_pnl":total_pnl,
        "trade_return%":trade_return*100
        }
                     )
pnl_df=pd.DataFrame(pandl_all)
pnl_df=pd.concat([
    trade_df,
    pnl_df
],axis=1)
pnl_df

,trade_id,direction,entry_date,exit_date,entry_zscore,exit_zscore,exit_reason,holding_period,entry_price_A,exit_price_A,entry_price_B,exit_price_B,shares_A,shares_B,pnl_A,pnl_B,total_pnl,trade_return%
0,1,LONG,2024-02-29 05:00:00+00:00,2024-03-05 05:00:00+00:00,-0.881727,-2.267345,LONG_STOPLOSS,3,192.53,205.13,413.64,402.65,259,120,3263.40,1318.80,4582.20,4.58220
1,2,SHORT,2024-06-13 04:00:00+00:00,2024-09-05 04:00:00+00:00,2.508991,1.990870,SHORT_MAX_HOLDING,57,159.90,139.44,441.58,408.39,312,113,6383.52,-3750.47,2633.05,2.63305
2,3,SHORT,2024-11-14 05:00:00+00:00,2024-12-09 05:00:00+00:00,2.528190,3.489555,SHORT_STOPLOSS,16,138.84,130.87,426.89,446.02,360,117,2869.20,2238.21,5107.41,5.10741

In [69]:
stock1="AMD"
stock2="MSFT"

In [80]:
from src.backtest.portfolio import build_equity_curve
portfolio_df = build_equity_curve(
    pnl_df,
    initial_capital=100000
)

portfolio_df

                       date  trade_id  trade_pnl  cumulative_pnl     equity
0 2024-03-05 05:00:00+00:00         1    4582.20         4582.20  104582.20
1 2024-09-05 04:00:00+00:00         2    2633.05         7215.25  107215.25
2 2024-12-09 05:00:00+00:00         3    5107.41        12322.66  112322.66